### ISSUE TITLE
cleanup checks for jar context execution

### ISSUE THREAD

**Issue by colinsurprenant** [elasticsearch/logstash#1229]
in many places there are checks for jar context execution like https://github.com/elasticsearch/logstash/blob/master/lib/logstash/inputs/log4j.rb#L46

these are not required anymore since logstash is not executed from a flatjar anymore.

**Comment by wiibaa** [comment]
@colinsurprenant apart from the two comments in grok and multilines filter I did not find anything else in plugins about jar execution check. In core maybe you could delete https://github.com/elasticsearch/logstash/blob/master/lib/logstash/JRUBY-PR1448.rb as it was only used in gembag.rb ?

**Comment by jsvd** [comment]
so this needs a PR removing JRUBY-PR1448.rb and it's require in rakelib/gems.rake https://github.com/elasticsearch/logstash/blob/master/rakelib/gems.rake#L3

**Comment by jsvd** [comment]
closed by #2422
