### ISSUE TITLE
Option to set up permissions for unix socket

### ISSUE THREAD

**Issue by z0rc** [elasticsearch/logstash#1239]
Unix server socket is created with default permissions 755. It's practically useless to have such mode as it allows only user under which logstash is running to write into socket. Whether logstash is running under root or unprivileged user other unprivileged processes aren't able to write data into it.

**Comment by jsvd** [comment]
moved this issue to the logstash-plugins/logstash-input-unix repository: https://github.com/logstash-plugins/logstash-input-unix/issues/1
