### ISSUE TITLE
input plugin for batch processing of file

### ISSUE THREAD

**Issue by anandaverma** [elasticsearch/logstash#1269]
The input file plugin is primarily designed for tailing a file with sincedb. Problem arises when we download logs overnight and let logstash process it and then delete files which leaves sincedb entry remains same and if new file get same inode number then either its partially read or not read at all depending on size of previous file being read. A separate batch input file plugin with not effect the current one but will give more options for specific  use case.

**Comment by jsvd** [comment]
I don't really see a benefit in this case of using the file input plugin. You'd probably be better off having your scripts do:

```
# download files
curl ...
# process logstash batch of files
cat logs/* | bin/logstash -f logstash.conf
```

If this is insufficient please reopen the issue :)
