### ISSUE TITLE
redhat init script can't start logstash when logfile belongs to user root

### ISSUE THREAD

**Issue by jgaedicke** [elasticsearch/logstash#1273]
with the commit of
https://github.com/elasticsearch/logstash/commit/618a0e70a03df6f27106cf08301c297b89a6a506
stdout and stderror are forwarded to the LS_LOG_FILE which is a great idea.

But when the file didn't exists it is created for the user "root".
The logstash process, running as user logstash, can't write to this log file and refuses to start.

**Comment by jsvd** [comment]
fixed in #1580
