### ISSUE TITLE
Separate logstash package

### ISSUE THREAD

**Issue by faxm0dem** [elasticsearch/logstash#1282]
I know many people having small setups use ELK, but even more people actually only use L, so it would make sense to reflect packaging accordingly instead of getting one large monolithic RPM.

Thanks!

**Comment by ph** [comment]
In Logstash 1.5 we will introduce a new plugin system allowing you to install or remove the plugin. This will allow you to easily customize your own installation. We don't have any plan to create individuals OS package for each plugins. You can get more information about the new architecture in this blog post http://www.elasticsearch.org/blog/plugin-ecosystem-changes/
