### ISSUE TITLE
Documentation request: example or brief tutorial utilizing sysv init scripts

### ISSUE THREAD

**Issue by novodinia** [elasticsearch/logstash#1291]
I see there are sysv init scripts in the `pkg` dir, but I'm not sure how to use them. Would someone please write a tutorial or an explanation of how to setup logstash as a service with the `docs/tutorials` or `docs` directory?

**Comment by untergeek** [comment]
No follow-up has been here for several months.  Feel free to re-open this if you feel it still needs to be addressed.

sysv init script how-to documents are a bit out of scope for Logstash.  Many can be found on google (or your favorite search engine).
