### ISSUE TITLE
clean up s3 output docs

### ISSUE THREAD

**Issue by kevinkluge** [elasticsearch/logstash#1340]
See http://logstash.net/docs/1.4.0/outputs/s3.

It has a lot of TODOs, transitions to and from italics that don't have a reason that I see, and just needs some formatting improvements.

This bug is to clean up the look and put the TODOs in some constrained place so they don't interrupt reading about what is present.

**Comment by suyograo** [comment]
Closed via https://github.com/logstash-plugins/logstash-output-s3/pull/1
