### ISSUE TITLE
USER grok pattern should allow '@' to support email address as username

### ISSUE THREAD

**Issue by jotbe** [elasticsearch/logstash#1357]
I just started tinkering with Logstash, Elasticsearch, Kibana et all and
I am following the tutorials right now. So far so awesome!

When I was trying to process some Apache logs with the pattern `COMBINEDAPACHELOG` I ran into a couple of
`_grokparsefailure` errors which were caused by authenticated users that
had email addresses as user names.

I extended the grok patterns to support an '@' in `USER` and wanted to
issue a pull request if this small fix is okay. I was wondering whether I should add a test case to https://github.com/elasticsearch/logstash/blob/master/spec/examples/parse-apache-logs.rb or somewhere else.

Kind regards

**Comment by untergeek** [comment]
Closing in favor of https://github.com/logstash-plugins/logstash-patterns-core/pull/4
