### ISSUE TITLE
fix unintended class level @logger leak

### ISSUE THREAD

**Issue by colinsurprenant** [elasticsearch/logstash#1365]
the `Config::Mixin::DSL#validate` class method initializes `@logger` which end up being defined  in the plugins at class level. 

the symptom was to be able to call `@logger` from a lambda defined at class level in a codec, which normally should not be possible since `@logger` normally should only exist in a plugin instance.

https://github.com/elasticsearch/logstash/blob/master/lib/logstash/config/mixin.rb#L192

**Comment by jordansissel** [comment]
I think we can close this; the code pointed at by the link doesn't mention @logger anymore
