### ISSUE TITLE
improve error handling for elasticsearch_http

### ISSUE THREAD

**Issue by jillesvangurp** [elasticsearch/logstash#1367]
I had some issues setting up the elasticsearch_http output. I had several working inputs but mysteriously nothing showed up in elasticsearch. I turned on verbose logging and there were no errors. After double and triple checking everything else, I modified the plugin to inspect what was happening and it turned out that elasticsearch was returning errors because the cluster was red (no quorum) because my index template required two replicas. This failed completely silently on the logstash side.

From my point of view a few things are wrong there:
1) The plugin does not check the status code that elasticsearch returns (500) and does not inspect the message that is returned. It should verify both the status and the message to be as expected and log an error if that is not the case.
2) The plugin only catches EOF exceptions and surely there are other things that might go wrong?
3) With verbose logging on (-vvv) there was no evidence of anything elasticsearch related even happening when in fact it was trying and failing. At debug level I would expect to see a message confirming when the plugin is trying to push events to elasticsearch and another debug message when that completes successfully and an error/warning otherwise.

**Comment by suyograo** [comment]
Hi, all the functionality of `elasticsearch_http` output was moved to `elasticsearch-output`. We are focusing all our efforts on that plugin. Thanks for the issue -- we just added retry support to elasticsearch-output that handles error codes(https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/2). Let us know what you think.
