### ISSUE TITLE
Showstopper bugs on Windows 7

### ISSUE THREAD

**Issue by javalama** [elasticsearch/logstash#1389]
On win7 64 bit (and possibly other windows versions) logstash is currently useless for these reasons:

1. Logstash locks logfiles when using file input. This means that rolling logs doesn't work at all. Even editing a logfile monitored by logstash is impossible.

2. There are clearly line ending issues as I get events with text "\r" and nothing more.

3. If there is something wrong with the config file (such as specifying the wrong port number for an output) Ctrl+C doesn't work - the process must be killed manually.

**Comment by suyograo** [comment]
All these issues are fixed with v0.6.1 of filewatch gem which is used by the file input.
