### ISSUE TITLE
s3 outputs - filename prefix ?

### ISSUE THREAD

**Issue by Poil** [elasticsearch/logstash#1417]
Hi,

It doesn't seem to be possible to add a prefix to simulate a directory on s3 output, it can be a nice feature. 

Best regards,

**Comment by ph** [comment]
Thank you, in the latest version of the plugin you can use the `prefix` option to simulate directory in your s3 bucket. see https://github.com/logstash-plugins/logstash-output-s3/blob/master/lib/logstash/outputs/s3.rb for more information.

**Comment by ipeisong** [comment]
Can I embed date into the prefix? To make it dynamic? Thanks.
