### ISSUE TITLE
Netflow v9 codec not working for Exinda router

### ISSUE THREAD

**Issue by rjbozzol** [elasticsearch/logstash#1432]
Hi,

I'm trying to use Logstash to process Netflow v9 logging from an Exinda router, but it doesn't seem to work at all. Netflow v5 works alright, but when I switch to v9 Logstash only throws this error message:

```No matching template for flow id 382 {:level=>warn}```

I'm really new to both Exinda _and_ Logstash, so I really don't know what could be going wrong. My first thought is that the YAML definition might be wrong, but I'm not certain, so I'm going to compare it against the CISCO specs.

Any help in resolving this would be highly appreciated.

**Comment by untergeek** [comment]
Closing, as it has been several months with no update.  Please feel free to re-open this issue at https://github.com/logstash-plugins/logstash-codec-netflow (the netflow codec has been moved).
