### ISSUE TITLE
logstash 1.4.1 as windows service

### ISSUE THREAD

**Issue by abouchama** [elasticsearch/logstash#1433]
Hello;

Looking in the documentation [1], I can not find an example to turn logstash 1.4.1 as windows service. 

There's any way to do it? 

It is possible to include an installer like ElasticSearch?

Thanks in advance.

[1] http://cookbook.logstash.net/recipes/windows-service/

**Comment by jordansissel** [comment]
We have several reports of users successfully using nssm. I'm content with this as the answer for now.
