### ISSUE TITLE
problem following http://logstash.net/docs/1.4.1/tutorials/getting-started-with-logstash

### ISSUE THREAD

**Issue by jho1965us** [elasticsearch/logstash#1443]
Later I found http://logstash.net/docs/1.4.1/tutorials/10-minute-walkthrough/ seems like 
the "getting-started-with-logstash" page has an out of date, command line args usage for bin/logstash:
    bin/logstash -e 'input { stdin { } } output { stdout { codec => rubydebug } }'
missing "agent" as first argument

**Comment by untergeek** [comment]
Duplicate of #1444.  Closed by #1296
