### ISSUE TITLE
problem following http://logstash.net/docs/1.4.1/tutorials/getting-started-with-logstash as windows user

### ISSUE THREAD

**Issue by jho1965us** [elasticsearch/logstash#1444]
When transforming commandline example to windows syntax I get a syntax error:
    c:\logstash-1.4.1>bin\logstash -e "input { stdin { } } output { elasticsearch { host => localhost } }"
    { was unexpected at this time.
    c:\logstash-1.4.1>
Adding "agent" (see #1443) does not make any different
    c:\logstash-1.4.1>bin\logstash agent -e "input { stdin { } } output { elasticsearch { host => localhost } }"
    { was unexpected at this time.
    c:\logstash-1.4.1>
Fix change line 58 of bin\logstash.bat:
    rem if "%*"=="deps" goto install_deps
    set x=%*
    set x=%x:"='%
    if "%x%"=="deps" goto install_deps

**Comment by untergeek** [comment]
Duplicate.  Closed by #1296
