### ISSUE TITLE
Make ignore_older_than logic useable beyond just the metrics filter

### ISSUE THREAD

**Issue by timbunce** [elasticsearch/logstash#1447]
Currently there seems to be no easy way to implement logic to "only do this for recent events". For example, only send recent errors to the irc output.

The metrics filter has an [ignore_older_than](http://logstash.net/docs/1.4.1/filters/metrics#ignore_older_than) attribute. That mechanism, or something like it would be very useful beyond just metrics.

Perhaps `ignore_older_than` could be moved to the output base class, so it can be used for all outputs (as suggested in the comments in the metrics code).

And/or perhaps it could be added to the base class of filters, so it can be used in filters like drop, mutate, metrics etc.

**Comment by untergeek** [comment]
Closing this as the work-around is good for now, and Jordan has future plans for addressing this.
