### ISSUE TITLE
S3 input fails with "invalid byte sequence in UTF-8"

### ISSUE THREAD

**Issue by davidpfahler** [elasticsearch/logstash#1448]
Hi all,

I'm using logstash-1.4.1 in ubuntu 14.04. When using the S3 input, after a minute or so of startup time I get the following error:

```
A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::S3 bucket=>"bucket_name", credentials=>["Key", "Secret"], tags=>["abp", "s3"], type=>"request", charset=>"UTF-8", region=>"us-east-1", region_endpoint=>"us-east-1">
  Error: invalid byte sequence in UTF-8 {:level=>:error}
```

I did add `chartset`, `region` and `region_endpoint` only to check if that would have an effect. It didn't. Here is my full `logstash.conf`:
```
input {
    s3 {
        bucket => "appbusinesspodcast.com"
        credentials => ["key", "secret"]
        tags => ["abp", "s3"]
        type => "request"
        charset => "UTF-8"
        debug => "true"
        region => "us-east-1"
        region_endpoint => "us-east-1"
    }
}

filter {
    if [type] == "request" {
        grok {
            match => [ "message", "%{TIMESTAMP_ISO8601:timestamp} %{NOTSPACE:loadbalancer} %{IP:client_ip}:%{NUMBER:client_port:int} %{IP:backend_ip}:%{NUMBER:backend_port:int} %{NUMBER:request_processing_time:float} %{NUMBER:backend_processing_time:float} %{NUMBER:response_processing_time:float} %{NUMBER:elb_status_code:int} %{NUMBER:backend_status_code:int} %{NUMBER:received_bytes:int} %{NUMBER:sent_bytes:int} %{QS:request}" ]
        }
        date {
            match => [ "timestamp", "ISO8601" ]
        }
    }
}
output {
    elasticsearch { embedded => true }
}
```

I'm not a ruby programmer, but I think I might have found the bug. ~~I think that in [s3.rb line 76-89](https://github.com/elasticsearch/logstash/blob/v1.4.1/lib/logstash/inputs/s3.rb#L76-L89) the `line` variable should be encoded against this very issue.~~ It is mentioned in ["Fight back UTF-8 Invalid Byte Sequences"](http://robots.thoughtbot.com/fight-back-utf-8-invalid-byte-sequences) that this can be accomplished like so:

```ruby
def replace_name(body, name)
  body
    .encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')
    .gsub(/joel/, name)
end
```

The `encode` part is what I think might be missing. 

**UPDATE**: I now got it to work using a different fix at the correct line. On [line 213]() instead of `File.open(filename) do |file|` it should say `File.open(filename, "r:UTF-8") do |file|`.

I hope we can find a way to resolve this. It's really annoying as it prevents me from using this otherwise awesome software. Thanks for all the great work :)

**Comment by ph** [comment]
Fixed in the latest version of the https://github.com/logstash-plugins/logstash-input-s3
