### ISSUE TITLE
logstash s3 plugin error

### ISSUE THREAD

**Issue by takeiteasily** [elasticsearch/logstash#1458]
When i use s3 plugin connects to S3 bucket has a problem(my bucket has a lot of log files ),logstash wouldn’t connect to S3,the error massage is :
{:timestamp=>"2014-06-20T12:45:34.024000+0800", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::S3 type=>\"cloudfront\", bucket=>\"my_bucket_name\", credentials=>[\"access_key\", \"secret_key\"], region_endpoint=>\"us-east-1\", backup_to_dir=>\"/data/s3/\"}>\n  Error: execution expired", :level=>:error}, Is someone knows this question how to resolve, my logstash version is 1.4.1.

**Comment by untergeek** [comment]
No response in several months.  If you still need help, please open an issue at the new plugin home: https://github.com/logstash-plugins/logstash-input-s3
