### ISSUE TITLE
Feature request: Heartbeat for RabbitMQ

### ISSUE THREAD

**Issue by kuteninja** [elasticsearch/logstash#1466]
I've noticed that our ELB is killing the Logstash connections when there's nothing moving in any direction. I've also found a guy with the same issue on HAproxy (https://groups.google.com/forum/#!topic/logstash-users/odP7k8dhinI).

Logstash reconnects after a few seconds, and it seems to work when there's a ton of logs to parse, but it should have a customizable heartbeat instead, so I can set it on 20s and ELB will assume that the connection don't need to be dropped and it will be seamless without log barfing when the connection is lost...

{:timestamp=>"2014-06-23T16:03:34.446000+0000", :message=>"RabbitMQ connection error: . Will reconnect in 10 seconds...", :level=>:error}
{:timestamp=>"2014-06-23T16:03:47.476000+0000", :message=>"RabbitMQ connection error: . Will reconnect in 10 seconds...", :level=>:error}
{:timestamp=>"2014-06-23T16:04:00.502000+0000", :message=>"RabbitMQ connection error: . Will reconnect in 10 seconds...", :level=>:error}
{:timestamp=>"2014-06-23T16:04:13.566000+0000", :message=>"RabbitMQ connection error: . Will reconnect in 10 seconds...", :level=>:error}
{:timestamp=>"2014-06-23T16:04:26.607000+0000", :message=>"RabbitMQ connection error: . Will reconnect in 10 seconds...", :level=>:error}
{:timestamp=>"2014-06-23T16:04:39.643000+0000", :message=>"RabbitMQ connection error: . Will reconnect in 10 seconds...", :level=>:error}
{:timestamp=>"2014-06-23T16:04:52.662000+0000", :message=>"RabbitMQ connection error: . Will reconnect in 10 seconds...", :level=>:error}
{:timestamp=>"2014-06-23T16:05:05.703000+0000", :message=>"RabbitMQ connection error: . Will reconnect in 10 seconds...", :level=>:error}

**Comment by untergeek** [comment]
Closing.  Migrated to: https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/9
