### ISSUE TITLE
Multiline: message stays in buffer until new log entry

### ISSUE THREAD

**Issue by wvdongen** [elasticsearch/logstash#1482]
Hello,

Currently when using the multiline codec a message will only be outputted when Logstash is able to determine the end of the log entry. The end of a multiline log message can only be determined when a new one comes in. When watching a log that doesn't receive many log entries this is annoying. It would be nice if it was possible to set somekind of timeout on the multiline functionality so the the buffer is outputted before the next log message comes in.

**Comment by suyograo** [comment]
Closing this. #1545 is merged in

**Comment by ChrisMagnuson** [comment]
I think this needs to be reopend. 

The bug still exists for the multiline **codec** and the multiline filter has been deprecated elastic/logstash#4386.

**Comment by ChrisMagnuson** [comment]
In case anyone else finds this and is trying to get the multiline codec to output the last log record that it has in its buffer after a timeout, the parameter you want is auto_flush_interval which was introduced with [Logstash 2.2](https://www.elastic.co/guide/en/logstash/2.2/plugins-codecs-multiline.html#plugins-codecs-multiline-auto_flush_interval).

The value is specified in seconds you want to wait before the codec flushes whatever it has into a new event.

Here is an example from a windows based logstash configuration:

```Ruby
input {
    file {
        path => "$LogstashFilePathValue"
        type => "DemandwareError"
        tags => "$EnvironmentName"
        start_position => "beginning"
        sincedb_path => "NUL"
        codec => multiline {
            pattern => "\A\[%{TIMESTAMP_ISO8601:demandware_timestamp} GMT\]"
            negate => true
            what => previous
            auto_flush_interval => 10
        }
    }
}
```
