### ISSUE TITLE
tcp input + multiline codec won't work correctly with huge ingress traffic

### ISSUE THREAD

**Issue by squiddle** [elasticsearch/logstash#1483]
the tcp input and the multiline codec interact really badly resulting in dropped and truncated messages.

the tcp input reads from a socket via socket.sysread(16384) this just reads the maximum data available on the socket. It does not read single lines.
 - the multiline codec will fail hardly as it assumes it only has to decode single complete lines
 - the default line codec is working correctly

easy to test just push more than one line to the tcp input which can be read in a single sysread call and use a multiline filter
  ``nc localhost 9001 < biglogfile.log #netcat does this very reliable for me (ubuntu 12.04)``

i do not know what the interface definition is but i think the multiline codec needs fixing. Probably by just using the line codec followed by the multiline codec. But this composition cannot be done via configuration.

**Comment by suyograo** [comment]
@jsvd has a fix here https://github.com/logstash-plugins/logstash-codec-multiline/pull/1

**Comment by suyograo** [comment]
merged via logstash-plugins/logstash-codec-multiline#1

**Comment by jogaco** [comment]
I am experiencing this problem right now, with latest version of logstash.
I have a very large text file.
When I run the logstash with a small input of from stdin, all is fine.
When I run it against a very large text file, random lines are sticked together with a newline.

**Comment by mib4fun** [comment]
I have the same issue. The lines are truncated like 
```
{
    "@timestamp" => "2016-09-09T14:38:22.019Z",
       "message" => "ed=10301, p1=177, p2=10045, p3=2, p4=21, p5=55, sr=12, sw=1, l=0, gc=0\nResponse-Body-Transformed: Dechunked\nProducer: ModSecurity for nginx (STABLE)/2.8.0 (http://www.modsecurity.org/); OWAS
P_CRS/2.2.9.\nServer: ModSecurity Standalone\nEngine-Mode: \"ENABLED\"\n--33b79b01-Z--",
      "@version" => "1",
          "tags" => [
        [0] "multiline",
        [1] "_grokparsefailure",
        [2] "_rubyexception"
    ],
          "path" => "/var/log/nginx/modsecurity/20160909/20160909-1438/20160909-143817-Ac8cfcAcbcAtAcAcTcAcAcAc",
          "host" => "ANY",
          "type" => "mod_security"
}
```

I'm using logstash 2.4
