### ISSUE TITLE
Support for "update" in elasticsearch plugin's `action` setting

### ISSUE THREAD

**Issue by robbles** [elasticsearch/logstash#1504]
Would it be possible to add a third option to this setting, so that partial updates can be made as well as inserts/deletes?

The use case I have is keeping an ES index in sync with another datastore, by sending incremental updates instead of the whole record.

It looks like this could be implemented here: https://github.com/elasticsearch/logstash/blob/master/lib/logstash/outputs/elasticsearch/protocol.rb#L221, but I'm not sure if there's some context here that I'm missing. If it's straightforward, I'd be happy to look into adding this.

**Comment by untergeek** [comment]
Closing in favor of #1581, and in lieu of the fact that the desired functionality is already present with the elasticsearch output plugin if `protocol => "http"` is used.  The node protocol update is almost ready to be merged (if it hasn't been already).

**Comment by colinsanders** [comment]
I can't make the (partial) "update" action work with protocol => "http" as suggested above (in logstash-1.5.0.rc2)
Would you mind share an example on how to make it work?
Thanks
