### ISSUE TITLE
add_field/add_tag doesn't work for multiline filter

### ISSUE THREAD

**Issue by hoelzro** [elasticsearch/logstash#1526]
Example:

```conf
input {
    stdin {}
}

filter {
    multiline {
        what      => "previous"
        pattern   => "^4$"
        add_field => { "fourth" => "4" }
        add_tag   => ["fourth"] 
    }   
}   

output {
    stdout {
        codec => json_lines {}
    }   
}   
```

    $ seq 1 10 | ./bin/logstash agent -f test.conf
    {"message":"1","@version":"1","@timestamp":"2014-07-11T15:32:35.873Z","host":"lepus"}
    {"message":"2","@version":"1","@timestamp":"2014-07-11T15:32:35.875Z","host":"lepus"}
    {"message":"3\n4","@version":"1","@timestamp":"2014-07-11T15:32:35.875Z","host":"lepus","tags":["multiline"]}
    {"message":"5","@version":"1","@timestamp":"2014-07-11T15:32:35.876Z","host":"lepus"}
    {"message":"6","@version":"1","@timestamp":"2014-07-11T15:32:35.876Z","host":"lepus"}
    {"message":"7","@version":"1","@timestamp":"2014-07-11T15:32:35.877Z","host":"lepus"}
    {"message":"8","@version":"1","@timestamp":"2014-07-11T15:32:35.877Z","host":"lepus"}
    {"message":"9","@version":"1","@timestamp":"2014-07-11T15:32:35.878Z","host":"lepus"}

**Comment by untergeek** [comment]
This behavior is completely different now with the current version of the multiline plugin.

With this config:
```
input {
    stdin {}
}

filter {
    multiline {
        what      => "previous"
        pattern   => "^4$"
        add_field => { "fourth" => "4" }
        add_tag   => ["fourth"]
    }
}

output {
    stdout {
        codec => json_lines
    }
}
```

Then run: `$ seq 1 10 | bin/logstash -f b.conf`

```json
{"message":"1","@version":"1","@timestamp":"2015-01-23T18:45:03.019Z","host":"Elasticbox","fourth":"4","tags":["fourth"]}
{"message":"2","@version":"1","@timestamp":"2015-01-23T18:45:03.020Z","host":"Elasticbox","fourth":"4","tags":["fourth"]}
{"message":"3\n4","@version":"1","@timestamp":"2015-01-23T18:45:03.020Z","host":"Elasticbox","tags":["multiline","fourth"],"fourth":"4"}
{"message":"5","@version":"1","@timestamp":"2015-01-23T18:45:03.020Z","host":"Elasticbox","fourth":"4","tags":["fourth"]}
{"message":"6","@version":"1","@timestamp":"2015-01-23T18:45:03.020Z","host":"Elasticbox","fourth":"4","tags":["fourth"]}
{"message":"7","@version":"1","@timestamp":"2015-01-23T18:45:03.020Z","host":"Elasticbox","fourth":"4","tags":["fourth"]}
{"message":"8","@version":"1","@timestamp":"2015-01-23T18:45:03.020Z","host":"Elasticbox","fourth":"4","tags":["fourth"]}
{"message":"9","@version":"1","@timestamp":"2015-01-23T18:45:03.020Z","host":"Elasticbox","fourth":"4","tags":["fourth"]}
{"message":"10","@version":"1","@timestamp":"2015-01-23T18:45:03.021Z","host":"Elasticbox","fourth":"4","tags":["fourth"]}
```

This means that every line that passes through the multiline filter will have the configured tags and extra fields added, not just matching lines.  This is the expected behavior.

Marking closed.
