### ISSUE TITLE
update doc for changes introduced in #1437

### ISSUE THREAD

**Issue by colinsurprenant** [elasticsearch/logstash#1527]
update developers documentation for changes introduced in #1437

**Comment by suyograo** [comment]
@colinsurprenant the README now says: 

> We recommend using flatland/drip for faster startup times during development. To tell Logstash to use drip, set USE_DRIP=1 in your environment.

This should be good, no?

**Comment by colinsurprenant** [comment]
Hmmm. Personally I think I would add a proper **Drip** section, especially to list the caveats etc...

**Comment by suyograo** [comment]
Closed via https://github.com/elasticsearch/logstash/pull/2484
