### ISSUE TITLE
Getting started section in README is incorrect

### ISSUE THREAD

**Issue by volker48** [elasticsearch/logstash#1543]
If you follow the README you will be greeted with the following error.

```shell
~/code/logstash> bin/logstash deps
ls: ~/code/logstash/vendor/jar/jruby-complete-*.jar: No such file or directory
Unable to access jarfile
```

To fix this I had to use `export USE_RUBY=1` or run the command like so `USE_RUBY=1 bin/logstash deps`. I can updated the README if you like, but not sure if the scripts in bin should be updated instead.

**Comment by ph** [comment]
The documentation was updated in the latest README of logstash.
The S3* plugins were updated to fallback the string manipulation in the codecs.
