### ISSUE TITLE
Error on nagios pattern

### ISSUE THREAD

**Issue by jeromeLB** [elasticsearch/logstash#1562]
On the nagios pattern, there is a missing closing curly bracket on the NAGIOSLOGLINE definition

On line 108, col 565
**%{NAGIOS_EC_LINE_DISABLE_HOST_CHECK|**
to be replaced by 
**%{NAGIOS_EC_LINE_DISABLE_HOST_CHECK}|**

**Comment by untergeek** [comment]
Migrated to https://github.com/logstash-plugins/logstash-patterns-core/issues/7
