### ISSUE TITLE
Windows startup crash

### ISSUE THREAD

**Issue by jonopwell** [elasticsearch/logstash#1564]
Conditions: 

Windows 7, Java 7u45 JRE, JRuby not explicity installed, following startup directions in http://logstash.net/docs/1.4.2/tutorials/getting-started-with-logstash. Have ElasticSearch 1.2.2 & Kabana 3.1.1 (are they compatible?). They were all downloaded from the same page basically.

Command Line:
C:\Program Files\ELK\LogStash\logstash-1.4.2\bin>logstash.bat –e ‘input { stdin { } } output { elasticsearch { host => localhost } }’

Stack Trace:
RubyIO.java:1468:in `fwrite’: java.lang.NullPointerException
        from RubyIO.java:1408:in `write’
        from RubyIO$INVOKER$i$1$0$write.gen:-1:in `call’
        from RubyClass.java:690:in `finvoke’
        from Helpers.java:502:in `invoke’
        from RubyBasicObject.java:363:in `callMethod’
        from RubyIO.java:2486:in `write’
        from RubyIO.java:2474:in `putsSingle’
        from RubyIO.java:2403:in `puts1’
        from RubyIO.java:2376:in `puts’
        from RubyIO$INVOKER$i$puts.gen:-1:in `call’
        from CachingCallSite.java:326:in `cacheAndCall’
        from CachingCallSite.java:170:in `call’
        from C:\Program Files\ELK\LogStash\logstash-1.4.2\lib\logstash\runner.rb:182:in `method__8$RUBY$run’ from C_3a_$Program_20_Files$ELK$LogStash$logstash_minus_1_dot_4_dot_2$lib$logstash$runner$method__8$RUBY$run:-1:in `call’ from C_3a_$Program_20_Files$ELK$LogStash$logstash_minus_1_dot_4_dot_2$lib$logstash$runner$method__8$RUBY$run:-1:in `call’
        from CachingCallSite.java:326:in `cacheAndCall’
        from CachingCallSite.java:170:in `call’
        from C:\Program Files\ELK\LogStash\logstash-1.4.2\lib\logstash\runner.rb:92:in `method__7$RUBY$main’ from C_3a_$Program_20_Files$ELK$LogStash$logstash_minus_1_dot_4_dot_2$lib$logstash$runner$method__7$RUBY$main:-1:in `call’ from C_3a_$Program_20_Files$ELK$LogStash$logstash_minus_1_dot_4_dot_2$lib$logstash$runner$method__7$RUBY$main:-1:in `call’
        from CachingCallSite.java:326:in `cacheAndCall’
        from CachingCallSite.java:170:in `call’
        from C:\Program Files\ELK\LogStash\logstash-1.4.2\lib\logstash\runner.rb:215:in `__file__’
        from C:\Program Files\ELK\LogStash\logstash-1.4.2\lib\logstash\runner.rb:-1:in `load’
        from Ruby.java:811:in `runScript’
        from Ruby.java:804:in `runScript’
        from Ruby.java:673:in `runNormally’
        from Ruby.java:522:in `runFromMain’
        from Main.java:395:in `doRunFromMain’
        from Main.java:290:in `internalRun’
        from Main.java:217:in `run’
        from Main.java:197:in `main’

**Comment by jordansissel** [comment]
I'll investigate this next week as my windows bugfxi spree continues.

**Comment by suyograo** [comment]
Dup of https://github.com/elasticsearch/logstash/issues/1426 which was fixed
