### ISSUE TITLE
Suggestion: Alter the standard plugin loading message to banish confusion

### ISSUE THREAD

**Issue by MonnyA** [elasticsearch/logstash#1570]
I've been trying to help out in the [Logstash Google group](https://groups.google.com/forum/#!forum/logstash-users) and one thing I see very often is people mistaking the standard plugin loading message as an actual error. E.g. what one person wrote:

> this is my ERROR>>
> Using milestone 2 input plugin 'file'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}

If their config file isn't configured properly, so that it doesn't process messages how they want, and they see that message they assume that the warning message is saying why their config isn't working. Whereas, in actual fact, their config is incorrect in some other way. And then they come to the message boards to ask what it means and how to fix it.

I'd like to propose that the message is changed slightly to emphasize that it is NOT an error so that people who are new to Logstash are not confused. Perhaps something more like:

> **Informational message: Input plugin 'file' has been activated successfully. This milestone 2** plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}

**Comment by ph** [comment]
I've changed the log level from `.warn` to `.info`, this information will only be show if you start logstash with the verbose flag. 

But by removing that, I think the user will miss it.

I propose we use the newly introduced `.terminal` method in cabin (see https://github.com/elasticsearch/logstash/pull/2409) to output to the user:

```
'File' input plugin activated successfully. 
```
