### ISSUE TITLE
ZLib Errors cause logstash to quit

### ISSUE THREAD

**Issue by rwilliamselab** [elasticsearch/logstash#1576]
Having multiple errors such as Zlib::DataError: invalid distance code and logstash Zlib::DataError: invalid block type that causes the logstash service to stop. Feeders to the service are from other logstash instances (4 of them) also running logstash and using the lumberjack protocol to send logs

**Comment by jsvd** [comment]
The fix for this zlib error has to do with large messages (over 16k), and a proposal for fix is here: elasticsearch/logstash-forwarder#384

**Comment by suyograo** [comment]
Fixed in https://github.com/elasticsearch/logstash-forwarder/pull/384
