### ISSUE TITLE
Allow pattern to match multiple times in string

### ISSUE THREAD

**Issue by fatmcgav** [elasticsearch/logstash#1586]
As outlined [here] (https://gist.github.com/fatmcgav/98cfd045a588f60bf968) it would be useful if it was useful to allow a single pattern to match multiple times in a single string, e.g. With a repetitive data format...

**Comment by jordansissel** [comment]
Grok is not the right tool for this, at least not right now.

The kv filter should be able to handle this. If it can't, please let us know.
