### ISSUE TITLE
init.d script on debian packages won't start (tested on Ubuntu 12.04)

### ISSUE THREAD

**Issue by rekibnikufesin** [elasticsearch/logstash#1592]
The init.d scripts on the debian packages don't seem to work properly.
__Steps to reproduce__
`vagrant init hashicorp/precise64`
`vagrant up`
`vagrant ssh`

Install repos and install logstash via `apt-get install logstash`

Create a small conf file to illustrate:
`vi /etc/logstash/conf.d/inputs.conf`

```
input { 
  file { 
    path => ["/var/log/auth.log"]
    type => "auth"
    start_position => beginning
  }
}
output {
  stdout {
    codec => rubydebug
  }
  file {
    path => ["/var/lib/logstash/auth.log"]
    codec => rubydebug
  }
}
```

Give logstash user rights to monitored file:
`usermod -a -G adm logstash`
Start logstash via init scripts:
`service logstash start`

Wait 5 minutes to ensure full startup.
Note the lack of function, specifically:
* logstash process can be seen running with `ps aux | grep logstash`
* no sincedb files seen with `ls -alh /var/lib/logstash`
* no file created per output config, as seen with `ls -alh /var/lib/logstash`

Stop the logstash service with `service logstash stop`
Modify logstash account so it can be logged:
`vim /etc/passwd`
remove `:/sbin/nologin`
Login as the logstash user
`su - logstash`

As the logstash user, start logstash to verify the desired operation:
`/opt/logstash/bin/logstash agent -f /etc/logstash/conf.d/ `
Note the expected output on the screen (from the stdout output)
`Ctrl + C` to kill the process.
Note the desired sincedb and output files as verified with `ls -alh /var/lib/logstash`

**Comment by kwibbly** [comment]
Can confirm what @caezs is seeing

**Comment by untergeek** [comment]
Closing in favor of #1398 and #1555 

Please direct comments to these issues.
