### ISSUE TITLE
Elasticsearch output does not flush when idle.

### ISSUE THREAD

**Issue by Zaharid** [elasticsearch/logstash#1596]
I am using logstash 1.4.2 to process a custom log file. Output is send to an Elasticsearch server in this way:

 ````
output {
  elasticsearch { 
  host => 'elhost' 
  idle_flush_time => 2
  }
}
````

But the last messages that are written on the file are not flushed to the ES server until new ones arrive. For sure, not every two seconds.

**Comment by untergeek** [comment]
Closing.  Addressed by #1545.
