### ISSUE TITLE
lumberjack plugin doesn't work with ssl key passphrase

### ISSUE THREAD

**Issue by jlintz** [elasticsearch/logstash#1597]
I generated a key using the instructions for the logstash-forwarder README.md

`openssl req -x509 -batch -nodes -newkey rsa:2048 -keyout logstash-forwarder.key -out logstash-forwarder.crt -days 3650`

Then to test, I put the key and cert in place and started logstash successfully.  Next, I set a passphrase on the key using 

`openssl rsa -aes256 -in logstash-forwarder.key -out logstash-forwarder.key.new && mv logstash-forwarder.key.new logstash-forwarder.key`

I placed the passphrase so my config looks like

```
input {
    lumberjack {
      port               => 12345
      ssl_certificate    => "/etc/ssl/logstash-forwarder.crt"
      ssl_key            => "/etc/ssl/logstash-forwarder.key"
      ssl_key_passphrase => "passphrase"
    }
}
output {
    stdout {}
    elasticsearch {
        cluster  => "logstash_es"
        protocol => "http"
        host     => "localhost"
    }
}
```

I started up logstash and receive the following error `The error reported is: \n  Neither PUB key nor PRIV key:`.  I verified the passphrase works by decrypting it with `openssl rsa -in logstash-forwarder.key -out logstash-forwarder.key.new`.  

Package versions:
My version of openssl is 1.0.1, I'm using Ubuntu 12.04.  Java is
```
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1~0.12.04.2)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)
```
logstash                         1.4.2-1-2c0f5a1                   An extensible logging pipeline
logstash-contrib                 1.4.2-1-efd53ef                   Community supported plugins for Logstash

Appreciate any suggestions.  Thanks

**Comment by jordansissel** [comment]
Pondering about this, when starting Logstash as a service through upstart, systemd, sysv init, etc, how are we able to provide input to enter the passphrase?

**Comment by jlintz** [comment]
@jordansissel well if they pass the `ssl_key_passphrase` in, then it's not necessary, I imagine it can prompt the user for input, similar to apache if it's not supplied in the config

**Comment by jordansissel** [comment]
@jlintz putting a passphrase in plain text right next to the encrypted key is unwise. If you are able to do that, why even have a key with a passphrase at all?

As for apache, I've only seen apache do this when invoked via sysv or apachectl processes, but as systemd, upstart, runit, daemontools, etc are all viable ways to run Logstash, and none of those will have access to stdin on your console (they are RPC-oriented control mechanisms).

**Comment by jlintz** [comment]
@jordansissel yea, and I agree, we actually punted on even doing that, it was mainly for storing the SSL cert in a location that some others had access to at the time, so we had a passphrase on it which only got put into place on that server for decryption.

**Comment by jordansissel** [comment]
@jlintz ahh, that's a fair point, like shared storage with an encrypted key but only decryption passphrase available locally on servers that need it.

**Comment by jordansissel** [comment]
I'll leave this open while we ponder how to do solve things for ssl passphrases. I am against adding an `ssl_key_passphrase` setting, but if we have to do this then that is what we will do.

This gets even trickier when we look forward to Logstash driven by an API (and possibly in a cluster!), distribution of credentials becomes something we need to solve securely.

**Comment by jordansissel** [comment]
Actually, I'll close this in favor of a "how to protect credentials"
