### ISSUE TITLE
kv filter: support escaped quotes

### ISSUE THREAD

**Issue by tisba** [elasticsearch/logstash#1605]
I found https://logstash.jira.com/browse/LOGSTASH-2272 via Google and I ran into the same issue. I could not sign up at JIRA[0] so I decided to open the issue here too.

[0] "We are currently unable to complete your sign up. There are no available licenses for JIRA."

**Comment by untergeek** [comment]
Closing in favor of https://github.com/logstash-plugins/logstash-filter-kv/issues/2
