### ISSUE TITLE
LoadError, no such file to load -- treetop/runtime/terminal_parse_failure

### ISSUE THREAD

**Issue by heungtae** [elasticsearch/logstash#1606]
Installed logstash version: 1.4.2
OS Env: SunOS 5.10 Generic_147440-22 sun4u sparc SUNW, SPARC-Enterprise
Java: 1.7.0_65, Java(TM) SE Runtime Enviroment (build 1.7.0_65-b17)
           Java Hotspot(TM) Server VM (build 24.65-b04, mixed mode)

When i try to start ...
I get

LoadError: no such file to load -- treetop/runtime/terminal_parse_failure
   require at org/jruby/RubyKernal.java:1085
   require at file:/users/logmgr/logstash/logstash-1.4.2./vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
...

**Comment by untergeek** [comment]
Unfortunately, Solaris is not an officially supported platform.  This is why the message occurs.

Some users have had limited success with Solaris (usually on x86 hardware, rather than Sparc), but we do not support it.
