### ISSUE TITLE
cleanup rabbitmq input/output plugins

### ISSUE THREAD

**Issue by colinsurprenant** [elasticsearch/logstash#1610]
PR #1607 had me review the plugin to discover some unused code at https://github.com/elasticsearch/logstash/blob/master/lib/logstash/outputs/rabbitmq/bunny.rb#L103-L108 and https://github.com/elasticsearch/logstash/blob/master/lib/logstash/outputs/rabbitmq/march_hare.rb#L103-L108

- I don't really like the coding style of the rabbitmq input/output plugins, they could be tidied up
- either remove this dead code or use it to log useful information
- bot input and output plugins should log in a consistent way

**Comment by untergeek** [comment]
Closed.  Split and migrated to:
https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/13
https://github.com/logstash-plugins/logstash-output-rabbitmq/issues/5
