### ISSUE TITLE
Email attachment with log contents

### ISSUE THREAD

**Issue by pareeohnos** [elasticsearch/logstash#1611]
I'm working on an app that uses log stash to handle all of our log files, and we want to send the log files as emails to a central server for processing by another application. The application that does the processing expects each email to have an attachment that contains the contents of these logs, and does not even look at the body of the email itself.

We don't have control over all the servers, as our application is deployed inside customer environments, and almost all of their SMTP servers inject footers into all emails being sent, hence we want to attach files rather than embed them in the body - Much easier to work with!

Currently, using log stash it is easy to send emails from the logs, but I quickly found that getting it to do what we wanted wasn't quite so easy. Whilst it does allow you to specify attachments, it expects that they are file paths and nothing more. After looking around in the code, it seems the underlying `Mail` gem does allow for content and file name to be supplied instead of just a file path, which is exactly what we need however log stash doesn't support this.

Inside `email.rb` the attachments are looped over, and added to the mail. I've made an alteration here which checks to see if a path, or a hash has been supplied before passing it the the `Mail` gem. I then found that the `Mail` gem expects a hash with symbols as keys and not string as log stash produces, so had to quickly convert them to symbols. 

Following this, the attachment contents also need to be evaluated via `sprintf` so that the content can be customised. Below is the attachment adding of my modified version.

      @attachments.each do |fileLocation|
        if fileLocation.kind_of?(String)
          mail.add_file(fileLocation)
        else
          fileOpts = fileLocation.dup
          fileOpts.keys.each do |key|
            fileOpts[(key.to_sym rescue key) || key] = fileOpts.delete(key)
            if key == 'content'
              fileOpts[:content] = event.sprintf(fileOpts[:content])
            end
          end
          mail.add_file(fileOpts)
        end
      end # end @attachments.each

Would you consider adding this to the main project? I'll happily put together a pull request if so? This allows you to create a configuration such as

    input {
      file {
        path => ['/log/file/path/*']
      }
    }

    output {
      email {
        to => 'no@reply.com'
        attachments => [{ 
          filename => 'attachment_name.txt'
          content => "%{message}"
        }]
        options => {
          smtpIporHost => 'localhost'
          port => 1025
        }
      }
    }

Which produces an email, with an attachment containing the entire message.
It would be great to see this added, as keeping a modified version up to date is always annoying

**Comment by untergeek** [comment]
We'd love to have you issue a pull request for this! (Sorry it's taken us so long to get to it).

Please submit the PR to http://github.com/logstash-plugins/logstash-output-email as this is where the plugin now resides.  Starting with Logstash 1.5, all plugins are independent of the Logstash core code, and can be updated independently (as they are ruby gems now).
