### ISSUE TITLE
Add "sample" endpoint support for twitter inputs

### ISSUE THREAD

**Issue by johtani** [elasticsearch/logstash#1620]
Now, Twitter input is only "filter" endpoint support, that means we need "keywords" property.
I want to use "sample" endpoint for collecting many tweet.

I think we have two option for implementing.

1. change "keywords" to "optional"
   If we don't specify "keyword" property, Twitter input use "sample" endpoint.
2. add "sample" property
   If we set "sample" property to "true", Twitter input use "sample" endpoint.

**Comment by untergeek** [comment]
Migrating this issue the twitter input plugin's dedicated repository at https://github.com/logstash-plugins/logstash-input-twitter/issues/6
