### ISSUE TITLE
NameError: uninitialized constant Nokogiri::XERCES_VERSION

### ISSUE THREAD

**Issue by ShimiTaNaka** [elasticsearch/logstash#1621]
It appears that when running logstash with the runner, the nokogiri fails to find a constant, the stack is:
NameError: uninitialized constant Nokogiri::XERCES_VERSION
    const_missing at org/jruby/RubyModule.java:2690
          to_hash at /opt/logstash/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.1-java/lib/nokogiri/version.rb:71
         Nokogiri at /opt/logstash/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.1-java/lib/nokogiri/version.rb:97
           (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.1-java/lib/nokogiri/version.rb:1
          require at org/jruby/RubyKernel.java:1085
          require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
          require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53
          require at /opt/logstash/lib/logstash/JRUBY-6970.rb:27
          require at /opt/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.4/lib/polyglot.rb:65
           (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.1-java/lib/nokogiri.rb:1
          require at org/jruby/RubyKernel.java:1085
          require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
          require at file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53
          require at /opt/logstash/lib/logstash/JRUBY-6970.rb:27
          require at /opt/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.4/lib/polyglot.rb:65
           (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.1-java/lib/nokogiri.rb:29
           (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-1.35.0/lib/aws/s3/client.rb:1
             call at org/jruby/RubyProc.java:271
           (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-1.35.0/lib/aws/s3/client.rb:20
           (root) at /opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-1.35.0/lib/aws/core/configuration.rb:1
      add_service at /opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-1.35.0/lib/aws/core/configuration.rb:470
        s3_client at /opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-1.35.0/lib/aws/core/configuration.rb:384
       initialize at /opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-1.35.0/lib/aws/core/service_interface.rb:73
             each at org/jruby/RubyArray.java:1613
    aws_s3_config at /opt/logstash/lib/logstash/outputs/s3.rb:164
  write_on_bucket at /opt/logstash/lib/logstash/outputs/s3.rb:187
           upFile at /opt/logstash/lib/logstash/outputs/s3.rb:223
           upFile at /opt/logstash/lib/logstash/outputs/s3.rb:215
             call at org/jruby/RubyProc.java:271
          receive at /opt/logstash/lib/logstash/outputs/s3.rb:329
           handle at /opt/logstash/lib/logstash/outputs/base.rb:86
       initialize at (eval):43

As described in this bug: https://logstash.jira.com/browse/LOGSTASH-2060
Per small investigation, the constant should be available here:
https://github.com/sparklemotion/nokogiri/blob/8fe2c2b3ef532626fd23d995f8f2b45228f6dee0/ext/java/nokogiri/NokogiriService.java#L119-L120

**Comment by untergeek** [comment]
Closing since it's been 3 months with no reply.  If this is still affecting you, please open new issues at the respective repositories:
http://github.com/logstash-plugins/logstash-output-s3
http://github.com/logstash-plugins/logstash-output-elasticsearch
