### ISSUE TITLE
Provide ability in config file to declare a variable that can be referenced throughout the file (e.g. pattern_dir)

### ISSUE THREAD

**Issue by woolfie** [elasticsearch/logstash#1629]
In a large logstash config file, I often find myself having to specify the same pattern_dir for the grok filter multiple times throughout the file.

It would be very helpful if I could set this path once at the top of the config file and then refer to it throughout the file.

This is just one example where the ability to set and reference a variable would be useful, I'm sure there are others.

**Comment by suyograo** [comment]
Closed based on @jordansissel comments

**Comment by grahamoregan** [comment]
This is something that seems to keep coming up (from googling for a solution), one case where a templated file won't work is deploying logstash in an asg on ec2 with prebaked AMIs - the endpoints may not be known at the time that the AMI is created but UserData could populate the environment.

**Comment by reinaldovale** [comment]
Não sei se é thread safe.
@metadata somente no logstash 1.5. Retire isso em versões anteriores.

ruby{
        code => "$data_atualizacao = $data_atualizacao ? $data_atualizacao : (event['[@metadata][data_atualizacao]'].to_s)
                 event['data_atualizacao'] = $data_atualizacao"
    }

**Comment by blindpet** [comment]
@jordansissel do you have any resources for using ansible, puppet or check config template variables with logstash?

**Comment by bozernov** [comment]
Being able to set a variable will give possibility to use it in multiline - to join lines which have the same timestamps for example.
