### ISSUE TITLE
Move cloudfront stuff from s3 input into a codec

### ISSUE THREAD

**Issue by jordansissel** [elasticsearch/logstash#1630]
The S3 input has partial support for cloudfront log format in this 'metadata' thing in the code. This kind of 'format-specific' concern belongs in a codec, for sure! Further, moving it into a codec would improve performance of the S3 input and reduce code complexity.

Doing this change would fix the following bug: https://logstash.jira.com/browse/LOGSTASH-2220

**Comment by ph** [comment]
The cloudfront logic was extracted into his own codec, you need the latest version of the
https://github.com/logstash-plugins/logstash-input-s3/ to use it and the https://github.com/logstash-plugins/logstash-codec-cloudfront
