### ISSUE TITLE
elasticsearch output plugin: rejected docs in bulk indexing partial failure are silently lost

### ISSUE THREAD

**Issue by colinsurprenant** [elasticsearch/logstash#1631]
if the bulk indexing request returns a 200 OK but contains partial failures, these rejected doc are silently lost.

some documents in a bulk request can fail indexing with "EsRejectedExecutionException[rejected execution (queue capacity XX)” but the bulk request response still returns with a  200 success. Here’s
such a response example:

```
{"took":5324,"errors":true,"items”:[
  {"create":{"_index":"logstash 2014.08.11.16","_type":"logs","_id":"HwBm8IAZT1ycsdJidIPlOQ","_version":1,"status":201}},
  {"create":{"_index":"logstash-2014.08.11.16","_type":"logs","_id":"i6Xy10NUTyyd4V-ns Dt0w","_version":1,"status":201}},
  …
  {"create":{"_index":"logstash 2014.08.11.16","_type":"logs","_id":"4RjTBGGhSaCVNSiMFyf9PA","status":503,"error":"RemoteTransportException[[elasticsearch-d6.pardot.com][inet[/10.60.57.163:9300]][bulk/shard]]; nested: EsRejectedExecutionException[rejected execution (queue
capacity 200) on org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1@3da71c15]; "}},
  …
]}
```

This could be handled with a retry queue + an exponential backoff plus a time & size  limit where documents could be routed to a “rejections” file output for example. doing this would handle temporary hickups and would avoid loosing trace of rejected documents. User could then easily re-feed the rejected documents once the situation is resolved.

**Comment by talevy** [comment]
fixed by https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/2
