### ISSUE TITLE
Support DSL style queries in Elasticsearch input plugin

### ISSUE THREAD

**Issue by ppf2** [elasticsearch/logstash#1635]
Have a use case in the field where ES data have to be extracted from 1 site and shipped to a remote site for analysis.  The Elasticsearch input plugin is a great tool right now to be able to efficiently export data from an Elasticsearch index.  Currently this plugin supports only Lucene style queries.  It will be nice to add DSL support for more query and caching flexibility (eg. perhaps allow the end user to define a query in an external text file and reference the file and the plugin can simply read in the query, etc..)

**Comment by jordansissel** [comment]
-1 on heredocs.

**Comment by jordansissel** [comment]
The elasticssearch input plugin now supports this:

https://github.com/logstash-plugins/logstash-input-elasticsearch/blob/144f81d2272621fd7a21de38921726b7ac2ea140/lib/logstash/inputs/elasticsearch.rb#L44

The
