### ISSUE TITLE
urldecode error Encoding::CompatibilityError: incompatible encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by khornberg** [elasticsearch/logstash#1638]
I am parsing logs with urls and then trying to create an decoded field using the `urldecode` filter. 

Some urls have caused an error (shown below) where logstash throws an exception and hangs. I can only stop the process by killing it.

The url below is encoded with `\n` characters. Those show up when I run the string through `URI.unescape()` in an irb session. That too is shown below.

I'm not sure what is causing the errors. Logstash has consistently errored on the same log when I have tried to run it through again (after deleting the `.since` file).  
This occurs in about 0.0001% of the logs (~25M) I have.  

I don't know what would cause this error.   

The raw log has two urls. Both from Amazon.  
The first one is encoded and the second one is not. The second url also has `\n` characters which is strange for a url but that is auxiliary to the problem.  

Logstash reads the lines and tries to parse them as shown in the grok parsing error output. Logstash fails which is expected because I am not expecting `\n` characters.

Then the next output is the exception.

## Raw Log

```
[14/Aug/2014:09:28:33 -0500] 200 "GET http://fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:180-6327007-2173202:1SS93XT5M0GA50YY9F7D$uedata=s:%2Fdp%2FB00IAA5BSS%2Fref%3Ddra_a_sm_hp_ho_it_P1400_1000%2Fuedata%2Fnvp%2Funsticky%2F180-6327007-2173202%2FDetail%2Fntpoffrw%3Fld%26v%3D0.811.2%26id%3D%0A%0A%0A00FJT63VJ75HDW3FH6K0%0A%0A%0A%26ctb%3D1%26m%3D1%26sc%3DB00LO3K0021%26af%3D2927%26cf%3D3031%26pc%3D3207%26ld%3D3207%26t%3D1408026513217%26csmtags%3Daui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%26pty%3DDetail%26spty%3DGlance%26pti%3DB00IAA5BSS%26tid%3D1SS93XT5M0GA50YY9F7D%26aftb%3D1:38589 HTTP/1.1" "http://www.amazon.com/dp/B00IAA5BSS/ref=dra_a_sm_hp_ho_it_P1400_1000?tag=dradisplay-20&ascsubtag=4a251a2ef9bbf4ccc35f97aba2c9cbda" "image/gif" "ATVPDKIKX0DER:180-6327007-2173202:1SS93XT5M0GA50YY9F7D$uedata=s:/dp/B00IAA5BSS/ref=dra_a_sm_hp_ho_it_P1400_1000/uedata/nvp/unsticky/180-6327007-2173202/Detail/ntpoffrw%3Fld&v=0.811.2&id=


00FJT63VJ75HDW3FH6K0


&ctb=1&m=1&sc=B00LO3K0021&af=2927&cf=3031&pc=3207&ld=3207&t=1408026513217&csmtags=aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax&pty=Detail&spty=Glance&pti=B00IAA5BSS&tid=1SS93XT5M0GA50YY9F7D&aftb=1:38589" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"
```

## Grok parsing errors

The log entry is not formed as expected. The grok parsing errors are not what I'm concered with. Included here to show that each line is read.

```
{
       "message" => "[14/Aug/2014:09:28:33 -0500] 200 \"GET http://fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:180-6327007-2173202:1SS93XT5M0GA50YY9F7D$uedata=s:%2Fdp%2FB00IAA5BSS%2Fref%3Ddra_a_sm_hp_ho_it_P1400_1000%2Fuedata%2Fnvp%2Funsticky%2F180-6327007-2173202%2FDetail%2Fntpoffrw%3Fld%26v%3D0.811.2%26id%3D%0A%0A%0A00FJT63VJ75HDW3FH6K0%0A%0A%0A%26ctb%3D1%26m%3D1%26sc%3DB00LO3K0021%26af%3D2927%26cf%3D3031%26pc%3D3207%26ld%3D3207%26t%3D1408026513217%26csmtags%3Daui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%26pty%3DDetail%26spty%3DGlance%26pti%3DB00IAA5BSS%26tid%3D1SS93XT5M0GA50YY9F7D%26aftb%3D1:38589 HTTP/1.1\" \"http://www.amazon.com/dp/B00IAA5BSS/ref=dra_a_sm_hp_ho_it_P1400_1000?tag=dradisplay-20&ascsubtag=4a251a2ef9bbf4ccc35f97aba2c9cbda\" \"image/gif\" \"ATVPDKIKX0DER:180-6327007-2173202:1SS93XT5M0GA50YY9F7D$uedata=s:/dp/B00IAA5BSS/ref=dra_a_sm_hp_ho_it_P1400_1000/uedata/nvp/unsticky/180-6327007-2173202/Detail/ntpoffrw%3Fld&v=0.811.2&id=",
      "@version" => "1",
    "@timestamp" => "2014-08-15T14:20:50.350Z",
          "tags" => [
        [0] "_grokparsefailure"
    ]
}
{
       "message" => "",
      "@version" => "1",
    "@timestamp" => "2014-08-15T14:20:50.352Z",
          "tags" => [
        [0] "_grokparsefailure"
    ]
}
{
       "message" => "",
      "@version" => "1",
    "@timestamp" => "2014-08-15T14:20:50.354Z",
          "tags" => [
        [0] "_grokparsefailure"
    ]
}
{
       "message" => "00FJT63VJ75HDW3FH6K0",
      "@version" => "1",
    "@timestamp" => "2014-08-15T14:20:50.355Z",
          "tags" => [
        [0] "_grokparsefailure"
    ]
}
{
       "message" => "",
      "@version" => "1",
    "@timestamp" => "2014-08-15T14:20:50.356Z",
          "tags" => [
        [0] "_grokparsefailure"
    ]
}
{
       "message" => "",
      "@version" => "1",
    "@timestamp" => "2014-08-15T14:20:50.357Z",
          "tags" => [
        [0] "_grokparsefailure"
    ]
}
{
       "message" => "&ctb=1&m=1&sc=B00LO3K0021&af=2927&cf=3031&pc=3207&ld=3207&t=1408026513217&csmtags=aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax&pty=Detail&spty=Glance&pti=B00IAA5BSS&tid=1SS93XT5M0GA50YY9F7D&aftb=1:38589\" \"Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36\"",
      "@version" => "1",
    "@timestamp" => "2014-08-15T14:20:50.360Z",
          "tags" => [
        [0] "_grokparsefailure"
    ]
}
```

## Error

This error hangs logstash.

    Exception in filterworker {"exception"=>#<Encoding::CompatibilityError: incompatible encodings: ASCII-8BIT and UTF-8>, "backtrace"=>["org/jruby/RubyString.java:3041:in `gsub'", "file:/home/nsm/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/uri/common.rb:331:in `unescape'", "file:/home/nsm/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/uri/common.rb:649:in `unescape'", "/home/nsm/logstash-1.4.2/lib/logstash/filters/urldecode.rb:44:in `urldecode'", "/home/nsm/logstash-1.4.2/lib/logstash/filters/urldecode.rb:33:in `filter'", "(eval):225:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/home/nsm/logstash-1.4.2/lib/logstash/pipeline.rb:262:in `filter'", "/home/nsm/logstash-1.4.2/lib/logstash/pipeline.rb:203:in `filterworker'", "/home/nsm/logstash-1.4.2/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error}

## irb rest

    irb(main)> value="http://fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:180-6327007-2173202:1SS93XT5M0GA50YY9F7D$uedata=s:%2Fdp%2FB00IAA5BSS%2Fref%3Ddra_a_sm_hp_ho_it_P1400_1000%2Fuedata%2Fnvp%2Funsticky%2F180-6327007-2173202%2FDetail%2Fntpoffrw%3Fld%26v%3D0.811.2%26id%3D%0A%0A%0A00FJT63VJ75HDW3FH6K0%0A%0A%0A%26ctb%3D1%26m%3D1%26sc%3DB00LO3K0021%26af%3D2927%26cf%3D3031%26pc%3D3207%26ld%3D3207%26t%3D1408026513217%26csmtags%3Daui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%7Caui%7Caui%3Aajax%26pty%3DDetail%26spty%3DGlance%26pti%3DB00IAA5BSS%26tid%3D1SS93XT5M0GA50YY9F7D%26aftb%3D1:38589"

    irb(main):024:0> URI.unescape(value)
    => "http://fls-na.amazon.com/1/batch/1/OP/ATVPDKIKX0DER:180-6327007-2173202:1SS93XT5M0GA50YY9F7D$uedata=s:/dp/B00IAA5BSS/ref=dra_a_sm_hp_ho_it_P1400_1000/uedata/nvp/unsticky/180-6327007-2173202/Detail/ntpoffrw?ld&v=0.811.2&id=\n\n\n00FJT63VJ75HDW3FH6K0\n\n\n&ctb=1&m=1&sc=B00LO3K0021&af=2927&cf=3031&pc=3207&ld=3207&t=1408026513217&csmtags=aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax|aui|aui:ajax&pty=Detail&spty=Glance&pti=B00IAA5BSS&tid=1SS93XT5M0GA50YY9F7D&aftb=1:38589"

**Comment by jordansissel** [comment]
Fixed by https://github.com/logstash-plugins/logstash-filter-urldecode/pull/1
