### ISSUE TITLE
Make record offset available for file input

### ISSUE THREAD

**Issue by cdahlqvist** [elasticsearch/logstash#1641]
Logstash-forwarder includes the file offset for generated events. This is great to have when trying to identify duplicate events, and it would be very useful if the `file` input plugin also provided the offset as part of the generated event.

**Comment by jordansissel** [comment]
Still in agreement. We have some plans for big improvements to the file input and I'll make sure this is included.

I'm going to move this to the file input repo.

**Comment by jordansissel** [comment]
https://github.com/logstash-plugins/logstash-input-file/issues/7
