### ISSUE TITLE
Useragent plugin not parsing some strings correctly

### ISSUE THREAD

**Issue by arctica** [elasticsearch/logstash#1669]
Hi, I've been using the useragent plugin of logstash and found it very useful but encountered a problem with some user agents not being parsed properly.

A useragent string like "Mozilla/5.0 (Windows NT 6.3; Win64; x64; Trident/7.0; rv:11.0) like Gecko" will have the ua.os field set to just "Windows" while it should be "Windows 8.1".

The regexes.yml file contains appropriate regexes as shown below and testing the string on http://www.whatsmyua.info/ also identifies it correctly.

    - regex: '(Windows NT 6\.3)' 
      os_replacement: 'Windows 8.1' 

Also I could not figure out what the difference between "ua.os" and "ua.os_name" is. They seem to always contain the same values.

**Comment by untergeek** [comment]
The original complaint, that `regexes.yaml` needs updating, is outside the scope of Logstash's control, as it comes as part of the `user_agent_parser` ruby gem (https://rubygems.org/gems/user_agent_parser/).  Updating the plugin—now possible with Logstash 1.5—will pull the latest version of the `user_agent_parser` ruby gem.  

You can obtain the latest yaml file from the uap-core github repo: https://github.com/ua-parser/uap-core/blob/master/regexes.yaml

If a change needs to be made to the user agent plugin code, please create a pull request or a new issue at http://github.com/logstash-plugins/logstash-filter-useragent
