### ISSUE TITLE
Eventlog input doesn't shutdown when asked.

### ISSUE THREAD

**Issue by jordansissel** [elasticsearch/logstash#1672]
A user on IRC reported that eventlog input (windows) prevents Logstash from terminating cleanly and appears to get stuck or at least ignores the shutdown request.

**Comment by suyograo** [comment]
Fix is in: https://github.com/logstash-plugins/logstash-input-eventlog/pull/4

**Comment by suyograo** [comment]
@jordansissel moving this to 1.5.0. This is an issue with a specific plugin and we can release the plugin separately.
