### ISSUE TITLE
File Input - buffering causing duplicate messages on logstash restart

### ISSUE THREAD

**Issue by brianlow** [elasticsearch/logstash#1679]
**Symptom**
Restarting logstash while it is reading a large file will cause it to duplicate some messages.

**Cause**
I think it is the buffering in tail.rb (_read_file) from ruby-filewatch. tail.rb reads the file in 16KB chunks, but doesn't update it's in-memory sincedb until all 16KB have been sent to logstash (and presumably processed - I don't yet understand how file.rb is wired in).

**Possible Fix - slow**
Reading in smaller chunks - using a 25 byte buffer caused no messages to be duplicate but a few to be dropped.

**Possible Fix - faster**
Update the in-memory sincedb hash after yielding each line (e.g. sincedb[inode] = filepos + line.length). Not sure how multi-byte character encodings are handled in ruby and/or logstash. 

Any thoughts? I'd be willing to work on a fix with some direction.

**Comment by jsvd** [comment]
I need to reproduce this..Another possible fix is handle this checkpointing during the plugin's teardown, and assure that if the since db was updated, all that content was dealt with before exiting

**Comment by jsvd** [comment]
moved to https://github.com/logstash-plugins/logstash-input-file/issues/8
