### ISSUE TITLE
how to remove the fields that used in the output 

### ISSUE THREAD

**Issue by lshb** [elasticsearch/logstash#1683]
I want to set index according to the file name, and I don't want the index has some useless fields, such as file name, 

 output{
         elasticsearch{
                  host => "192.168.1.10"
                  cluster => "ky_ESearch"
                 index => "%{file_dir}--%{file_name}"
                 index_type => "%{file_time}"
        }
}
like above, I don't want index has the fields:file_dir,file_name,file_time,but if I remove them from the object event,I won't get them in the output. how to do it?

**Comment by jordansissel** [comment]
This is possible now in Logstash 1.5 with `@metadata`. You can have data in an event under the `[@metadata]` field reference and it is NOT included in the event when serialized to JSON or other outputs.

In your example, ASSUMING you have put your file_dir, file_name, and file_time fields in `[@metadata]`:

```
 output{
         elasticsearch{
                  host => "192.168.1.10"
                  cluster => "ky_ESearch"
                 index => "%{[@metadata][file_dir]}--%{[@metadata][file_name]}"
                 index_type => "%{[@metadata][file_time]}"
        }
}
```
