### ISSUE TITLE
bin\logstash deps fails on win7(64bit) 

### ISSUE THREAD

**Issue by thmoeller** [elasticsearch/logstash#1701]
Just cloned a fork of logstash to my dev box on win7. Tried to install dependecies but always ran into these errors:

c:\Users\myuser\Documents\GitHub\logstash>bin\logstash deps
Installing gem dependencies. This will probably take a while the first time.
Fetching and installing gem: bundler (>= 1.3.5)
Fetching: bundler-1.7.2.gem (100%)
Successfully installed bundler-1.7.2
1 gem installed
Invalid gemspec in [c:/Users/myuser/Documents/GitHub/logstash/tools/../logstash.gemspec]: No such file or directory - git
c:/Users/myuser/Documents/GitHub/logstash/tools/Gemfile:6:in `(eval)': undefined method `runtime_dependencies' for nil:NilClass (NoMethodError)
       org/jruby/RubyBasicObject.java:1545:in `instance_eval'
       c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/dsl.rb:32:in `eval_gemfile'
       c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/dsl.rb:10:in `evaluate'
       c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/definition.rb:25:in `build'
       c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler.rb:154:in `definition'
       c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/cli/install.rb:76:in `run'
       c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/cli.rb:145:in `install'
       c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/vendor/thor/command.rb:27:in `run'
       c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/vendor/thor/invocation.rb:121:in `invoke_comm
and'
       c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/vendor/thor.rb:363:in `dispatch'
       c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/vendor/thor/base.rb:440:in `start'
       c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/cli.rb:9:in `start'
       c:\Users\myuser\Documents\GitHub\logstash\gembag.rb:63:in `(root)'
       org/jruby/RubyFixnum.java:275:in `times'
       c:\Users\myuser\Documents\GitHub\logstash\gembag.rb:61:in `(root)'
Bundler::GemfileError: There was an error in your Gemfile, and Bundler cannot continue.
    eval_gemfile at c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/dsl.rb:39
        evaluate at c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/dsl.rb:10
           build at c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/definition.rb:25
      definition at c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler.rb:154
             run at c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/cli/install.rb:76
         install at c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/cli.rb:145
             run at c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/vendor/thor/command.rb:27
  invoke_command at c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/vendor/thor/invocation.rb:121
        dispatch at c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/vendor/thor.rb:363
           start at c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/vendor/thor/base.rb:440
           start at c:/Users/myuser/Documents/GitHub/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.7.2/lib/bundler/cli.rb:9
          (root) at c:\Users\myuser\Documents\GitHub\logstash\gembag.rb:63
           times at org/jruby/RubyFixnum.java:275
          (root) at c:\Users\myuser\Documents\GitHub\logstash\gembag.rb:61

Any idea why this happens?? Already deleted local copy and did a reclone and also tried it on another machine, always with the same result as above.

**Comment by suyograo** [comment]
@thmoeller we moved to using `rake` to bootstrap the dev environment. Closing this
