### ISSUE TITLE
Copy over sync/async replication for ES output

### ISSUE THREAD

**Issue by electrical** [elasticsearch/logstash#1706]
In the old 'elasticsearch_http' output we have the sync/async replication option.
Perhaps worth to copy that back to the 'elasticsearch' output?

https://github.com/elasticsearch/logstash/blob/master/lib/logstash/outputs/elasticsearch_http.rb#L94

**Comment by jsvd** [comment]
moved to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/48
