### ISSUE TITLE
Logstash fails to start when a '.git' directory exists alongside it

### ISSUE THREAD

**Issue by RyanMorrison04** [elasticsearch/logstash#1708]
Tested against Mac OS X 10.9.4 and CentOS 6.5 x86-64, with Logstash 1.4.2.

To reproduce:

1. Download and extract the precompiled Logstash archive (https://download.elasticsearch.org/logstash/logstash/logstash-1.4.2.tar.gz)
2. Run Logstash with a blank configuration. (./bin/logstash -e 'input { stdin { } } output { stdout {} }')
3. Stop Logstash. Create a '.git' folder (mkdir .git) in the root directory of the extracted Logstash installation.
4. Run Logstash same as above.
5. Observe the following error:
```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- i18n (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/rmorrison/Downloads/logstash-1.4.2/lib/logstash/runner.rb:46:in `<main>'
```

Note that other hidden directories don't cause adverse effects - e.g. a '.test' directory. I can only reproduce this issue with '.git' directories.

**Comment by suyograo** [comment]
not sure this is an issue anymore with master. Closing. Let us know if it does not work for you
