### ISSUE TITLE
kv filter : Issue with kv on repeated key/values pairs, duplicate values emitted

### ISSUE THREAD

**Issue by fancellu** [elasticsearch/logstash#1714]
Using logstash 1.4.2

kv { 
   trim => ","
   include_keys=>["tradeId"]
  }

Now the message has tradeId=123, etc etc, tradeId=123

But now my tradeId=123,123 

Would be nice if it removed duplicates. In the mean time, is there a work around?

**Comment by talevy** [comment]
PR: https://github.com/logstash-plugins/logstash-filter-kv/pull/3
