### ISSUE TITLE
Unable to get Logstash Twitter input working through a web proxy

### ISSUE THREAD

**Issue by schmorgs** [elasticsearch/logstash#1743]
Hi,
I'm trying to get the logstash Twitter v1.4.2 input working through a proxy server (on both Linux and Windows), but having no luck.
The same configuration works without a proxy, but I get the error with a proxy ::

```
A plugin had an unrecoverable error. Will restart this plugin.
Plugin: <LogStash::Inputs::Twitter consumer_key=>"xxxxx, oauth_token=>"xxxx", keywords=>["bitcoin", "scotland"], type=>"twitter">
Error: Connection refused - Connection refused {:level=>:error}
```

Config looks something like this : 

```
input {
  twitter {
    consumer_key => "xxxx"
    consumer_secret => "xxxx"
    oauth_token => "xxxx"
    oauth_token_secret => "xxxx"
    keywords => ["bitcoin","scotland"]
    type => "twitter"
    full_tweet => true
  }
}
filter {
}
output {
  stdout {}
}
```

It looks like the Twitter input used to support proxy but it was removed.  Any plans to bring it back or any knows workaround I can try?

**Comment by suyograo** [comment]
Tracked by https://github.com/logstash-plugins/logstash-input-twitter/issues/7. Closing this. Thanks @schmorgs
