### ISSUE TITLE
Implement regex based gsub option in mutate filter

### ISSUE THREAD

**Issue by rockaBe** [elasticsearch/logstash#1748]
We want to anonymize some user data e.g. client_ip by replacing the last octet of IPv4 with 'xxx' or domain names in email adresses without eliminating the top level domain.

**Comment by suyograo** [comment]
Tested on 1.4.2 and 1.5.0.beta1 and regex works.

```
suyog@machine:~/bin/logstash-1.5.0.beta1$ bin/logstash -e ' input { stdin {}} filter { mutate { gsub => ["message", "\d$", "world" ] } }'
red3
{
       "message" => "redworld",
      "@version" => "1",
    "@timestamp" => "2015-01-30T21:56:24.671Z",
          "host" => "Suyogs-MacBook-Pro.local"
}
```

Also added tests to cover this: https://github.com/logstash-plugins/logstash-filter-mutate/pull/10
