### ISSUE TITLE
Question: How to add 3rd party gems into logstash? especially with older version

### ISSUE THREAD

**Issue by Kapaski** [elasticsearch/logstash#1765]
I am running Logstash 1.4.1, comparing to the latest, I can't find anywhere in my installation folders contains gem information (versus the latest code in github has those gembag.rb, Gemfile etc..)

My current issue is I need to use several gems that Logstash doesn't have out of box, simply `require 'gemname'` seems doesn't work. Could anyone direct me to the readings that explains how to add these 3rd party gems or show me some sample codes which can do this.

On the other hand, I have a v1.3.3 logstash running with the other customer, is it possible to add gems to that version or I have to bump it up ?
Thanks very much!

**Comment by suyograo** [comment]
Hi please take a look at the new plugin system we developed which makes adding dependent gems easier. more details here http://www.elasticsearch.org/blog/plugin-ecosystem-changes/
