### ISSUE TITLE
s3 input: do not require aws credentials (fallback to IAM roles)

### ISSUE THREAD

**Issue by danmilon** [elasticsearch/logstash#1778]
I'm using the S3 input to pull some logs from S3 and didn't configure the `credentials` part since I have configured the instance with IAM roles. Unfortunately I found out that the credentials are required. I searched a bit and found out that aws-sdk [works with IAM roles seamlessly](http://docs.aws.amazon.com/AWSSdkDocsRuby/latest/DeveloperGuide/ruby-dg-roles.html). So I suppose that it's going to be trivial to let it use that.

If it appears to be trivial, we can adopt this for all AWS related input/outputs.

Unfortunately my ruby skills are limited to some chefing, so I'd hesitate to go on and fix it, but if you could provide some guidance and feedback, I could give it a shot.

ps: The s3 input has no tests, right?

**Comment by ph** [comment]
You can now use IAM Role with the s3 input and s3 ouput in the master.
https://github.com/logstash-plugins/logstash-output-s3/
https://github.com/logstash-plugins/logstash-input-s3/

**Comment by ph** [comment]
STS is done in https://github.com/logstash-plugins/logstash-mixin-aws/pull/4 and should be merged shortly.

**Comment by innovia** [comment]
I took it from the master but it's complaining:

Unable to find JRuby.
If you are a user, this is a bug.
If you are a developer, please run 'rake bootstrap'. Running 'rake' requires the 'ruby' program be available.

why? i did not need Jruby before

am i doing something wrong?
Ami

**Comment by innovia** [comment]
my mistake sorry about that, i took the wrong master...

i am trying to install this from master of https://github.com/logstash-plugins/logstash-input-s3/

on logstash 1.4.2

do i have to install it on the beta 1.5?

is there a way to install it on 1.4.2?

**Comment by ph** [comment]
@innovia It _could_ be possible to use it in a logstash 1.4.2, But I would wait the RC1 release if possible.

**Comment by innovia** [comment]
for now i simply yanked out the @credentilals section along with its ENV['AWS... settings which is defaulting to IAM Roles

any idea when RC1 will be out ?

**Comment by anilvedala** [comment]
With the latest logstash version 2.0 , consider this scenario: If I create an IAM role while setting up an EC2 instance and install logstash instance on it,will I have to specify anything in configuration file more than the following:
s3{
bucket =>"name"
region =>"region"
}
