### ISSUE TITLE
Metrics filter not working with current master

### ISSUE THREAD

**Issue by matejzero** [elasticsearch/logstash#1805]
Hello!

I tried to do some benchmarking yesterday with the latest master, but metrics plugin is not working with that release.

I used various config settings, one of them was also the one suggested in metrics.rb plugin file:

    input {
     generator {
       type => "generated"
     }
    }

    filter {
      if [type] == "generated" {
        metrics {
          meter => "events"
          add_tag => "metric"
        }
      }
    }

    output {
      only emit events with the 'metric' tag
      if "metric" in [tags] {
        stdout {
          codec => line {
            format => "rate: %{events.rate_1m}"
          }
        }
      }
    }

Generator is generating event, so input works. I also added mutate's add_tag before if sentence and between metrics and I get 3 new tags, so it looks like it does go through filter section, but metrics plugin somehow doesn't produce output.

Can anyone confirm?
Is my syntax wrong?

**Comment by colinsurprenant** [comment]
relates to #1839 and logstash-plugins/logstash-filter-metrics#3

**Comment by colinsurprenant** [comment]
closing per logstash-plugins/logstash-filter-metrics#5, new plugin version 0.1.5 published
