### ISSUE TITLE
Input imap.rb - crash on no Date

### ISSUE THREAD

**Issue by plarivee** [elasticsearch/logstash#1806]
When a mail does not have a Date header, the plugin crash.

    {:timestamp=>"2014-09-29T16:43:12.059000-0400", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::IMAP host=>\"mx.xxxxx.com\", tags=>[\"imap_mail\"], user=>\"logs@logs.xxxxx.com\", content_type=>\"text/plain\">\n  Error: undefined method `to_time' for nil:NilClass", :level=>:error}

seems to be link to line 108-109 of lib/logstash/inputs/imap.rb

      # Use the 'Date' field as the timestamp
      event["@timestamp"] = mail.date.to_time.gmtime

I think there should be 
1- try / catch 
2- Maybe try the Received header if no Date. I think the Imap class has something extracting date already. ( Tried to play with it, but couldn't get it to work as I don't know ruby much )

https://github.com/mikel/mail/blob/08cd8f5d9cd89ac2d23eab09aa57f96af735c234/lib/mail/elements/received_element.rb

Here is a test mail failing.
https://gist.githubusercontent.com/anonymous/4de2e0490ca32150cba8/raw/33aa686a8a1bfd12b84185425a61cf5f7496e485/gistfile1.txt

**Comment by suyograo** [comment]
migrated to https://github.com/logstash-plugins/logstash-input-imap/issues/6
