### ISSUE TITLE
S3 output use an hardcorded path for tmp and fail creating directories

### ISSUE THREAD

**Issue by ph** [elasticsearch/logstash#1860]
When you are using the S3 output plugin and the "/opt/logstash/S3_temp" doesnt exist it will try to create the "S3_temp" but it wont do it recursively. 

Also there is no way to specify a custom directory, it should be a new option in the config file.

**Comment by ph** [comment]
fixed in https://github.com/logstash-plugins/logstash-output-s3/

**Comment by pruthvintss** [comment]
hey ph what about "way to specify a custom directory, it should be a new option in the config file."
