### ISSUE TITLE
silent msgpack crash

### ISSUE THREAD

**Issue by jrxFive** [elasticsearch/logstash#1869]
I have been attempting to use the mspack codec with a UDP output. I realize that msgpack does not handle datetime, and can see in msgpack.rb there is a call to the Float class for event["@timestamp"].to_f  .Even with --verbose --debug, logstash gives no indication in the logs than an error has occurred, nor do I see any code for the logger (encode function) to to do so ( it maybe a call higher up ). I am using logstash 1.4.2.

**Comment by jsvd** [comment]
Timestamp handling has been changed in the msgpack codec https://github.com/logstash-plugins/logstash-codec-msgpack/blob/master/lib/logstash/codecs/msgpack.rb#L44
Please reopen if the problem still occurs in 1.5.0beta1
