### ISSUE TITLE
Logstash skipping lines when moving between files

### ISSUE THREAD

**Issue by kryten68** [elasticsearch/logstash#1902]
In Windows the two log files below are to be processed by the conf also below. 

The first file, app1.log is read in and processed just fine. 

The second file is then processed - BUT the first three lines are skipped entirely. 
The second file typically starts at 'Identified 1 listener(s).'  It does this every single time.
 
This appears to only happen on Windows platform and happens on LS 1.4.1 and LS 1.4.2
 
Have tried all sorts of combinations and have now virtually given up. Would deeply appreciate any insights into what may be going on as this problem is seriously damaging to our uptake of the ELK stack.

THANKS

The text below is app1.log:
2014-09-09 00:00:00.000+0100 Starting...
2014-09-09 00:00:01.000+0100 Started
2014-09-09 00:00:02.000+0100 Listening...
2014-09-09 01:00:00.000+0100 Command received [shutdown]
2014-09-09 01:00:01.000+0100 Shutting down...
 
The text below is app2.log:
2014-09-09 00:00:00.000+0100 Starting initialization
2014-09-09 00:00:01.000+0100 Initialization completed successfully
2014-09-09 00:00:02.000+0100 Scanning for listeners
2014-09-09 00:00:03.000+0100 Identified 1 listener(s)
2014-09-09 00:00:04.000+0100 Registering 1 listeners(s)
2014-09-09 00:00:05.000+0100 Registered listeners #1
2014-09-09 00:00:06.000+0100 Registration complete successfully
 
Here is the conf (very simple):
 
input {
        file {
                path => [
                        "C:\ELK\app1.log",
                        "C:\ELK\app2.log"
                ]
                start_position => "beginning"
                sincedb_path => "C:\ELK\.sincedb"
        }
}
 
filter {
       
        grok {
                match => [ "message", "(?<datetime>\d\d\d\d-\d\d-\d\d \d\d:\d\d:\d\d\.\d\d\d\+\d\d\d\d)\s+(?<text>.*)" ]
        }
       
        if "_grokparsefailure" not in [tags] {
 
                date {
                        match => [ "datetime", "YYYY-MM-dd HH:mm:ss.SSSZ" ]
                }
        }
}
 
output {
        stdout {
                codec => rubydebug
        }
}

**Comment by tuespetre** [comment]
Just because I have not seen anyone explicitly mention it, this is what I've seen:

log file | length | position where file input starts reading it
----|----|----
150127.log | 59238 | 0
150202.log | 527171 | 59238 
150203.log | 729280 | 527171 
150204.log | 259862 | 0 
150205.log | 609396 | 259862 

So it starts reading, moves to the next file, tries to start at the length of the previous file, and if the file is not that long, starts back to 0 for that file (as we see with 150204.log.)

**Comment by kryten68** [comment]
Yes. Starting file y at the line number reached in file x is classic behaviour for this issue. Only on Windows though - never seen this on *nix or Mac. Thanks for confirming.

**Comment by kryten68** [comment]
Is there any update on this issue at all? We have been trying to work around it with the nio2 path input but that doesn't accept path globbing just filename globbing. 

Is there ANY kind of work around or fix on the horizon for this issue (missing entire files when globbing paths on Windows).

Thanks.

**Comment by elvarb** [comment]
I would just use nxlog in Windows to read file logs and parse them,  then ship those to logstash as json

**Comment by jordansissel** [comment]
@kryten68 there are patches in the file watching library we use that should fix this. If you note the milestone on this ticket, we anticipate having this resolved for the 1.5.0 rc1 release.

**Comment by tuespetre** [comment]
@jordansissel any idea for a date on that release?

@kryten68 @elvarb I am having success with the modified version here: https://github.com/jordansissel/ruby-filewatch/issues/39#issuecomment-66992110 using the tip given here: https://github.com/jordansissel/ruby-filewatch/issues/39#issuecomment-67136389. There is a disclaimer about using it in production but I have had success with it for the time being.

**Comment by suyograo** [comment]
Fixed in 0.6.1 of filewatch gem

**Comment by JeanFrancoisContour** [comment]
I had the same problem (Windows, missing lines) so I 've installed logstash-1.5.0.beta1
but I did not see any improvement
Still missing lines for Logstash file input
In my test, I copy/paste files one by one in a directory which is monitored by a Logstash agent.
Logstash still misses the first lines (10, 11, 16... ). 
Only one sincedb file
Windows 7 Enterprise
I may have missed something in the installation process. I only noticed to get 
jruby-complete-1.7.19
and store it in 
C:\logstash-1.5.0.beta1\vendor\jar
Thanks for great work around ELK

**Comment by ph** [comment]
@JeanFrancoisContour We just pushed a new release which include the new version of the filewatch that should fixes some of the windows issues. 
Could you redo your test with this version: http://www.elasticsearch.org/blog/announcing-logstash-1-5-0-release-candidate/ ?

**Comment by JeanFrancoisContour** [comment]
Issue resolved with the Logstash 1.5.0 RC1 
Tests OK for me
Thanks

**Comment by OuesFa** [comment]
@JeanFrancoisContour i have the same problem on windows with logstash 1.4.2.
To resolve this issue, did you use the 'logstash core download' without adding any plugin or features ?
Or did you use 'logstash 1.5.0 RC2 download' ? Thanks for your help.

**Comment by JeanFrancoisContour** [comment]
I used Logstash 1.5.0 RC1 but I guess Logstash 1.5.0 RC2 (http://download.elasticsearch.org/logstash/logstash/logstash-1.5.0.rc2.zip) is OK  too

**Comment by OuesFa** [comment]
Ok thanks.
I'm trying it. But a problem occurred.
It starts to parse my logs and ship them into ES, it works for a couple of seconds then it stops and i have an error message when i shut down the pipeline ^C (←[33m_sincedb_write rename/sync failed: c:\'path of my siincedb'. new -> 'path of my since_db': Permission denied )

Don't know if it stops because of this error or if it's another issue.
I found this topic (https://github.com/logstash-plugins/logstash-input-file/issues/16). It says that the error message has no effect on logstash

**Comment by JeanFrancoisContour** [comment]
I had sometimes a "since_db permission denied" message when I shut down the pipeline too, but I don't really care. 
My advice is to investigate somewhere else (parse failure ?)

**Comment by OuesFa** [comment]
Thanks for quick reply.

I thought it was a connection problem between LS and ES but even when i change my output conf to this one (output { if "_grokparsefailure" not in [tags] {stdout {}}}) 
Adding a condition on parse failures too, i still have the same problem, logstash starts then stops without reporting any error.

**Comment by OuesFa** [comment]
I had multiline filters in my LS conf that i removed. i'm testing right now and it seems to work.
So i have to find a workaround to multiline filter i guess.
