### ISSUE TITLE
[input / elasticsearch] retrieve also meta data

### ISSUE THREAD

**Issue by dadoonet** [elasticsearch/logstash#1904]
It would be nice to support `_id`, `_type`, `_index` fields (and any other available meta field).

Today, elasticsearch input only extract `_source` field:

```json
{
    "foo" => "bar",
    "@version" => "1",
    "@timestamp" => "2014-10-16T09:28:29.945Z",
    "type" => "doc"
}
```

**Comment by suyograo** [comment]
Fixed https://github.com/logstash-plugins/logstash-input-elasticsearch/pull/6
