### ISSUE TITLE
logstash does not work on ARM systems

### ISSUE THREAD

**Issue by rabinnh** [elasticsearch/logstash#1916]
Tested on Wandboard Quad, Ubuntu 14.04 (note that there are many reports of the same issue on Raspberry and other ARM systems).

rbross@wandboard-hollis1:~/temp/logstash-1.4.2$ bin/logstash -e 'input { stdin { } } output { stdout {} }'
LoadError: Could not load FFI Provider: (NotImplementedError) FFI not available: null
 See http://jira.codehaus.org/browse/JRUBY-4583
  require at org/jruby/RubyKernel.java:1085
  require at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
   (root) at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/ffi/ffi.rb:69
  require at org/jruby/RubyKernel.java:1085
   (root) at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
  require at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
  require at org/jruby/RubyKernel.java:1085
   (root) at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/ffi.rb:1
   (root) at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
  require at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
  require at org/jruby/RubyKernel.java:1085
     LibC at /home/rbross/temp/logstash-1.4.2/lib/logstash/util/prctl.rb:4
   (root) at /home/rbross/temp/logstash-1.4.2/lib/logstash/util/prctl.rb:3
     main at /home/rbross/temp/logstash-1.4.2/lib/logstash/runner.rb:79
   (root) at /home/rbross/temp/logstash-1.4.2/lib/logstash/runner.rb:215
rbross@wandboard-hollis1:~/temp/logstash-1.4.2$ 
rbross@wandboard-hollis1:~/temp/logstash-1.4.2$ hello world
-bash: hello: command not found
rbross@wandboard-hollis1:~/temp/logstash-1.4.2$ bin/logstash -e 'input { stdin { } } output { stdout {} }'
LoadError: Could not load FFI Provider: (NotImplementedError) FFI not available: null
 See http://jira.codehaus.org/browse/JRUBY-4583
  require at org/jruby/RubyKernel.java:1085
  require at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
   (root) at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/ffi/ffi.rb:69
  require at org/jruby/RubyKernel.java:1085
   (root) at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
  require at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
  require at org/jruby/RubyKernel.java:1085
   (root) at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/ffi.rb:1
   (root) at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
  require at file:/home/rbross/temp/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
  require at org/jruby/RubyKernel.java:1085
     LibC at /home/rbross/temp/logstash-1.4.2/lib/logstash/util/prctl.rb:4
   (root) at /home/rbross/temp/logstash-1.4.2/lib/logstash/util/prctl.rb:3
     main at /home/rbross/temp/logstash-1.4.2/lib/logstash/runner.rb:79
   (root) at /home/rbross/temp/logstash-1.4.2/lib/logstash/runner.rb:215

There have been suggestions that if the /tmp directory is mounted with the "noexec" option that this can happen, but I explicity remounted with exec and see no difference.  I've also seen that apparently the logstash jar contains a native libjffi library which would restrict it to a single platform, but as I am unfamiliar with logstash, I have no way of confirming this.

**Comment by ph** [comment]
This is the step people are doing to make in run under arm.
https://github.com/jruby/jruby/issues/1561#issuecomment-67953147

**Comment by ph** [comment]
I am closing this ticket, there is workaround to make it work on ARM. 
When JRuby have an out of the box version with support for arm, logstash will work.
