### ISSUE TITLE
New config option :validate => :bytes

### ISSUE THREAD

**Issue by ph** [elasticsearch/logstash#1921]
from a discussion with @jordansissel and me:
Adding :validate => :bytes to allow users to, from config, say :size_file => "10mb" and it 'just works' and under the hood we still get the base units (10mb == 10485760) but improves user input. 
Probably done when parsing the config file. Could also work with Timed based configuration "1m".

Related to the s3 output and the file rotation on size.

**Comment by colinsurprenant** [comment]
for intervals, this gem https://github.com/hpoydar/chronic_duration could be used.

**Comment by jordansissel** [comment]
I'd prefer supporting either ISO8601 durations or Elasticsearch's duration syntax. chronic_duration seems english-focused and may not do support ISO8601 or ES-style durations?

**Comment by colinsurprenant** [comment]
+1 for ES consistency

**Comment by talevy** [comment]
Do we want our prefixes to be in base-1024, or base-1000?
`1MB = 1000KB` VS `1MB = 1024KB`

**Comment by talevy** [comment]
Do we want to follow this policy for sizes?
https://wiki.ubuntu.com/UnitsPolicy

**Comment by talevy** [comment]
PR for this issue: https://github.com/elasticsearch/logstash/pull/2321
