### ISSUE TITLE
Trouble parsing json with plain text file

### ISSUE THREAD

**Issue by klepthys** [elasticsearch/logstash#1955]
I have a nginx log file that I want to monitor using logstash. Log format is quite classic : one line with timestamp, verb, etc...

my grok pattern seems OK ([debug](http://grokdebug.herokuapp.com/) work well)

I have this error : 
```
{:timestamp=>"2014-10-24T12:40:06.035000+0200", 
:message=>"Trouble parsing json", 
:source=>"message", 
:raw=>"hostname.net 192.168.1.21 [2014-10-24T12:14:00+02:00] \"GET /favicon.ico HTTP/1.1\" 500 594 \"-\" \"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.101 Safari/537.36\" 0.012 -", 
:exception=>#<JSON::ParserError: unexpected token at 'hostname.net 192.168.1.21 [2014-10-24T12:14:00+02:00] "GET /favicon.ico HTTP/1.1" 500 594 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.101 Safari/537.36" 0.012 -'>, :level=>:warn
}
```

Obviously, message is no JSON. But as my codec is set to "plain", why does logstash try to parse it?

**Comment by gershonsherman** [comment]
I don't know if you ever got this working but I was having the same problem and I tried changing the coded to json (codec => json {}) and that solved the issue for me.

**Comment by ph** [comment]
Sorry for taking so long to answer.

@klepthys did you resolve your issue?
From my local test setup the plain codec should work out of the box with regular file.
If this is still a problem feel free to reopen this ticket.

**Comment by klepthys** [comment]
It's still a problem but I can't figure out any clue of why it doesn't work. I'll leave it closed and reopen it when I have time to investigate
