### ISSUE TITLE
Make logstash available in Maven Central or Bintray

### ISSUE THREAD

**Issue by Batmat** [elasticsearch/logstash#1966]
Hi,

Would be great if you could publish your binaries onto central repositories like Maven Central or Bintray. This would definitely help users leverage existing infrastructures when coming to downloading things from a local repository manager (be it archiva, artifactory or Nexus).

Thanks!

**Comment by ph** [comment]
Currently we are pushing the tgz, and we provide repo for deb and rpm. Deb and rpm  packages allow you to run your own mirror or caching. Different corporate environment have different restrictions, we believe we give enough flexibility to our users. 

We don't plan in the short term to push our releases to the maven, this is something we may revisit later if we have more requests.

**Comment by Lloydshove** [comment]
I have the same usecase as Batmat.
Putting the tgz in mavencentral would fix that for us.

Deb and rpm are much less useful as in many corporate environments application developers can't easily get access to install via those mechanisms so being able to bundle the tgz as part of our app installation makes it much more self contained.

You're right, we could manually download the tgz and manually upload it to our maven repo but I've done that for the last couple of versions but life is short and I expect this wastes my time and that of many other developers wanting to use logstash in similar situations.

**Comment by jmowen** [comment]
well, here i am about to start working with logstash so I created a working directory and started to initialize my dependencies only to find that not only is it not in mavencentral but the developers are obtuse on the subject. Is it really so different to work with logstash that you have to spin up a vm to develop configuration scripts for it? ok. So I found multiple "ELK with Vagrant" items and that's an easy enough starting point I guess. But it seems wrong - like too much overhead.
