### ISSUE TITLE
'rake' has lots of noisy warnings

### ISSUE THREAD

**Issue by jordansissel** [elasticsearch/logstash#1994]
We should avoid emitting the following, which are currently observed in master when doing `rake artifact:tar`

* [ ] Gems in the group development were not installed.
* [ ] WARN: Unresolved specs during Gem::Specification.reset:
* [ ] WARN: Clearing out unresolved specs.
* [ ] Please report a bug if this causes problems.

**Comment by ph** [comment]
Since we are still doing a lot of changes here, I propose we close this and reopen specific issues after the windows sprint.
