### ISSUE TITLE
Lumberjack + multiline codec is not  worker thread safe and does not actually support multiline

### ISSUE THREAD

**Issue by blipper** [elasticsearch/logstash#2016]
Basic issues
1)  Lumberjback + Multiline codec don't play well together.
2)  Lumberjack doesn't support stream_identity
3)  Even if it did multiline codec isn't safe with worker threads if you implement number 2 above

Ugly Workaround below fixes #1-#3

- Derives stream_identity from host:port
- Mutexes the buffer hash
- Breaks other codecs that you might be using

https://github.com/blipper/logstash/commit/9b54c21cfddeb3d02de71436e96f7d7c0f08fb5a

Not sure what the real fix is this works for us

**Comment by suyograo** [comment]
Fix in https://github.com/logstash-plugins/logstash-input-lumberjack/pull/5
