### ISSUE TITLE
[logstash-docs] Add a disclaimer at the top of community-maintained plugins

### ISSUE THREAD

**Issue by tbragin** [elasticsearch/logstash#2096]
Right now on logstash.net, for plugins that are provided in the 'contrib' package there is a note at the top saying:
*This is a community-contributed plugin! It does not ship with logstash by default, but it is easy to install! To use this, you must have installed the contrib plugins package.*

As we migrate the docs to .org, we should maintain this type of notice on plugins that are not shipped by default with Logstash. Otherwise, users may think something is wrong when they don’t see them available in the download. Proposed wording for .org documentation:
*This is a community-maintained plugin! It does not ship with Logstash by default, but it is easy to install by running `bin/plugin install [plugin name]`.*

**Comment by jordansissel** [comment]
+1

@kurt - thoughts on implementing this?

**Comment by kurtado** [comment]
@jordansissel @suyograo do we have a list of said plugins?

Three-line perl script, and... done :)

**Comment by suyograo** [comment]
@kurtado the default plugins we ship with LS is here: https://github.com/elasticsearch/logstash/blob/master/rakelib/default_plugins.rb

Anything not on this list should have the warning above. See what we did in 1.4.2 http://logstash.net/docs/1.4.2/filters/sumnumbers

**Comment by kurtado** [comment]
Codecs completed:
http://www.elasticsearch.org/guide/en/logstash/current/codec-plugins.html
via:
https://github.com/elasticsearch/logstash-docs/pull/50/files

**Comment by kurtado** [comment]
Filters completed:
http://www.elasticsearch.org/guide/en/logstash/current/filter-plugins.html
e.g.
http://www.elasticsearch.org/guide/en/logstash/current/plugins-filters-cidr.html

**Comment by kurtado** [comment]
Inputs completed:
http://www.elasticsearch.org/guide/en/logstash/current/input-plugins.html
e.g.
http://www.elasticsearch.org/guide/en/logstash/current/plugins-inputs-drupal_dblog.html

**Comment by kurtado** [comment]
Outputs completed:
http://www.elasticsearch.org/guide/en/logstash/current/output-plugins.html
e.g.
http://www.elasticsearch.org/guide/en/logstash/current/plugins-outputs-circonus.html

**Comment by kurtado** [comment]
There are a few missing plugins which need to be added to the index.asciidoc page (possibly by @electrical?) or via his process? They've been added to the logstash-plugins repo since the last index regeneration:

CODEC:
avro

FILTERS:
oui
tld
