### ISSUE TITLE
Coveralls not working

### ISSUE THREAD

**Issue by PragTob** [elasticsearch/logstash#2113]
I see that logstash has a development dependency on coveralls and also seems to have it set up alright in the [spec_helper](https://github.com/elasticsearch/logstash/blob/master/spec/spec_helper.rb#L5-L17) but it doesn't seem to report coverage to the [coveralls web](https://coveralls.io/r/elasticsearch/logstash)

My guess would be that the CI server misses the COVERAGE environment variable or somehow the results aren't getting sent over there.

I'd suggest removing coveralls or getting it reporting :). Maybe the results are also private and I just see them, in that case carry on but I love to have those public for oss projects.

I've had my fair share of troubles with coveralls so using another service might also be an option.

Cheers,
Tobi

**Comment by purbon** [comment]
Fixed #2412
