### ISSUE TITLE
Allow splitting of lists / arrays into multiple events

### ISSUE THREAD

**Issue by agirbal** [elasticsearch/logstash#2131]
A very common pattern in JSON & XML is to make use of lists to group data together.
For example an XML file often looks like:
```
<root>
    <some common data about this file ... />
    <events>
        <event ... />
        <event ... />
        <event ... />
        ...
    </events>
<root/>
```

Same way in JSON, many SQL exports or API results look like this:
```
{ some-common-fields: ...,
  results: [
    { result ... },
    { result ... },
    { result ... },
    ...
] }
```

Right now logstash can't easily handle those "groupings" and require some external XSLT or script of some sort.
Instead it would be great to extend the "split" command so that it can be applied to an array, after the initial data has been parsed.
The behavior would be: make each element of the array its own event, copying all other fields over.
A flag could be used to disable copying the common fields.
This would be generic and applicable to any input format.

For example based on above JSON:
```
$ logstash -e 'input {} filter { split { json { source => "message" } split { arrayField => "results" } } } output {}'
```

Common use cases:
- many SQL dumps into XML / JSON
- internet of things: many readings from the network come in grouped per device & time

**Comment by markwalkom** [comment]
There is some API data that I am trying to use that would benefit greatly from this!

**Comment by markwalkom** [comment]
Thanks to @jordansissel, here is a work around. Just change the values in the event field to match your array.

```
filter {
  ruby {
    init => "def filter(event, &block); event['[result][records]'].each { |o| yield LogStash::Event.new(o) }; event.cancel; end"
    code => "hahaha"
  }
}
```

**Comment by suyograo** [comment]
there is a PR for this https://github.com/elasticsearch/logstash/pull/787 .. we can extend on it

**Comment by suyograo** [comment]
Fixed via https://github.com/logstash-plugins/logstash-filter-split/pull/1

**Comment by agirbal** [comment]
sweet! thanks guys

**Comment by algesten** [comment]
in which logstash version is this available?

**Comment by talevy** [comment]
@algesten Logstash 1.5. currently in RC2

**Comment by algesten** [comment]
thanks!

**Comment by mtarantino** [comment]
@suyograo, @talevy  : 
 - is there an example for the filter syntax when it comes to json split ?
 - another question regarding filter scheduling ? what is the order in which the filter will be applied ? For example, there is a mutate filter which add_fileds will the fields be added to the parent event or the split event ?

**Comment by KrishnaPG** [comment]
Came across this thread when looking for info on splitting xml events. One of the posts above indicates that such facility is added into the logstash.

Where can I find more information on it?  For example, for the below kind of xml, what is the config to be used to generate separate events correctly?
````
<root>
    <some common data about this file ... />
    <events>
        <event ... />
        <event ... />
        <event ... />
        ...
    </events>
<root/>
````
I am trying xml filter and xpath etc. but having hard time trying to get things work. Any help / documentation is highly appreciated.

**Comment by markwalkom** [comment]
@KrishnaPG check out the docs, and if you need more help then please create a thread on https://discuss.elastic.com
