### ISSUE TITLE
Slim down the release artifacts

### ISSUE THREAD

**Issue by jordansissel** [elasticsearch/logstash#2137]
Unpacked tar of master branch (at time of writing) is pretty large. This causes the package to be large (100mb). Unpacked size is 169mb.

Comparatively, v1.4.2 is ~80mb.

* [ ] Duplicate files (same checksum) in package. Deduplication will shave 24mb. [1]
* [x] See if we can ship a release without dependency tests. Specifically, spec and test directories in our dependency gems. This accounts for about 10mb of data. [2]
* [ ] Clean up large files. There are more than 200 files over 50kb. This accounts for 120mb of data. [3]
* [x] Strip Ruby 1.8 and 2.0 support from JRuby (we only use Ruby 1.9 syntax) for now. [4]
* [x] Strip code we don't use, like rdoc (1.9mb) [5]

It's also likely we can do platform-specific cleanup:
* [ ] On RPM- and deb-based systems, we can probably assume it's Linux, and as a result don't need to ship any windows or solaris artifacts (ffi dll/so files, etc)

Let's find lots of things to clean up
---

[1] Deduplication
```
% find ./ -type f -print0 | xargs -0 du -bs  | sed -e 's,\./.*/,,' |sort -n | sum 1 |bytes
156.75M
% find ./ -type f -print0 | xargs -0 du -bs  | sed -e 's,\./.*/,,' |sort -n | uniq | sum 1 |bytes
132.67M
```

[2] Removing spec+tests from gems

```
% du -bs vendor/{bundle,plugins}/jruby/1.9/gems/*/{test,spec} |sum 1 | bytes
9.58M
```

[3] Lots of files larger than 50kb. Do we need them all?

```
% find ./ -type f -print0 | xargs -0 du -bs --apparent-size  | awk '$1 > 50*1024' | wc -l
237
% find ./ -type f -print0 | xargs -0 du -bs --apparent-size  | awk '$1 > 50*1024' | sum 1 | bytes
119.86M
```

Example candidates include Kibana which includes bootstrap `less` files which are unlikely to be needed in production. The `twitter` gem's CHANGELOG.md is 76kb. `simplecov-html` includes 250kb of javascript that isn't used by logstash.

[4] Stripping Ruby 1.8 and 2.0 support in the JRuby packaging

```
% du -hs vendor/jruby/lib/ruby/*
4.8M    vendor/jruby/lib/ruby/1.8
5.6M    vendor/jruby/lib/ruby/1.9
5.0M    vendor/jruby/lib/ruby/2.0
```

[5] Strip unused code, like rdoc.
```
% du -hs vendor/jruby/lib/ruby/1.9/rdoc
1.8M    vendor/jruby/lib/ruby/1.9/rdoc
```

Estimate 10mb of saving if we strip 1.8 and 2.0 support. Needs testing.

**Comment by jsvd** [comment]
Space saved by removing duplicate jars: 23mb

```
 % find . -name '*.jar' -type f -exec du -k {} + | awk '{total += $1} END {print total}'
86020
% find . -name '*.jar' -type f -exec du -k {} +  | sort -un | awk '{total += $1} END {print total}'
62420
% expr 86020 - 62420
23600
```

**Comment by jsvd** [comment]
All low hanging fruits have been picked by #2285

Closing this issue, dealing with jar duplication requires big changes and should be handled in a separate issue.
