### ISSUE TITLE
tcp output not adding LF (0x0a) at the end of line

### ISSUE THREAD

**Issue by cova-fe** [elasticsearch/logstash#2173]
I'm tring to use tcp output (logstash 1.4.2) but, even if the documentation says "Each event json is separated by a newline.", it seems that LF is not added.

Looking at the code, it seems that the "\n" part is commented out. Am I doing something wrong?

**Comment by talevy** [comment]
@cova-fe 

The commented code seems to be referring to a depreciated method of handling the messages.

Now, the format of the output is controlled by a logstash codec. The default codec for the tcp output plugin is `json`. If you are interested in emitting a json string payload along with a new line please check to see if the `json_lines` codec does what you want

here are the docs: http://logstash.net/docs/1.4.2/codecs/json_lines

let me know if that does what you had in mind.

Thanks!
