### ISSUE TITLE
Conditionnal on field always true with multiline filter and enable_flush true

### ISSUE THREAD

**Issue by Benoit-DunandLaisin** [elasticsearch/logstash#2185]
Hi,

With logstash-1.4.2-1_2c0f5a1.

Here is my test case:

Content of input file:

    2014/12/05 10:33:06.781 Hi
    2014/12/05 10:33:06.781 hi again

Note that there is no crlf at the end of the last line.   

Logstash config:

    input {
      file {
        path => "/tmp/input.log"
        start_position => "beginning"
      }
    }
    filter {
      multiline {
        pattern => "^(\d{2})?%{DATESTAMP} "
        negate => true
        what => previous
        enable_flush => true
      }
      grok {
        match => ["message", "%{DATESTAMP:logtime} %{GREEDYDATA:log}"]
      }
      date {
        match => ["logtime", "YY/MM/dd HH:mm:ss.SSS"]
        target => "logtime"
        locale => "en"
      }
      if [log] == ""{
        mutate {
          add_tag => ["log empty"]
        }
      }
      if [log] != "" {
        mutate {
          add_tag => ["log filled"]
        }
      }
      if [log] == "anything" {
        mutate {
          add_tag => ["wow always true?"]
        }
      }
      mutate {
        remove_field => ["message", "host", "path"]
      }
    }
    output {
      stdout { codec => json }
    }

Output:

    {"@version":"1","@timestamp":"2014-12-05T13:50:44.148Z","logtime":"2014-12-05T09:33:06.781Z","log":"Hi","tags":["log filled"]}
    {"@version":"1","@timestamp":"2014-12-05T13:50:44.149Z","logtime":"2014-12-05T09:33:06.781Z","log":"hi again","tags":["log empty","log filled","wow always true?"]}

The output for the first line is correct.
However, for the second line (that is triggered by the flush of multiline filter), every conditionnal test about "log" field is true. So that the result is incorrect.

Bug happened each time lines are added to log file "slowly".
I don't see any workaround

**Comment by suyograo** [comment]
Fixed via https://github.com/elasticsearch/logstash/pull/1545. Please let us know if this is not the case
