### ISSUE TITLE
Warning about overriding patterns when using hash syntax in grok filter

### ISSUE THREAD

**Issue by wiibaa** [elasticsearch/logstash#2197]
As grok filter match can now use a hash syntax, I switched from

    filter {
      grok {
        match => [
          "message", "pattern1"
          ,"message", "pattern2"
          ,"message", "pattern3"
        ]
      }
    }

to a no-comma paradise

    filter {
      grok {
        match => {
          "message"=> "pattern1"
          "message"=> "pattern2"
          "message"=> "pattern3"
        }
      }
    }

However this is internally interpreted as a **HASH** so it only keeps the last pattern in the final config
Either it is a bug or a friendly warning in grok is required for dummies

**Comment by colinsurprenant** [comment]
<3 clean yaks
