### ISSUE TITLE
-syslog not logging to syslog

### ISSUE THREAD

**Issue by dlangille** [elasticsearch/logstash#2198]
From https://groups.google.com/forum/#!topic/logstash-users/A_FBYj9C-6U

I am using logstash-forwarder-0.3.1.20140829 on FreeBSD 9.3-RELEASE-p5 

I'd like logstash-forwarder to log, to either syslog or a file.

I've tried various options with -debug, -syslog, and --log-to-syslog

Based on output such as this, I've concluded that -syslog and --log-to-syslog are identical:

$ sudo /usr/local/bin/logstash-forwarder -config=/usr/local/etc/logstash-forwarder.conf -log-to-syslog=true -debug=true 
2014/12/08 02:20:51.029255 	--- options -------
2014/12/08 02:20:51.029276 	config-file:         /usr/local/etc/logstash-forwarder.conf
2014/12/08 02:20:51.029281 	idle-timeout:        5s
2014/12/08 02:20:51.029284 	spool-size:          1024
2014/12/08 02:20:51.029287 	harvester-buff-size: 16384
2014/12/08 02:20:51.029289 	--- flags ---------
2014/12/08 02:20:51.029291 	tail (on-rotation):  false
2014/12/08 02:20:51.029293 	use-syslog:          true
2014/12/08 02:20:51.029296 	verbose:             false
2014/12/08 02:20:51.029298 	debug:               true

Nothing is appearing anywhere in /var/log/*

Is this expected?

FWIW, In random desperation, I've tried adding this to /etc/syslog.conf to get something:

*.*	/var/log/logstash-forwarder.log

Still, nothing.

**Comment by dcremonini** [comment]
It looks like you are referring to the wrong project: don't confure logstash with logstash-indexer. The latter is something different and its parameters are not the same as the ones of the former.
Example
logstash accepts --config (with two dashes)
logstash-indexert accepts -config (with one dash)

**Comment by dlangille** [comment]
I'm not sure why you refer to logstash-indexert.  I have never used it. but I see your point regarding -config versus --config.  I will retest as soon as I can.

**Comment by suyograo** [comment]
Hi @dlangille could you please open logstash-forwarder specific issues here https://github.com/elasticsearch/logstash-forwarder

**Comment by dlangille** [comment]
Done. Thank you.  https://github.com/elasticsearch/logstash-forwarder/issues/355
