### ISSUE TITLE
RabbitMQ queues get deleted no matter what on shutdown

### ISSUE THREAD

**Issue by teu** [elasticsearch/logstash#2212]
Hi,

as much as we love logstash+elasticsearch, shipping with logstash-forwarder->logstash has proven to be quite unreliable (logstash getting overwhelmed quickly and some race condition bounding connections = logs lost), today we tested moving messages though beaver->rabbitmq->logstash. 

The latter approach in theory should let us to process any number of logs (horizontally scaling on AWS) and remove SPoF's. Idea is to have beavers ship to RabbitMQ cluster, another dynamic logstash cluster would consume the messages and ship to yet another elasticsearch cluster. When any one thing gets to small we can always adjust it by simply adding machines.

The problem we found is that the logs from the rabbitmq input vanish into thin air. 

Error message that we get when we kill logstash (perhaps not relevant) 
```
NoMethodError: undefined method `cancel' for nil:NilClass
  shutdown_consumer at /home/ubuntu/logstash-1.4.2/lib/logstash/inputs/rabbitmq/march_hare.rb:126
           teardown at /home/ubuntu/logstash-1.4.2/lib/logstash/inputs/rabbitmq/march_hare.rb:68
           shutdown at /home/ubuntu/logstash-1.4.2/lib/logstash/pipeline.rb:247
               each at org/jruby/RubyArray.java:1613
           shutdown at /home/ubuntu/logstash-1.4.2/lib/logstash/pipeline.rb:246
               each at org/jruby/RubyArray.java:1613
           shutdown at /home/ubuntu/logstash-1.4.2/lib/logstash/pipeline.rb:234
            execute at /home/ubuntu/logstash-1.4.2/lib/logstash/agent.rb:120
               call at org/jruby/RubyProc.java:271
               each at org/jruby/RubyArray.java:1613
    simulate_signal at /home/ubuntu/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/trap.rb:46
               trap at /home/ubuntu/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/trap.rb:26
               call at org/jruby/RubyProc.java:271

```

Configuration is following:
```
rabbitmq {
	host => [moderated]
	ack => true
	auto_delete => false
	codec => "json"
	type => "http-access-log"
	key => "logstash"
	passive => true
	prefetch_count => 10
	queue => "beaver-access-logs"
	user => [moderated]
	password => [moderated]
}

```

Another problem is, that the messages have been set to ACK but seam to be vanishing into thin air (not a word in the logs) but getting ACKed before being shipped of anywhere. The same logstash agent is working with several lumberjack inputs that are moving logs to elasticsearch just fine and the format is the same as I am testing on a machine that normally has logstash-forwarder running on it. On a side note logstash is restarting a lot without any log entry or apparent cause.

 Please advise.

**Comment by suyograo** [comment]
@teu Closing this, please reopen if this is not fixed yet
