### ISSUE TITLE
create getting-started template/example input/filter/output plugins

### ISSUE THREAD

**Issue by colinsurprenant** [elasticsearch/logstash#2230]
we should provide example input/filter/output plugins developers can start with to bootstrap their dev environment.

**Comment by untergeek** [comment]
I've got these for a start.  Will submit codec and input examples soon.

https://github.com/logstash-plugins/logstash-output-example/pull/1
https://github.com/logstash-plugins/logstash-filter-example/pull/1

**Comment by untergeek** [comment]
Added the codec:

https://github.com/logstash-plugins/logstash-codec-example/pull/1

**Comment by untergeek** [comment]
Added the input:

https://github.com/logstash-plugins/logstash-input-example/pull/1

**Comment by suyograo** [comment]
Example repos were added
