### ISSUE TITLE
email output plugin keeps only last options

### ISSUE THREAD

**Issue by Goulart** [elasticsearch/logstash#2250]
I have this config for logstash output section:
```ruby
if [severity_code] {
     if [severity_code] < 5 {
       email {
         subject => "Alert: %{severity} Origem: %{hostname}"
         body => "Timestamp: %{@timestamp}\nHost: %{host}\nHostname: %{hostname}\nMessagebody: %{messagebody}\nBrowse2: http://vip-kibana.bportugal.pt/kibana/index.html#/dashboard/script/logstash.js?query=host:%22%{host}%22,severity=%22%{severity}%22"
         from => "from@addr.lz"
         to => "group@addr.lz"
         replyto =>  "me@addr.lz"
         options => [ "smtpIporHost", "smtpServer.addr.lz", "port", "25" ]
       }
     }
     if [severity_code] < 3 {
       email {
         subject => "s"
         body => "%{severity}\n%{hostname}\n%{messagebody}"
         from => "from@addr.lz"
         replyto =>  "from@addr.lz"
         to => "920000000@sms.smsgateway.addr.lz"
         options => [ "smtpIporHost", "smsgateway.addr.lz", "port", "25" ]
       }
     }
}
```
As it happens, logstash tries to send all messages to *smsgateway.addr.lz*
It looks as if only the last config override of the plugin is kept.
How can I use a different mail server for different conditions?
Thank you.

**Comment by ph** [comment]
This is a bug, when we start logstash we are registering a new plugin instance for each block of configuration. Plugins are usually self contains and don't try to change global settings, this is not the case with the email plugin.

The plugin overrides the global defaults for sending email, this is why your configuration is trying to use the `smsgateway.addr.lz` which is the last declared smtp. see https://github.com/logstash-plugins/logstash-output-email/blob/master/lib/logstash/outputs/email.rb#L114-

We should make sure each instance of the email plugin use his own configuration, the behavior is already supported in the library we are using https://github.com/mikel/mail#sending-an-email.

I don't have a solution without changing the code of the plugin. We are in the process of extracting all the plugins from the core, would you mind recreating this issue in the email plugin repository at https://github.com/logstash-plugins/logstash-output-email ?

**Comment by Goulart** [comment]
Thank you!
I will recreate the issue in github soon.

Thanks again.
A.Goulart

2015-01-06 17:26 GMT+00:00 Pier-Hugues Pellerin <notifications@github.com>:

> This is a bug, when we start logstash we are registering a new plugin
> instance for each block of configuration. Plugins are usually self contains
> and don't try to change global settings, this is not the case with the
> email plugin.
>
> The plugin overrides the global defaults for sending email, this is why
> your configuration is trying to use the smsgateway.addr.lz which is the
> last declared smtp. see
> https://github.com/logstash-plugins/logstash-output-email/blob/master/lib/logstash/outputs/email.rb#L114-
>
> We should make sure each instance of the email plugin use his own
> configuration, the behavior is already supported in the library we are
> using https://github.com/mikel/mail#sending-an-email.
>
> I don't have a solution without changing the code of the plugin. We are in
> the process of extracting all the plugins from the core, would you mind
> recreating this issue in the email plugin repository at
> https://github.com/logstash-plugins/logstash-output-email ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/elasticsearch/logstash/issues/2250#issuecomment-68898408>
> .
>



-- 
Artur Goulart

**Comment by ph** [comment]
closing this ticket, the ticket moved to the plugin repository.
https://github.com/logstash-plugins/logstash-output-email/issues/5
