### ISSUE TITLE
after logstash upgrade to 1.5 - uninitialized constant Grok::Pile

### ISSUE THREAD

**Issue by eyalc10** [elasticsearch/logstash#2298]
Hi, 

I receive the following error after upgrading to logstash 1.5. 
if grok clause is removed from the configuration - it works fine . 
( I use grok for the pattern specific files ), all worked well in the previous release : 1.4.2 

-----
Using milestone 2 input plugin 'file'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones {:level=>:warn}

The error reported is:
  uninitialized constant Grok::Pile
-----

**Comment by suyograo** [comment]
@eyalc10 did the java version fix your issue? Seems like you also got beyond the grok error?

**Comment by eyalc10** [comment]
Yes,  although I didnt have the chance to run a clean pkg

Regards, 
Eyal Cohen

**Comment by jordansissel** [comment]
> Hmm okay. my guess is that with the major changes we did it might have left some files behind messing around.

Deb packages don't leave files behind when they are uninstalled. It only leaves files labeled 'config files' that have been modified. Nothing that should cause the bug reported here. Confusing :(

**Comment by eyalc10** [comment]
First of all thank you for everything, 
I belive that it might have been a mix of old and new files becasue when I have untared the full directory and copied only the required configuration,  all worked great.

**Comment by jordansissel** [comment]
@eyalc10 glad things are working now! :)

**Comment by arnaudmm** [comment]
Hi, dunno if I have to open a new issue but I got the same problem with a fresh logstash 1.5RC1 install

 missing class or uppercase package name (`org.elasticsearch.common.settings.ImmutableSettings'), caused by (NameError) cannot load Java class org.elasticsearch.common.settings.ImmutableSettings

**Comment by purbon** [comment]
@arnaudmm I guess your error is related to https://github.com/elasticsearch/logstash/issues/2780

**Comment by arnaudmm** [comment]
exactly, thanks a lot

**Comment by purbon** [comment]
working on getting rid of this issue ASAP, but there is a workaround there. hope it helps.

**Comment by arnaudmm** [comment]
just tested the workaround, it works like a charm. Thanks again @purbon
