### ISSUE TITLE
new year bug for the output elasticsearch_http index name

### ISSUE THREAD

**Issue by abualy** [elasticsearch/logstash#2306]
Hello!
With the new year,  i got my new log events for the 01/01/2015, indexed with the index name: 2014.01.01, 
![logstash_bug_new_year](https://cloud.githubusercontent.com/assets/2552664/5592207/2dee2544-91b7-11e4-8e15-c7b8d3160833.jpg)

i had to restart Logstash to index the new logs with the index name 2015.01.01

here is my logstash output conf:
```
output {
        if [type] == "apache_error_logs" {
                elasticsearch_http {
                        index => "%{+YYYY.MM.dd}-apache_error_logs"
                        host => "localhost"
                        port => 9200
                }
        }
}
```

**Comment by jpyth** [comment]
Same issue, same style config. Using YYYY-MM-DD syntax.

Had to restart the initial indexer.

**Comment by untergeek** [comment]
I do not have this problem.
```
$ curator show --show-indices
...
logstash-2014.12.29
logstash-2014.12.30
logstash-2014.12.31
logstash-2015.01.01
```
- How are your logs being sent *to* Logstash (as you've only included your output block)?
- How is the `@timestamp` extracted (since you've omitted the grok and/or date filter blocks)?

**Comment by wiibaa** [comment]
Can you confirm that you are using date filter with a format not containing the year (or syslog input)
Similar issues (from last year)
* https://logstash.jira.com/browse/LOGSTASH-1574
* https://logstash.jira.com/browse/LOGSTASH-1744

**Comment by abualy** [comment]
@wiibaa : yes, i'm using a date filter not containing the year
```
                date {
                         match => [ "syslog_timestamp" , "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
                }
```
btw i'm using Logstash_1.4.2-1-2

@untergeek : 
  - for the logs i'm using the udp input (no custom config, standard one), rsyslog as a sender

**Comment by Bloodevil** [comment]
I have same issue. I used two type of filter like below, so I had a two type of elasticsearch index like "logstash-2014.01.01" and "logstash-2015.01.01". 

UDP input
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }

file input
  date {
    match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
  }

**Comment by CullyB** [comment]
Confirm this happened with me as well; I also had a partial index for 2015.01.01, but I assume that was due to logstash rolling to a new index at midnight UTC; my logs stopped parsing after localtime rolled over to the new year.  Like others - a restart fixed it, now just need to go back and uncompress the old logs and feed them in.

**Comment by cheechun2005** [comment]
Logstash 1.4.2-1-2c0f5a1 + elastichsearch 1.4.2 user affected here as well. Current logstash configuration is here -> https://gist.githubusercontent.com/anonymous/652bf2142ca989854fe1/raw/a1dd31e0fcd4b47cf689bf12f2244f2e0bd577ff/gistfile1.txt

In my case, logstash not only creates index logstash-2014.01.0, but also logstash-2013.12.31 :

2:[2015-01-01 00:00:01,670][DEBUG][indices                  ] [Mothership] creating Index [logstash-2013.12.31], shards [5]/[1]
24:[2015-01-01 00:00:01,706][DEBUG][indices                  ] [Mothership] creating Index [logstash-2013.12.31], shards [5]/[1]
245:[2015-01-01 01:17:01,728][DEBUG][indices                  ] [Mothership] creating Index [logstash-2014.01.01], shards [5]/[1]
267:[2015-01-01 01:17:01,763][DEBUG][indices                  ] [Mothership] creating Index [logstash-2014.01.01], shards [5]/[1]

**Comment by darkwarriors** [comment]
same bug with date logstash filter that parse syslog timestamp, Logstash create 2014.01.01 insted of 2015.01.01, by restarting the process we solve the problem.

seems that LS takes the year at start-up process time with if you have the date filter on and it didnt take the current system date.

regards.

**Comment by jpyth** [comment]
Hi,

Can confirm we were using syslog input on the impacted logs. Our setup is syslogs into an indexer, no filtering, into an MQ then additional indexers down stream.

I had to restart the initial indexer that is taking just syslog input to resolve the issue. -- Full disclosure; I had already restarted the down stream indexers but the issue was not resolved. In hindsight; I think only the initial(syslog input) indexer needed the restart. )

I haven't dug into it, but there were *some* logs in the 2015.01.01 index before I restarted - at a glance it was logs from SNMP traps, and some lines LS generaters from the generator input.

**Comment by arohter** [comment]
Same issue here.
Syslog input timestamp match  => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
Restart of logstash fixes the year.   Appears to be https://github.com/logstash-plugins/logstash-filter-date/issues/3

**Comment by checkmypi** [comment]
+1 
Same issue

**Comment by jordansissel** [comment]
Let's continue the discussion here: https://github.com/logstash-plugins/logstash-filter-date/issues/3

I have proposed a fix, but I want to make sure we get all the use cases covered and tests written so we can make sure this is a solid fix :)

**Comment by jordansissel** [comment]
(Closing in favor of discussing here: https://github.com/logstash-plugins/logstash-filter-date/issues/3)
