### ISSUE TITLE
TIMESTAMP_ISO8601 fails since 2015

### ISSUE THREAD

**Issue by flaurencin** [elasticsearch/logstash#2308]
Hi there,

Here is the kind of log I have :
"2015-01-02T10:31:10+01:00 192.168.1.1 notice Jan  2 10:31:10.721 CET: %DOT1X-5-FAIL: Authentication failed for client (aaaa.aaaa.aaaa) on Interface Gi1/0/X AuditSessionID XXXXXXXXXXXXXXXXXX"

When I try 
        grok {
            match => { "message" => "%{TIMESTAMP_ISO8601:syslog_host_time} %{GREEDYDATA:message}"}
            add_tag => [ "cisco_ios" ]
            match => { "path" => "%{YEAR:log_year}" }
            }

ruby debug sends me 
{
         "message" => "2015-01-02T10:31:10+01:00 192.168.1.1 notice Jan  2 10:31:10.721 CET: %DOT1X-5-FAIL: Authentication failed for client (aaaa.aaaa.aaaa) on Interface Gi1/0/X AuditSessionID XXXXXXXXXXXXXXXXXX",
        "@version" => "1",
      "@timestamp" => "2015-01-02T09:31:10.749Z",
            "host" => "localhost"
}

no syslog_host_time :-(

But it works here http://grokconstructor.appspot.com/do/match#result

Best regards

Frederic

**Comment by wiibaa** [comment]
Indeed I see nothing wrong in your pattern but are you sure this filter was executed at all, your event should either have the cisco_ios or _grokparsefailure tags

**Comment by flaurencin** [comment]
You're absolutely right. My problem is due to the fact that i did not reach the filter at all.

Sorry for the noise.

Best regards.

/Fred

**Comment by wiibaa** [comment]
@flaurencin no problem, just can you please close the issue. Happy new year!
