### ISSUE TITLE
syslog agent is not excuting

### ISSUE THREAD

**Issue by upbalshetwar** [elasticsearch/logstash#2309]
Hi,

when I am trying to excute syslog agent through runner.class
it throws exception 
Exception is:
throws exception on running logstash (LoadError) load error: shared/jruby-openssl -- java.lang.ExceptionInInitializerError: null

Used jar file:logstash-1.3.2-flatjar.jar

**Comment by electrical** [comment]
Hi,

its best to upgrade Logstash since 1.3.2 is pretty old
current GA version is 1.4.2

**Comment by wiibaa** [comment]
@upbalshetwar can you please explain why you want to stick with java execution instead of bin/logstash agent ? are you wrapping the runner.class in your java app ?

Aside can you please comment on this issue only and closes #2311 #2310

**Comment by suyograo** [comment]
@upbalshetwar closing this as it is not supported. Let us know why you need the jar behavior
