### ISSUE TITLE
Regarding jar file creation

### ISSUE THREAD

**Issue by upbalshetwar** [elasticsearch/logstash#2310]
Hi,

Can I create latest jar file for logstash using latest GITHUB.
if yes then what is process or steps to generate jar file

so can I execute tarball in java
I think no as per my understanding
so can I create jar file for latest code because same I am trying to use in my java application

**Comment by electrical** [comment]
Hi,

We have dropped the jar file creation for logstash 1.5 and later.
you can now create a tarball with `rake artifact:tar`
