### ISSUE TITLE
Regarding jar file creation

### ISSUE THREAD

**Issue by upbalshetwar** [elasticsearch/logstash#2311]
can I execute tarball in java
I think  as per my understanding answer is "No"
so can I create jar file for latest code GITHUB
 so same I can try to use in my java application

**Comment by untergeek** [comment]
That is unsupported.  What do you need Logstash code in your java application for?  Might you be better served using the https://github.com/logstash/log4j-jsonevent-layout project or one of the others like it?


—Aaron

**Comment by suyograo** [comment]
Dup of #2310
