### ISSUE TITLE
Wrong in metrics docs?

### ISSUE THREAD

**Issue by roflmao** [elasticsearch/logstash#2313]
Trying to do the example from: http://logstash.net/docs/1.4.2/filters/metrics

This codeblock:
```
output {
  # only emit events with the 'metric' tag
  if "metric" in [tags] {
    stdout {
      message => "rate: %{events.rate_1m}"
    }
  }
}
```
Gives me:

```
{:timestamp=>"2015-01-05T14:37:22.015000+0100", :message=>"Unknown setting 'message' for stdout", :level=>:error}
```
Running logstash 1.4.2-1-2c0f5a1

**Comment by ph** [comment]
The documentation is misleading, the stdout plugin only support the codec option.
You could use the rubydebug codec to see the metrics data.
```
output {
  # only emit events with the 'metric' tag
  if "metric" in [tags] {
    stdout {
      codec => rubydebug {}
    }
  }
}
```

**Comment by ph** [comment]
This bug is already fixed in the new release of the plugin.
You can use the line codec to achieve the same result than with the 'message' option.

```
output {
  # only emit events with the 'metric' tag
  if "metric" in [tags] {
     stdout {
        codec => line {
             format => "rate: %{events.rate_1m}"
        }
    }
  }
}
```

**Comment by roflmao** [comment]
Shouldnt these messages go to the logfile when run as a daemon? Dont get any lines in /var/log/logstash/logstash.log

**Comment by ph** [comment]
I don't think we save the stdout to the `/var/log/logstash.log`, the `stdout` output is mostly for testing when you run logstash interactively from the command line. If you start it from the command line you can also use the `--verbose` or the `--debug` flag to get more info.

**Comment by roflmao** [comment]
Seems the stdout is sent to /var/log/logstash/logstash.stdout

Thanks!
