### ISSUE TITLE
indexing Json objects in Elasticsearch with java 

### ISSUE THREAD

**Issue by momok2** [elasticsearch/logstash#2316]
Hi,
i wan to index Json objects from Jolokia in Elasticsearch 
can i do this in java ?

Thanks

**Comment by wiibaa** [comment]
@momok2 is this not the exact same question than #2302 please avoid duplicates.

I had a quick look to Jolokia, it seems to only expose an http endpoint and Logstash does not have a generic http input yet.
But indeed you could try to write your own solution talking to elasticsearch in java either using a generic REST client (jersey?) or the dedicated API, the 2 following links could help you getting started.

* http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_talking_to_elasticsearch.html
* http://www.elasticsearch.org/guide/en/elasticsearch/client/java-api/current/index_.html

**Comment by wiibaa** [comment]
@momok2 the point is that I do not catch the difference between the 2 tickets because in both you refer to Jolokia content.

Indeed Logstash has a JSON codec but **no http input**. Again, could you please shortly describe what kind of polling you would like to do on your Jolokia endpoint, maybe a solution could be found using existing logstash plugins, for example maybe a config similar to this would suit your needs

````
input {
  exec {
    command => "curl http://your.jolokia.server/your-request"
    interval => 60
    codec => json
  }
}
````

**Comment by momok2** [comment]
Hi @wiibaa thanks for your interest 
i want to extract Solr-metrics with jolokia and when i send request like "http://myhost/jolokia/read/solr!/MySolrInstance:type=searcher,id=org.apache.solr.search.SolrIndexSearcher/"
i get a Json response where i have the metric what i need.
i want to index all responses in elasticsearch and visualise it in Kibana.
i hope you have an Idea to help me

**Comment by wiibaa** [comment]
is this url static? If you simply need to call the same URL every x seconds, then the logstash exec input is a good candidate to try.

**Comment by momok2** [comment]
i want to extract more metrics and for each metric is an URL needed 
can i use the exec input for more urls ?

**Comment by wiibaa** [comment]
if you are sure that each response is only one line, maybe you could group all your curl in a shell script and use [json_lines codec](http://logstash.net/docs/1.4.2/codecs/json_lines) I suppose ?

**Comment by momok2** [comment]
a response look like this :
{"request":{"mbean":"solr\/MySolrInstance:id=org.apache.solr.search.SolrIndexSearcher,type=searcher","type":"read"},"value":{"coreHashCode":"2065434214","reader":"StandardDirectoryReader(segments_3:5:nrt _0(4.10.2):C2 _1(4.10.2):C4)","deletedDocs":0,"registeredAt":"2015-01-06T13:42:31+01:00","description":"index searcher","indexVersion":5,"source":null,"version":"1.0","caching":true,"openedAt":"2015-01-06T13:42:30+01:00","numDocs":6,"searcherName":"Searcher@3d8f45[MySolrInstance] main","name":"org.apache.solr.search.SolrIndexSearcher","maxDoc":6,"warmupTime":0,"category":"CORE","readerDir":"NRTCachingDirectory(MMapDirectory@\/usr\/local\/tomcat\/apache-tomcat-7.0.57\/MySolrHome\/MySolrInstance\/data\/index lockFactory=NativeFSLockFactory@\/usr\/local\/tomcat\/apache-tomcat-7.0.57\/MySolrHome\/MySolrInstance\/data\/index; maxCacheMB=48.0 maxMergeSizeMB=4.0)"},"timestamp":1420548161,"status":200}

**Comment by wiibaa** [comment]
seems to be unformatted and on one-line indeed, so what I propose should be achievable

**Comment by momok2** [comment]
you think i can use the json_lines codec to do this ?

**Comment by wiibaa** [comment]
did not actually test it but that's the main purpose of this codec when used with stream input like tcp/udp, so it's worth a try :)

**Comment by momok2** [comment]
ok thanks i try it 
can you help me to write the curl commands in a shell ??

**Comment by wiibaa** [comment]
Really? Nothing difficult, you just have to write one curl by line and use echo to insert a newline
Create a file jolokia-metrics.sh and use its absolute path in the `command => ` config
`````
#/bin/bash
curl "http://myhost/jolokia/read/solr!/MySolrInstance:type=searcher,id=org.apache.solr.search.SolrIndexSearcher/"
echo
curl ...
echo
curl ...
echo

**Comment by momok2** [comment]
Thank you @wiibaa

**Comment by wiibaa** [comment]
Obviously you now want to change your exec input config to call your script file

input {
  exec {
    **command =>** "/absolute/path/to/jolokia-metrics.sh"
    interval => 60
    codec => json_lines
  }
}

**Comment by momok2** [comment]
Ok thanks 
i'll try it and i tel you if this works

**Comment by suyograo** [comment]
Closing this in favor of #2302
