### ISSUE TITLE
RabbitMQ input plugin failures leave open sockets

### ISSUE THREAD

**Issue by asmaps** [elasticsearch/logstash#2322]
Although the issue in the JIRA tracker is quite old and the link in it doesn't even work anymore the problem seems to persist. I also get the error messages named in the ticket and I have tons of unclosed connections from the logstash server in my RabbitMQ which causes it to crash once a day...

https://logstash.jira.com/browse/LOGSTASH-1698

I hope that the issue gets a little attention if it is in the GitHub tracker :-)

**Comment by untergeek** [comment]
Please open an issue at the plugin's own repository: https://github.com/logstash-plugins/logstash-input-rabbitmq

Thanks!

**Comment by asmaps** [comment]
Okay, opened an issue: logstash-plugins/logstash-input-rabbitmq#8
