### ISSUE TITLE
sincedb file not createt with v1.4.2 on FreeBSD10-x64

### ISSUE THREAD

**Issue by StefanSa** [elasticsearch/logstash#2329]
Hi all,
i have this file input filter.

     file {
         path => ["/data/log/network.log"]
        sincedb_path => "/var/log"
        start_position => "beginning"
        type => "syslog"
        tags => [ "netsyslog" ]
        }

this input filter works, but no sincedb file found witch "find / -name *since*" or "lsof -p PID".
logstash running as "root".

and i find this in debug mode:

:message=>"_sincedb_open: /var/log: Permission denied - /var/log", :level=>:debug, 
:file=>"filewatch/tail.rb"

same proplem with /tmp
 :message=>"_sincedb_open: /tmp: Permission denied - /tmp", :level=>:debug

as root ??
But the "normal" logstash.log file was createt in "/var/log"

Any help here ?
Thx
Stefan

**Comment by wiibaa** [comment]
@StefanSa sincedb_path should point to a file not a directory. Re-reading the doc I see the possible confusion. Need indeed some improvment

**Comment by StefanSa** [comment]
Hi wiibaa, your right.
it's work now, thank you for your help.

Stefan
