### ISSUE TITLE
Timezone can't be set dynamically in date filter

### ISSUE THREAD

**Issue by nornagon** [elasticsearch/logstash#2344]
I have a bunch of servers shipping logs using logstash-forwarder, and I have them set up to attach their timezone:

```
{
  "network": {...},
  "files": [
    {
      "paths": [...]
      "fields": { "type": "syslog", "timezone": "America/Los_Angeles" }
    }
  ]
}
```

On the central logstash server I have this filter:

```
filter {
  if [type] == "syslog" {
    ...grok, syslog_pri...
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
      timezone => "%{timezone}"
    }
  }
}
```

But since the date module sets up the matchers at boot time, the `%{timezone}` never gets substituted, and logstash fails to boot with this message:

```
  The datetime zone id '%{timezone}' is not recognised
```

**Comment by wiibaa** [comment]
Sorry but timezone cannot use dynamic  value, it is already registered as an enhancement in #1685 

You might be interested in the workaround described in this comment: https://github.com/elasticsearch/logstash/issues/1685#issuecomment-54278158

**Comment by suyograo** [comment]
Dup of https://github.com/elasticsearch/logstash/issues/1685
