### ISSUE TITLE
Convert From Interger timestamp to @timestamp

### ISSUE THREAD

**Issue by momok2** [elasticsearch/logstash#2348]
hi all ,
how can i convert a integer timstamp like this     "timestamp" => 1421161381,
to a date timestamp like this "@timestamp" => "2015-01-13T15:03:01.525Z"

thanks

**Comment by jordansissel** [comment]
Date filter can do this:

date { match => [ "timestamp", "UNIX" ] }

-Jordan

**Comment by momok2** [comment]
Ok Thanks
