### ISSUE TITLE
oldlogstashjson do not work for output elasticsearch_river

### ISSUE THREAD

**Issue by zhenghu** [elasticsearch/logstash#2349]
The logstash json schema was changed in logstash 1.2.0. In which the "@" prefix and the "@fields" group was removed. It broke some of my programs since the code was built with the old schema. Is there any way to get logstash output with the old json schema?

I am using elasticsearch_river output and I tried adding "codec => oldlogstashjson" in output configuration, it changed nothing.

But I tried with rabbitmq and file output with codec => oldlogstashjson, it works well.

Is there any config should be applied for elasticsearch_river to enable oldlogstashjson codec?

**Comment by untergeek** [comment]
Elasticsearch is deprecating rivers soon.  You should not be using this output.  It is not being carried over to Logstash 1.5.

In Logstash 1.4.2, the elasticsearch_river plugin does not support using the output codec, which is why it does not work for you.

**Comment by untergeek** [comment]
If you require this functionality still, your only option is to continue using older versions of Logstash.  It will not be included going forward.

**Comment by untergeek** [comment]
It is true that in Logstash 1.5, the new plugin ecosystem would allow you to maintain a personal version of the elasticsearch_river output plugin that you would be free to modify, as desired.  Any such plugin will be unsupported and unmaintained by Logstash.  

I reiterate in the strongest possible terms, however, that rivers are going away in Elasticsearch.  They will be unsupported in the future.  I recommend that you find another way to accomplish your design.

**Comment by RichardCSY** [comment]
I faced the same problem. But I am using elasticsearch output instead of elasticsearch_river. Does it affect by the deprecation of elasticsearch_river?
