### ISSUE TITLE
Logstash unable to connect after installing elasticsearch-river-jdbc plugin

### ISSUE THREAD

**Issue by darkpixel** [elasticsearch/logstash#2350]
After installing the https://github.com/jprante/elasticsearch-river-jdbc plugin, logstash is unable to connect.  Running logstash -vv returns this:
````
log4j, [2015-01-13T12:31:18.927] DEBUG: org.elasticsearch.discovery.zen: [logstash-tetrad-431-2250] filtered ping responses: (filter_client[true], filter_data[false])
	--> target [[tetrad][JsINgC5sTOqVtwfHlTO-Rw][tetrad][inet[/192.168.7.99:9300]]], master [[tetrad][JsINgC5sTOqVtwfHlTO-Rw][tetrad][inet[/192.168.7.99:9300]]]
	--> target [[zefram][mQfhCd2QRbGQFToqWmnZEw][zefram][inet[/192.168.7.189:9300]]{master=true}], master [[tetrad][JsINgC5sTOqVtwfHlTO-Rw][tetrad][inet[/192.168.7.99:9300]]]
log4j, [2015-01-13T12:31:18.942] DEBUG: org.elasticsearch.transport.netty: [logstash-tetrad-431-2250] connected to node [[tetrad][JsINgC5sTOqVtwfHlTO-Rw][tetrad][inet[/192.168.7.99:9300]]]
log4j, [2015-01-13T12:31:19.016]  WARN: org.elasticsearch.transport.netty: [logstash-tetrad-431-2250] Message not fully read (request) for [74293] and action [discovery/zen/join/validate], resetting
log4j, [2015-01-13T12:31:19.032]  INFO: org.elasticsearch.discovery.zen: [logstash-tetrad-431-2250] failed to send join request to master [[tetrad][JsINgC5sTOqVtwfHlTO-Rw][tetrad][inet[/192.168.7.99:9300]]], reason [org.elasticsearch.transport.RemoteTransportException: [tetrad][inet[/192.168.7.99:9300]][discovery/zen/join]; org.elasticsearch.transport.RemoteTransportException: [logstash-tetrad-431-2250][inet[/192.168.7.99:9301]][discovery/zen/join/validate]; org.elasticsearch.ElasticsearchIllegalArgumentException: No custom index metadata factory registered for type [riverstates]]
````

Fixing the issue requires shutting down logstash, removing the plugin from all nodes, restarting elasticsearch, (and I think removing the indexes created by the plugin), then restarting logstash.

Not sure if this is a logstash issue or an issue with the river-jdbc plugin.

**Comment by untergeek** [comment]
As observed in the url, this is not an officially supported plugin.

On a side note, rivers are being deprecated and removed from Elasticsearch.  This functionality and plugin will not be supported in future releases.  The correct path forward is dedicated Logstash plugins using the elasticsearch output.

**Comment by darkpixel** [comment]
The correct way to pull data from a Microsoft SQL server would be for someone to build a logstash plugin?

**Comment by untergeek** [comment]
Elasticsearch is deprecating rivers, and the preferred replacement for rivers is to use Logstash (or some other mechanism of your own devising) to convert source material into JSON and send it to Elasticsearch.

Rivers are problematic for multiple reasons, not the least of which being their single-threaded nature.

**Comment by darkpixel** [comment]
Thanks for the info.  You wouldn't happen to know of a better solution for grabbing data from MSSQL and getting it into elasticsearch would you?  ;)

**Comment by untergeek** [comment]
I don't yet.  I anticipate that as the deprecation looms, people will be pressed to write solutions to these and other dilemmas.  Rivers will be deprecated shortly, but functionality will not be officially removed until 2.0, if I were to hazard a guess.

**Comment by darkpixel** [comment]
Thanks again for the info @untergeek.
