### ISSUE TITLE
Defining a development gem in the gemfile and specifying the :path doesn't add it to the loadpath.

### ISSUE THREAD

**Issue by ph** [elasticsearch/logstash#2351]
Logstash use the `Gemfile` to install gems but doesn't use it to modify the load path of the application.
So if you add this line to your gemfile (useful to test an unreleased gems...):

```
gem "logstash-devutils", :path => "~/es/logstash-devutils"
```

The `~/es/logstash/lib` wont be added to the application `$LOAD_PATH` and the tests will fail with
```
LoadError: no such file to load -- logstash/devutils/rspec/spec_helper
```

the `:git` option might fail too?

**Comment by purbon** [comment]
I reproduce it by:

* Having an empty new logstash environment throw ```rm -rf vendor/bundle```.
* Adding ```gem "logstash-devutils", :path => "../../logstash-devutils"``` to the tools/Gemfile
* Run ```rake bootstrap```
* Run ```bin/logstash rspec spec/core/conditionals_spec.rb```

it might also happen, as @ph said in runtime.

**Comment by ph** [comment]
At runtime:

I did:

```
bin/plugin uninstall logstash-input-generator
```

Added this to the tools/Gemfile
```
gem 'logstash-input-generator', :path => '~/es/logstash-all/logstash-input-generator'
```

Ran:
```
rake vendor:gems
```

Got this output:
```
Using logstash 2.0.0.dev from source at /Users/ph/es/logstash                                                                                                                        │~/s/l/l/logstash git:master ❯❯❯ cd inputs                                                                                                                                         ◼
Using logstash-codec-plain 0.1.3                                                                                                                                                     │~/s/l/l/l/inputs git:master ❯❯❯ ls                                                                                                                                                ◼
Using logstash-input-generator 0.1.1 from source at ~/es/logstash-all/logstash-input-generator                                                                                       │beeroclock.rb
Using bundler 1.7.12                                                                                                                                                                 │~/s/l/l/l/inputs git:master ❯❯❯                                                                                                                                                   ◼
Your bundle is complete!                                                                                                                                                             │
Gems in the group development were not install
```

And this will fail:
```
bin/logstash -e 'input { generator {}}'
The error reported is: 
  Couldn't find any input plugin named 'generator'. Are you sure this is correct? Trying to load the generator input plugin resulted in this error: no such file to load -- logstash/inputs/generator
```

**Comment by colinsurprenant** [comment]
Yes, confirmed. I am not sure I understand why it was working before - it may be because I was testing with a plugin that had been previously installed, not sure.

**Comment by ph** [comment]
We need to test if defining the `Gemfile` with ENV["BUNDLE_GEMFILE"] and doing Bundler.setup fix this issue..

**Comment by colinsurprenant** [comment]
So, the problem is with the way we *manually* set the GEM_PATH, which only points to the `vendor/bundle/...` dir and we don't include any *remote* dir as when adding a gem using the `:path` directive. These actually appears at the top of the `.lock` file in 
```ruby
PATH
  remote: /path/to/your/super/awesome/logstash/plugin/yo
  specs
  ...
```
and `Bundler.setup` will obviously add them to the `GEM_PATH`.

So yes, I think this is a good question, is there still a valid reason for not relying on `Bundler.setup` to set the `GEM_PATH`?  Investigating. @jordansissel @ph @jsvd @electrical Thoughts?

**Comment by jordansissel** [comment]
If the world doesn't explode when invoking Bundler.setup, I am in favor of using it.

**Comment by ph** [comment]
I am in favor of using it, I would be surprised if it break anything.

**Comment by colinsurprenant** [comment]
:bomb:

**Comment by purbon** [comment]
+1 on checking on Bundler.setup I will release of some pain, if it works properly for us, for sure.
