### ISSUE TITLE
Logstash 1.5.0  writing the event to the failure file, Bug?

### ISSUE THREAD

**Issue by remotesyssupport** [elasticsearch/logstash#2352]
To capture the messages that fail grok, I write to a file

```javascript
# Catch grok failures
output {
   if [type] == "syslog" and "_grokparsefailure" in [tags] {
       file { path => "/mnt/log/logstash/failed_syslog-%{+YYYY-MM-dd}" }
   }
}
```

But instead, in the error I see
```
"File: the event tried to write outside the files root, writing the event to the failure file"

```

And the events are written to 
```
/mnt/log/logstash/failed_syslog-/_filepath_failures

```

Am I doing something wrong or is it a bug?

**Comment by untergeek** [comment]
Plugin tickets should be opened in their respective location, e.g. https://github.com/logstash-plugins/logstash-output-file

**Comment by remotesyssupport** [comment]
Extremely sorry, closing this here and opening it there.  [https://github.com/logstash-plugins/logstash-output-file/issues/3 ]

Apologies to Pier-Hugues who has already self-assigned the task.

**Comment by ph** [comment]
No worries @remotesyssupport i will check it :)
