### ISSUE TITLE
metrics example broken

### ISSUE THREAD

**Issue by twalzer** [elasticsearch/logstash#2355]
Hi,

I think the metrics filter documentation (http://logstash.net/docs/1.4.2/filters/metrics) has a problem:
The "message" is not/no longer working:
output {
  # only emit events with the 'metric' tag
  if "metric" in [tags] {
    stdout {
      message => "rate: %{events.rate_1m}"
    }
  }
}

There is also a question on SO: http://stackoverflow.com/questions/24452239/print-a-string-to-stdout-using-logstash-1-4 which details the solution:

output {
        if "metric" in [tags]
        {
                stdout {        
                        codec => line {
                                        format => "Rate: %{events.rate_1m}"
                        }

                }
        }
}

However I think the docs should be correct in the first place.

**Comment by wiibaa** [comment]
@twalzer I think this is already correct for the upcoming 1.5 release, can you please double-check here https://github.com/logstash-plugins/logstash-filter-metrics/blob/master/lib/logstash/filters/metrics.rb#L73 
Thanks

**Comment by twalzer** [comment]
1.5 is correct. But shouldn´t the 1.4 docs also reflect the truth?

**Comment by wiibaa** [comment]
@twalzer the point is that the *official doc* is already up to date: http://www.elasticsearch.org/guide/en/logstash/current/plugins-filters-metrics.html

I do not now when Logstash team will decide to tear down logstash.net, but it will be a hearbreaking change :sob:

**Comment by twalzer** [comment]
Oh, sorry. I missed that one. Google seems to rank logstash.net still higher than elasticsearch.....
This could be a heart breaker, indeed.
