### ISSUE TITLE
Deafault INT template doesn't work!

### ISSUE THREAD

**Issue by fervid** [elasticsearch/logstash#2361]
my conf:
input {
	file {
		path => "/tmp/logstash/test.log2"
		sincedb_path => "/dev/null"
		start_position => "beginning"
		type => "syslog_test"
	}
}

filter {
	if [type] == "syslog_test" {
		grok {
			patterns_dir => "/opt/logstash-1.4.2/patterns"
			match => [
				"message", "%{PRIORITY:pri}"
			]
		}
	}
}

output {
	file { 
		path => "/tmp/logstash/test.norm.log"
		flush_interval => 0
	}
	stdout {
		codec => rubydebug
	}
}

my patterns for test:
#PRIORITY \<INT\>
PRIORITY \<\d+\>

If i use PRIORITY \<INT\> I get:
{
       "message" => "\<24\>Jan 14 12:32:54 ",
      "@version" => "1",
    "@timestamp" => "2015-01-15T19:32:38.621Z",
          "type" => "syslog_test",
          "host" => "alerts-db",
          "path" => "/tmp/logstash/test.log2",
          "tags" => [
        [0] "_grokparsefailure"
    ]
}
{
       "message" => "\<24\>Jan 15 12:32:54 ",
      "@version" => "1",
    "@timestamp" => "2015-01-15T19:32:38.621Z",
          "type" => "syslog_test",
          "host" => "alerts-db",
          "path" => "/tmp/logstash/test.log2",
          "tags" => [
        [0] "_grokparsefailure"
    ]
}

If I use PRIORITY \<\d+\> I get:
{
       "message" => "\<24\>Jan 14 12:32:54 ",
      "@version" => "1",
    "@timestamp" => "2015-01-15T19:33:38.733Z",
          "type" => "syslog_test",
          "host" => "alerts-db",
          "path" => "/tmp/logstash/test.log2",
           "pri" => "\<24\>"
}
{
       "message" => "\<24\>Jan 15 12:32:54 ",
      "@version" => "1",
    "@timestamp" => "2015-01-15T19:33:38.739Z",
          "type" => "syslog_test",
          "host" => "alerts-db",
          "path" => "/tmp/logstash/test.log2",
           "pri" => "\<24\>"
}

What is wrong?

**Comment by untergeek** [comment]
You’re trying to grok a message defined as just "%{PRIORITY:pri}” with match => [ "message", "%{PRIORITY:pri}” ].  




But the message content in each example is "Jan 15 12:32:54 “.  




This does not match.  That’s why you have the _grokparsefailure tag.


—Aaron

**Comment by fervid** [comment]
But in second case I used PRIORITY \<\d+\> and it's ok. 
Also, if I use PRIORITY \<(?:[+-]?(?:[0-9]+))\> it will ok too.
But if I use PRIORITY \<INT\> it doesn't work. Why?

**Comment by fervid** [comment]
Sorry, it is not problem. I understood mistake I've done!!!
I must use INT with follow syntax: %{INT}.
