### ISSUE TITLE
Deb package installs both init and upstart scripts

### ISSUE THREAD

**Issue by pwyliu** [elasticsearch/logstash#2367]
I've just installed logstash from the repository, on Ubuntu 14.04. I ended up with both an upstart script in `/etc/init` and regular init in `/etc/init.d`. This has the potential to cause confusion, especially with configuration management systems. 

For example, I had a problem with Chef 11 that went something like this:

1. Write a Chef recipe to install and start logstash. If you don't specify a provider Chef tries to detect it automatically. Puppet has similar behaviour, though it may do detection differently.
2. Run Chef. Chef detects the script in init.d and uses this to start logstash.
3. SSH into server, try to manage logstash by typing `service logstash status`. `service` uses the upstart script, and upstart doesn't know anything about processes that it doesn't manage, so it says logstash is not running.
4. "Huh", one might say. Type `service logstash start`, upstart launches a new logstash procces. Now you have two!

So this is a pretty easy condition to detect and fix, but I think it's a little unfriendly (and unnecessary) for the package to install both kinds of scripts. Maybe it would be better if the deb could detect whether it's running on a system that has upstart, and then conditionally install one or the other.

**Comment by electrical** [comment]
Hi,

With LS 1.5.0 we ditched the upstart config and only included the sysv init script.
I know that debian and Ubuntu are switching over to use systemd instead of upstart so at some point we will be making that move as well.

**Comment by pwyliu** [comment]
Okay, I guess this problem goes away by itself then, I'll close this. Thanks!
