### ISSUE TITLE
Date with multiple groks

### ISSUE THREAD

**Issue by vic3lord** [elasticsearch/logstash#2369]
Date gives me an error when using with 2 groks

```
grok {
  match => ["message", "%{TEST}"]
  add_tag => "test1"
}
grok {
  match => ["message", "%{TEST2}"]
  add_tag => "test2"
}
date {
  match => [ "timestamp", "ISO8601" ]
} 
```

```
{:timestamp=>"2015-01-18T19:02:45.132000+0000", :message=>"Failed parsing date from field", :field=>"timestamp", :value=>"Jan 18 19:02:42", :exception=>java.lang.IllegalArgumentException: Invalid format: "Jan 18 19:02:42", :level=>:warn}
```

**Comment by magnusbaeck** [comment]
This has nothing to do with multiple grok filters. The problem is that "Jan 18 19:02:42" isn't an ISO8601 date. Try this instead:

    date {
      match => ["timestamp", "MMM dd HH:mm:ss", "MMM  d HH:mm:ss"]
    }

**Comment by vic3lord** [comment]
I want to change the original date and mutate it to be ISO8601

is it possible with date?

**Comment by magnusbaeck** [comment]
The date filter produces an ISO8601 date, by default stored into the `@timestamp` field. If this doesn't solve your problem, please elaborate. I'm not sure exactly what you want to accomplish.

**Comment by vic3lord** [comment]
Thanks for the help :+1:
