### ISSUE TITLE
Changing elasticsearch_http host DNS is not re-resolved to the new IP

### ISSUE THREAD

**Issue by ohookins** [elasticsearch/logstash#2378]
I have an ElasticSearch cluster behind an AWS ElasticLoadbalancer and the IP addresses behind the DNS name recently changed. It appears that the Logstash nodes did not notice this change and our events started disappearing. I haven't exhaustively recreated the scenario but perhaps can provide some more information on what was happening.

1. The ```elasticsearch_http``` output was configured with a DNS name for the ElasticSearch host.
2. The IP addresses returned from the DNS name had changed.
3. The original IP address was no longer active.
4. Logstash appeared to still have the connection to the old IP address, which was now in CLOSE_WAIT state.
5. The Logstash log file was filled with events like this:
```
lang.OutOfMemoryError: Java heap space, :backtrace=>[], :level=>:warn}
2015-01-20_11:12:40.66531 {:timestamp=>"2015-01-20T11:12:40.664000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>5000, :exception=>java.
lang.OutOfMemoryError: Java heap space, :backtrace=>[], :level=>:warn}
```
I suspect this was simply a cause of the events not being sent properly, and queuing up causing the process to run out of heap space, rather than being the cause of it.

**Comment by electrical** [comment]
Looks like we only do DNS resolving at startup of logstash. @jordansissel @colinsurprenant any idea's ?

**Comment by untergeek** [comment]
Migrating similar issue from JIRA: https://logstash.jira.com/browse/LOGSTASH-1335

**Comment by jordansissel** [comment]
> queuing up causing the process to run out of heap

I don't think logstash actually has any internal queues which are unbounded, so I don't quite follow this conclusion.

**Comment by ohookins** [comment]
Well, it did run out of heap. If it's not due to queuing, perhaps it's another bug :(

**Comment by jordansissel** [comment]
@ohookins totally believe you there :)

I'll file a separate bug on this: https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/51

Let's track the resolution/discussion of the dns problem there. I'll close this.
