### ISSUE TITLE
Mutate with non-existent field throws an error

### ISSUE THREAD

**Issue by thomasmarkus** [elasticsearch/logstash#2379]
`bin/logstash -e 'filter { mutate { remove => "[foo][bar]" } }'`

logstash-1.4.2 = OK
logstash-1.5.0beta1 = OK
logstash-1.5-snapshot (c95cc001b532906bfcaf3ea6808a63f7a8e4ae5e) = FAIL

```Exception in filterworker {"exception"=>#<NoMethodError: undefined method `delete' for nil:NilClass>, "backtrace"=>["/Users/tmarkus/git/logstash/build/logstash-1.5.0.beta1/lib/logstash/util/accessors.rb:51:in `del'", "/Users/tmarkus/git/logstash/build/logstash-1.5.0.beta1/lib/logstash/event.rb:192:in `remove'", "/Users/tmarkus/git/logstash/build/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-0.1.2/lib/logstash/filters/mutate.rb:227:in `remove'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/tmarkus/git/logstash/build/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-0.1.2/lib/logstash/filters/mutate.rb:226:in `remove'", "/Users/tmarkus/git/logstash/build/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/logstash-filter-mutate-0.1.2/lib/logstash/filters/mutate.rb:215:in `filter'", "(eval):50:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):46:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/Users/tmarkus/git/logstash/build/logstash-1.5.0.beta1/lib/logstash/pipeline.rb:272:in `filter'", "/Users/tmarkus/git/logstash/build/logstash-1.5.0.beta1/lib/logstash/pipeline.rb:206:in `filterworker'", "/Users/tmarkus/git/logstash/build/logstash-1.5.0.beta1/lib/logstash/pipeline.rb:150:in `start_filters'"], :level=>:error}```

**Comment by suyograo** [comment]
Thanks, confirmed it is broken with latest
