### ISSUE TITLE
logstash design

### ISSUE THREAD

**Issue by rakesh91** [elasticsearch/logstash#2385]
Hi,
In our setup we have around 700 vms and we need to ship logs to central location. So thought of using logstash proposed architecture (logstash(shipper)-redis-logstash-ES). Logs are very important and cant offered to loose single line. Considering this requirement 
1. How well the above mentioned design is good for the requirement?
2. Should I need high end redis machines for this purpose?

Also most important part is, Is there any standard fail over process for logstash? 
Thanks

**Comment by suyograo** [comment]
@rakesh91 this architecture is recommended and works well. Please test your ingestion rate and decide how much resources to add for redis -- its not something we can answer without knowing more about your use case.

For failover see http://www.elasticsearch.org/guide/en/logstash/current/pipeline.html#_fault_tolerance

For questions like this please use the mailing list  https://groups.google.com/forum/#!forum/logstash-users
