### ISSUE TITLE
filter/xml ignore namespace

### ISSUE THREAD

**Issue by Stefan129** [elasticsearch/logstash#2392]
Hi,

I need to remove namespace from the input xml before applying xpath expressions in the xml filter.
Changing the filter to achieve this is easy but it would be nice to have this feature included as an attribute in the configuration of the xml filter and also part of the standard release.

Adding the following line after the XML creation (doc = Nokogiri::XML(value)) will remove the namespace:
doc.remove_namespaces!

**Comment by suyograo** [comment]
@wiibaa closed this via https://github.com/logstash-plugins/logstash-filter-xml/pull/6
