### ISSUE TITLE
XML Parse failure, on field from a grok filter

### ISSUE THREAD

**Issue by johnwards** [elasticsearch/logstash#2398]
I've got a pretty simple log format coming in:
```
2015-01-21T20:59:59+00:00 <foo><key>value1</key><key>value2</key></foo>
```
And I'd like to parse the XML into a data structure for stuffing into elasticsearch. I'm testing it like this currently:
```
input {
	stdin {}
}
filter {
  grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{GREEDYDATA:logmessage}" }
  }
  date {
    match => [ "timestamp" , "ISO8601" ]
  }
  xml {
    source => "logmessage"
  }
}
output {
  stdout { codec => rubydebug }
}
```

I test this like so...and here is where it goes wrong...
```
/opt/logstash/bin/logstash -f stdinstdout.conf 
Using milestone 1 filter plugin 'xml'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones {:level=>:warn}
2015-01-21T20:59:59+00:00 <foo><key>value1</key><key>value2</key></foo>
Trouble parsing xml with XmlSimple {:source=>"logmessage", :value=>"<foo><key>value1</key><key>value2</key></foo>", :exception=>#<NoMethodError: undefined method `start_with?' for nil:NilClass>, :backtrace=>["/opt/logstash/lib/logstash/event.rb:135:in `[]='", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-xml-0.1.2/lib/logstash/filters/xml.rb:126:in `filter'", "(eval):144:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):140:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:268:in `filter'", "/opt/logstash/lib/logstash/pipeline.rb:206:in `filterworker'", "/opt/logstash/lib/logstash/pipeline.rb:150:in `start_filters'"], :level=>:warn}
{
       "message" => "2015-01-21T20:59:59+00:00 <foo><key>value1</key><key>value2</key></foo>",
      "@version" => "1",
    "@timestamp" => "2015-01-21T20:59:59.000Z",
          "host" => "elklogger",
     "timestamp" => "2015-01-21T20:59:59+00:00",
    "logmessage" => "<foo><key>value1</key><key>value2</key></foo>",
          "tags" => [
        [0] "_xmlparsefailure"
    ]
}
```
This is Logstash 1.5 beta, I've also checked there isn't a new xml filter plugin etc.

Any ideas, I'm sure I'm doing something stupid...

**Comment by wiibaa** [comment]
@johnwards I suppose you must specify a `target`

**Comment by johnwards** [comment]
Doh! That was it. Odd that it is an optional param. 

Not the most pretty XML parsing for single nodes, but XML to JSON is never fun :)

**Comment by wiibaa** [comment]
I suppose it is because you could use **store_xml => false** and **xpath** . Then specifying a target has no meaning.
Indeed that's not easy to get it right

**Comment by Aldian-fr** [comment]
They really should update the doc. I got tricked too :(

**Comment by lgrkvst** [comment]
me too =(

**Comment by ChrisMagnuson** [comment]
Me four =(. I actually wanted the XML filter to create the target property based on the name of the root element so that the root element name is not lost. I will open this as a separate issue to request this as a feature.

**Comment by magnusbaeck** [comment]
> They really should update the doc.

https://github.com/logstash-plugins/logstash-filter-xml/pull/8 updated the documentation of the `target` option to state that it's required under some circumstances. For some reason the [xml filter documentation at elastic.co](https://www.elastic.co/guide/en/logstash/current/plugins-filters-xml.html#plugins-filters-xml-target) hasn't been updated even though the PR was submitted over two months ago.

Also, https://github.com/logstash-plugins/logstash-filter-xml/issues/9 calls for a better error message than what's described in this bug.

**Comment by suyograo** [comment]
Docs have been updated. https://www.elastic.co/guide/en/logstash/current/plugins-filters-xml.html.
