### ISSUE TITLE
S3 Output Plugin fails on windows

### ISSUE THREAD

**Issue by thesolution** [elasticsearch/logstash#2399]
There are two issues I just ran into with the S3 plugin for windows.

#### The temp_directory is hardcoded to /opt/logstash/s3_temp/
When I ran logstash with the default path it tried to access this path in two different ways on my Windows 7 machine.  
* First it tried creating the temp dir as a sub directory of my cwd( cwd was C:\logstash\ so the path it wanted to create the temp dir on was C:\logstash\opt\logstash\s3_temp). 
* Secondly it tried accessing the temp file from a path rooted at opt (/opt/logstash/s3_temp/)

Fix: make temp_directory a parameter with a default of /opt/logstash/s3_temp/

     # Temp directory
     config :temp_directory, :default => "/opt/logstash/S3_temp/"

#### @tempFile is open when upFile tries to delete it
In Windows open file handles will cause a File.delete operation to throw an exception.

Modifying upFile fixes this issue

     # close the file before deleting
     @tempFile.close
     File.delete (file)

I will submit a pull request addressing these issues.

**Comment by ph** [comment]
In the latest version of the plugin located at https://github.com/logstash-plugins/logstash-output-s3/ we have added an option named `temporary_directory` allowing you to override where to save your files.

We are also closing the File handle before delete it.
https://github.com/logstash-plugins/logstash-output-s3/blob/master/lib/logstash/outputs/s3.rb#L168

Theses changes will be released in logstash 1.5.

Also with logstash 1.5 we have moved all the plugins into their own repository.
If you find any more issue could you create them in the issues tracker of the plugin?

**Comment by ph** [comment]
I am closing this ticket, If its still an issue feel free to reopen it or create a new one.
