### ISSUE TITLE
`rake bootstrap` on Windows Ruby cannot 'gem install minitar'

### ISSUE THREAD

**Issue by jordansissel** [elasticsearch/logstash#2402]
Bootstrapping goes: download jruby, unpack jruby, relaunch under jruby.

However, with the Windows Ruby installer, it ships with a broken rubygems configuration such that `gem install` cannot work due to SSL cert trust problems.

```
ERROR:  Could not find a valid gem 'minitar' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server ce
rtificate B: certificate verify failed (https://api.rubygems.org/latest_specs.4.8.gz)
Installation of minitar failed
```

The recommended workaround for each user is this: https://gist.github.com/luislavena/f064211759ee0f806c88

However, I think this is a bad workaround. It requires every dev on windows to do this "hunt for the ruby directory, download this random cert file, and hope you did it right". I want to automate the workaround, but I am at present unable to find a solution: https://gist.github.com/jordansissel/76b47be00509c5b6f5a0

**Comment by jordansissel** [comment]
If I patch the default cert method, I get a bit farther:

```
class Gem::Request
  def add_rubygems_trusted_certs(store)
    ca_path = File.join(File.dirname(__FILE__), "..", "tools", "ca")
    Dir.glob(File.join(ca_path, "*.pem")) do |ssl_cert|
      p ssl_cert
      store.add_file ssl_cert
    end
  end
end
```

Instead of failing to download the latest-gems list, it fails to fetch from fastly:

```
ERROR:  Could not find a valid gem 'O_o' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server ce
rtificate B: certificate verify failed (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/O_o-1.0.0.gemspec.rz)
```

**Comment by jordansissel** [comment]
Even if I provide the fastly cert + chain (via openssl s_client -showcerts > fastly.pem) it still fails to verify fastly.net.. hmm so weird

**Comment by wiibaa** [comment]
Did not run into this issue recently, strange...
I was using this [manual solution](https://gist.github.com/fnichol/867550#the-manual-way-boring) with the ENV variable SSL_CERT_FILE, maybe it is easier to set it on behalf of the user than patching ruby

**Comment by jordansissel** [comment]
I made an effort to get the Digicert root and intermediate in pem format, but they are in some binary format I don't' recognize. https://www.digicert.com/digicert-root-certificates.htm

**Comment by jordansissel** [comment]
@wiibaa Fetching the curl cacert list and using my monkeypatch seems to fix it.

**Comment by jordansissel** [comment]
I lied. Adding the curl cacert list plus using whatever Windows Ruby's rubygems ships with does the trick.

This was quite frustrating.

**Comment by wiibaa** [comment]
"frustrating" is a buzzword when talking about windows (or java) experiences

**Comment by jordansissel** [comment]
eh, this was a windows ruby or a rubygems bug for not shipping the correct ssl certs to talk with rubygems.org.

Doesn't matter, monkeypatched it :(
