### ISSUE TITLE
[1.5.0] patterns default path "./patterns" not checked unless specifically configured

### ISSUE THREAD

**Issue by JamesJJ** [elasticsearch/logstash#2406]
I'm using ~1.5.0 at commit e89eb0a12e9a5194eb54040b1c30821f66c069de.

I have put a patterns file in ./patterns:

`$ ls ./bin/logstash ./patterns/my-patterns`
`./bin/logstash  ./patterns/my-patterns`
`$`

... it isn't being read. Running `--debug` shows:

<snipped>
`Grok patterns path {:patterns_dir=>["/opt/logstash/current/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-0.1.2/patterns"], :level=>:info, :file=>"logstash/filters/grok.rb", :line=>"239"}`
</snipped>

...my config file does *not* specify :patterns_dir within the grok config. If I add `:patterns_dir => [ "./patterns" ]`, then my patterns file *is* read ..... so this is just a behavioural change from 1.4.2 (having to specify in the grok config, where before this was unnecessary).

Intended or bug?

Many thanks,
-J

**Comment by jsvd** [comment]
Hi! The "./patterns" dir was reintroduced to the from filter in https://github.com/logstash-plugins/logstash-filter-grok/commit/c103c2ffe8ab676d5498c15f41af5c88ab55ee1f 
Version 0.1.3 of this plugin will include the fix

**Comment by JamesJJ** [comment]
Super - many thanks.

(Closing this)
