### ISSUE TITLE
file input: Massive loss off events if file globbing is used

### ISSUE THREAD

**Issue by fonzmike** [elasticsearch/logstash#2410]
Hi,

every day i receive some dozen log files in a directory each file 50MB, 200.000 events. The Timestamps are ascending, about 5 to 20 events per second, no gaps. I process them with a file input using file globbing (\*.log) to import all files within that directory. All files are read but there is a massive loss of events, some files simply stop processing. Kibana shows broad gaps.
If i process one file after the other using full file names, the timeline in Kibana is complete.
Processing of a single directory like /var/log with globbing (\*.log) works like a charme.

There are no errors or messages in any log.

Please help in debugging/solving this, thank you.

Environment:
Server: RHEL, Java 1.8.0_25, Elasticsearch 1.4.2, Kibana 3 plugin, kopf plugin, logStash 1.4.2, redis 2.8.19, Apache 2.4 (reverse auth proxy to Kibana).
Shipper: Win Server 2008R2, Java 1.6.0_22 and 1.7.0_25 (tried both, no difference), logStash 1.4.2.

Setup: 
logStash shipper on win server, file input, filter, redis output
indexer on rhel: redis input, elasticsearch output.

This issue was created after several hours of googling, no hints. If this is a duplicate, pls. pardon ;-)

**Comment by wiibaa** [comment]
Related to #2135 #1902

**Comment by wiibaa** [comment]
In short we must wait for https://github.com/jordansissel/ruby-filewatch/issues/39

**Comment by fonzmike** [comment]
ok thx!
I moved the log files to rhel and ran the agent here, everything worked as expected.
