### ISSUE TITLE
Logstash pipe output doesn't work well with upstart

### ISSUE THREAD

**Issue by zhihuiFan** [elasticsearch/logstash#2411]
Here is some of my configuration. 

input {
    pipe {
        type => 'sar'
        add_field => [ 'st', 'rq' ]
        command => "/usr/bin/sar -q 1"
    }
}
output {}

I'm using logstash 1.3.3,  if I run on the terminal,  it is ok.  but if I run it with upstart, there is no logs generated. 

start on runlevel[35]
start on started mongod
stop on starting mongod
console owner

#pre-start script
#/ebay/logstash/logstash_prestart.py
#end script

exec /logstash/jre/bin/java -Xmx1g -jar /logstash/logstash-1.3.3-flatjar.jar  agent --config /logstash/conf/logstash.conf --log /logstash/logs/logstash-Agent.log

my upstart version is upstart-0.6.5.

I have tried console owner|output, but none of them works.  

what can I do to make them compatible?

**Comment by electrical** [comment]
Its most likely failing because you have no outputs configured.
Can you try to run logstash manually and without the --log flag?

**Comment by zhihuiFan** [comment]
@electrical , appreciate for your reply.  actually I have output configured.  

output {
  redis {
    host => ["my-redis-host"]
      data_type => "list"
      key => "mongodlog"
      reconnect_interval => 10000000000000
  }
  stdout { codec => 'rubydebug' }
}

I tried again manually and without --log flag,  I can see the data in elasticsearch at last. If I run with upstart,  the data is lost. 

I think if it is possible that upstart discard the output of the pipe command?

**Comment by zhihuiFan** [comment]
I didn't figure out how to fix this issue.  but as a workaround, I want a script to write the output of sar to a text file, logstash read from there.  everything is ok now.  Thanks
