### ISSUE TITLE
rss input uses ttl instead of intervall

### ISSUE THREAD

**Issue by arosenheinrich** [elasticsearch/logstash#2420]
RSS channel feature an optional ttl element that indicates how long a channel can be cached before it should be refreshed from the source. It would be an interesting option to use this instead of the intervall parameter for the rss input. My idea would be to make intervall an optional parameter, in case it is not set the channel will be fetched once and, if available, ttl will be used as recrawl time, otherwise a default value could be used.

This is actually the behavior of the elasticsearch rss river (http://dadoonet.github.com/rssriver/), it would be cool to have the same feature in the rss input.

Thanks in advance!
Andrej

**Comment by ph** [comment]
Thank your for the suggestion!

We have extracted all the plugins from the core, the new home for this plugins is now located at https://github.com/logstash-plugins/logstash-input-rss 

Would you mind recreating the issue in the new repository and closing this one? This will allow you to receive notification when someone work or comment on it.

**Comment by arosenheinrich** [comment]
Of course, closed here and new issue #2 at https://github.com/logstash-plugins/logstash-input-rss
