### ISSUE TITLE
Switch to use gem 'ftw' version 0.0.42 instead 0.0.39

### ISSUE THREAD

**Issue by GennadySpb** [elasticsearch/logstash#2427]
In version 0.0.39 in [lib/ftw/dns/dns.rb](https://github.com/jordansissel/ruby-ftw/blob/master/lib/ftw/dns/dns.rb) bug in unpacking ipv6 address.

**Comment by suyograo** [comment]
@purbon this should fix the dependencies mismatch too. Lets update to use 0.0.42

**Comment by purbon** [comment]
Agreed, I think I will update using a pessimistic operator (http://robots.thoughtbot.com/rubys-pessimistic-operator), so something like ```gem 'ffw',  '~> 0.0.42'```, if we follow proper sematic versioning then this would be nice as it will always take the newest minor release.

**Comment by purbon** [comment]
I amend my previous comment, thanks to this line https://github.com/elasticsearch/logstash/blob/master/logstash.gemspec#L33 in the gemspec we are already installing the latest version of ftw in logstash. We can also see it here https://github.com/elasticsearch/logstash/blob/master/tools/Gemfile.jruby-1.9.lock#L52.

More info about that format can be archived with the link in the previous comment.

Another question is to fix some of the plugins to use the latest version of this gem, but not related to this issue.
