### ISSUE TITLE
Allow Logstash RPM to require *either* JRE or JDK

### ISSUE THREAD

**Issue by kjhosein** [elasticsearch/logstash#2428]
We're unable to use Puppet to install the Logstash RPM because it requires the JRE package, while we use the JDK on many of our systems.

**Comment by jordansissel** [comment]
This is fixed for 1.5.0.

---

RPM dependencies, to the best of my knowledge, do not support "Requires X or Y". This is a limitation in RPM.

After various discussions in past tickets, I determined that it would be impossible to properly describe Logstash's java dependency in our deb and rpm packages, so our future releases (1.5.0 and beyond) will no longer list java (of any flavor) as a dependency. 

I put some notes about this decision (with links to further reading) in the code that builds the package: https://github.com/elasticsearch/logstash/blob/master/rakelib/artifacts.rake#L189-L201
