### ISSUE TITLE
Availability of refactored S3 input plugin in the latest logstash RPM release?

### ISSUE THREAD

**Issue by geez** [elasticsearch/logstash#2435]
Hi fellas,

Is the latest S3 input plugin considered for a 1.4.x RPM release?
https://github.com/logstash-plugins/logstash-input-s3/pull/1

We add a few issues with the old version and are currently assessing the refactored one.
Instead of creating our custom RPM and avoid drifiting, we're wondering if it will be included upstream soon?

Regards,
G.

**Comment by ph** [comment]
Hello @geez,
The plugin is planned for 1.5 with all the plugins changes.. I don't think we will do a 1.4.x release.
Concerning your issues with S3, can you check the related issues in the PR to see if they all fixed your problems?

**Comment by geez** [comment]
Hi @ph,

The issue was related to this:
https://github.com/elasticsearch/logstash/issues/1448
and:
https://github.com/elasticsearch/logstash/pull/1913

We have a workaround at the moment so we can wait for the next 1.5 release.

Thanks again,
G.

**Comment by ph** [comment]
You're welcome.
I'll close this.
