### ISSUE TITLE
Make Jenkins run the full test suite again

### ISSUE THREAD

**Issue by jordansissel** [elasticsearch/logstash#2444]

**Comment by ph** [comment]
This is bugging me too, something is wrong with our Jenkins setup for the plugins I had two plugins failing locally and green on jenkins.. The merge and PR arent triggering anything the last test was run 2 month ago.

**Comment by ph** [comment]
I'll manually trigger a build for all the plugins.

**Comment by suyograo** [comment]
this was kicked off by @purbon recently and he has tooling to trigger this automatically

**Comment by purbon** [comment]
we should improve and rock our testing infra tools ;-)
