### ISSUE TITLE
rake artifact:tar - Error installing murmurhash3

### ISSUE THREAD

**Issue by suyograo** [elasticsearch/logstash#2454]
trying to run `rake artifact:tar` after successful `rake bootstrap`

Installing logstash-codec-rubydebug 0.1.4
with native extensions
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension
.

    C:/logstash/vendor/jruby/bin/jruby.exe extconf.rb

make
'make' is not recognized as an internal or external command,
operable program or batch file.

Gem files will remain installed in C:/logstash/vendor/bundle/jruby/1.9/gems/murm
urhash3-0.1.5 for inspection.
Results logged to C:/logstash/vendor/bundle/jruby/1.9/gems/murmurhash3-0.1.5/ext
/murmurhash3/gem_make.out
An error occurred while installing murmurhash3 (0.1.5), and Bundler cannot conti
nue.
Make sure that `gem install murmurhash3 -v '0.1.5'` succeeds before bundling.
--> Retrying vendor:gems upon exception=Bundler::InstallError
Fetching source index from https://rubygems.org/

**Comment by wiibaa** [comment]
@suyograo did you retest since the major update to the Gemfile.lock by Jordan, 
murmurhash was updated to 0.1.6-java, I suppose it should solve this issue.
https://github.com/elasticsearch/logstash/commit/b044906ea57036dbd3bf06f50cee7dbf4e00df26#diff-bbbdce75bfca1095e2a02ac8cf3d6f38L458

**Comment by jsvd** [comment]
Runs ok on my windows machine since 0.1.6:

```
...
Installing logstash-codec-oldlogstashjson 0.1.4
Installing logstash-codec-plain 0.1.4
Installing logstash-codec-rubydebug 0.1.5
Installing murmurhash3 0.1.6
Installing logstash-filter-anonymize 0.1.3
Installing logstash-filter-checksum 0.1.4
Installing logstash-filter-clone 0.1.3
Installing logstash-filter-csv 0.1.3
Installing logstash-input-generator 0.1.2
Installing logstash-output-null 0.1.2
Installing logstash-filter-date 0.1.3
...
```

**Comment by suyograo** [comment]
tested, can't reproduce after 0.1.6
