### ISSUE TITLE
All plugins need to be tested automatically

### ISSUE THREAD

**Issue by jordansissel** [elasticsearch/logstash#2465]
At present, it appears that none of the plugin tests are being run by jenkins.

Here's a sample screenshot showing that the last 2 months we haven't run a set of filter tests. This pattern repeats for nearly all plugin jobs in Jenkins.

![screen shot 2015-01-28 at 8 58 01 am](https://cloud.githubusercontent.com/assets/131818/5942363/dc19a8ea-a6cb-11e4-9000-f3f7b43e70ff.png)

**Comment by electrical** [comment]
This is because the Github hook isn't enabled yet.

**Comment by purbon** [comment]
The github hook was added manually a few days ago, from now on every push to the git repo will trigger a test.

Working on having at least one complete run on every project.

**Comment by purbon** [comment]
The Github hook has been added to all the plugins and now every push will trigger a test job. I also made sure to run one time all plugins so their test suit is up to date.

**Comment by purbon** [comment]
There are however a list of plugins still not tested in the Jenkins infra:

```
  1 > logstash-codec-avro
  2 > logstash-codec-cef
  3 > logstash-filter-metricize
  4 > logstash-filter-oui
  5 > logstash-filter-tld
  6 > logstash-filter-yaml
  7 > logstash-input-heartbeat
  8 > logstash-input-jms
  9 > logstash-output-jms
```

**Comment by electrical** [comment]
Because they are new.

**Comment by purbon** [comment]
All currently testable plugins are now in Jenkins with regular test jobs executions after a PR is merge into master (git push command). So all plugins are going to be tested automatically each time there is some change.
