### ISSUE TITLE
Improve the package tests to test the tar and zip artifacts

### ISSUE THREAD

**Issue by jordansissel** [elasticsearch/logstash#2466]
At present, the package acceptance tests only appear to test the .deb and .rpm. We need to also test the .tar.gz and .zip.

**Comment by electrical** [comment]
No functionality in the puppet module to support this.

**Comment by jordansissel** [comment]
That's ok, we can test without puppet.

**Comment by jordansissel** [comment]
We'll want to simulate how humans do the installation anyway, so a few tests mimicking this will be useful.

**Comment by electrical** [comment]
http://build-eu-00.elasticsearch.org/view/LS%201.5/job/Logstash_Tarball_Acceptance_1.5/
http://build-eu-00.elasticsearch.org/view/LS%20Master/job/Logstash_Tarball_Acceptance_Master/

Want to have a job for the zip artifacts as well?

**Comment by jordansissel** [comment]
Yep! Need zip for windows support.

**Comment by electrical** [comment]
http://build-eu-00.elasticsearch.org/view/LS%20Master/job/Logstash_Zip_Acceptance_Master/
http://build-eu-00.elasticsearch.org/view/LS%201.5/job/Logstash_Zip_Acceptance_1.5/

**Comment by electrical** [comment]
All done.
