### ISSUE TITLE
Add monitoring to critical jenkins jobs

### ISSUE THREAD

**Issue by jordansissel** [elasticsearch/logstash#2468]
As noted in https://github.com/elasticsearch/logstash/issues/2465, we haven't been running plugin tests in at least 2 months.

We need monitoring to alert us when this kind of thing occurs. We should be paged if Jenkins isn't running tests.

**Comment by electrical** [comment]
Everything could be considered critical. We just need to make sure we enable the correct triggers for them.

**Comment by jordansissel** [comment]
> Everything could be considered critical

We agree :)

**Comment by purbon** [comment]
Working the tooling necessary to have this done.

**Comment by purbon** [comment]
All testing jobs in Jenkins have now a post build task that send email monitoring when a job was not successful.
