### ISSUE TITLE
File dependencies and the gem.hook

### ISSUE THREAD

**Issue by ph** [elasticsearch/logstash#2472]
The plugin manager actually invoke the `Gem.hook` of the plugin to download the vendor files.
I know we did some experimentation to remove the need for this call but I do not recall the blocker on this. I want to know if we can be closer to the jar-dependencies behaviour and make it work like magic.

If we cannot make it work like the jar-dependencies we will have to rely on a rake task after installing the gems with bundler.

**Comment by electrical** [comment]
The only reason it works magical is that we include the file that defines the hook.
I just made it in such a way that it can be called when we want it.

**Comment by electrical** [comment]
See https://github.com/elasticsearch/logstash/blob/master/lib/logstash/pluginmanager/install.rb#L9

**Comment by purbon** [comment]
This was actually not a problem. If we've file-dependecies installed before we get to run bundler, thanks to https://github.com/electrical/file-dependencies/blob/master/lib/rubygems_plugin.rb, all plugins that have a proper way to load vendored files (vendor.json), will trigger the download process.

**Comment by purbon** [comment]
I removed the blocker label as this is not blocking us to move forward. Vendor files are installed properly with ```bin/plugin install``` or with bundler.

**Comment by ph** [comment]
working
