### ISSUE TITLE
10-minute Tutorial wrong config file

### ISSUE THREAD

**Issue by thordy** [elasticsearch/logstash#2482]
I was going through the [10-minute Tutorial](http://www.logstash.net/docs/1.4.2/tutorials/10-minute-walkthrough/) and got to Step-5, which uses [the following configuration file](http://www.logstash.net/docs/1.4.2/tutorials/10-minute-walkthrough/apache-parse.conf) which references `debug => true` in the output section.

When trying to run the code `bin/logstash agent -f apache-parse.conf`, I get the following error

    Unknown setting 'debug' for stdout {:level=>:error}
    Error: Something is wrong with your configuration.
    You may be interested in the '--configtest' flag which you can
    use to validate logstash's configuration before you choose
    to restart a running system.

I am assuming this should be updated to use `codec => rubydebug` instead ?

**Comment by untergeek** [comment]
You are correct about that (sorry for the inconvenience).  The 10-minute tutorial is going away for 1.5.  See the current documentation at http://www.elasticsearch.org/guide/en/logstash/current/index.html, particularly the [Getting Started With Logstash](http://www.elasticsearch.org/guide/en/logstash/current/logstash-reference.html) link.

**Comment by acro5piano** [comment]
↑ now the link moved to https://www.elastic.co/guide/en/logstash/current/advanced-pipeline.html

**Comment by lnunno** [comment]
FYI this setting is still present in the sqlite plugin docs here: https://www.elastic.co/guide/en/logstash/current/plugins-inputs-sqlite.html#_description_36
