### ISSUE TITLE
SYSLOG5424SD format crashes logstash at startup

### ISSUE THREAD

**Issue by wsw70** [elasticsearch/logstash#2483]
I am matching events such as

    [Sun Jan 11 10:43:35 2015][3205.51466981] user idp : testing 10.234.22.220 (10.234.22.220) [61673782]

with

    %{SYSLOG5424SD:timestamp}%{GREEDYDATA}user %{WORD:user} : testing %{HOST:ip}

It works, I see the various fields in elasticsearch/kibana. Specifically `timestamp` in the example above is matched with `[Sun Jan 11 10:43:35 2015]`

I now would like to use this match with `date` in order to have the right `@timestamp`.

I tried to use in `filter`

        date
        {
          match =>  [ "timestamp", "SYSLOG5424SD" ]
        }

but this crashes logstash hinting a bug.

The last line before the crash:

```
Grok compile {:field=>"message", :patterns=>["%{SYSLOG5424SD:timestamp}%{GREEDYDATA}user %{WORD:user} : testing %{HOST:ip}", "%{SYSLOG5424SD:timestamp}%{GREEDYDATA}Finished testing %{HOST:ip}. Time : %{NUMBER:time} secs", "%{SYSLOG5424SD:timestamp}%{GREEDYDATA}The remote host \\(%{HOST:ip}\\) is dead"], :level=>:info}
```

The reported error:

```
The error reported is:
  Illegal pattern component: L
```

**Comment by magnusbaeck** [comment]
I responded to this question in the [original StackOverflow thread](http://stackoverflow.com/questions/28239972/how-to-debug-the-matching-of-the-date). What could be added here is that the reason for the seemingly weird error message ("Illegal pattern component: L") is that "L" happens to be the first character in "SYSLOG5424SD" that isn't a vaild Joda-Time pattern letter.

**Comment by wsw70** [comment]
@magnusbaeck : you are correct, the change you suggested works.

Since I got an output after the crash which suggested to file a bug report, it would probably be good to address that message. This said, this is not a bug
