### ISSUE TITLE
logstash timezone

### ISSUE THREAD

**Issue by techbobo** [elasticsearch/logstash#2489]
How can I auto create index with UTC+8.
Thanks.

**Comment by markwalkom** [comment]
Indices aren't created with a TZ, it's left to the client to deal with differences.

Make sure you use the date filter to set your TZ :)

**Comment by techbobo** [comment]
The output of date filter, always is UTC time. How convert UTC to other TZ?
Thanks.

**Comment by markwalkom** [comment]
It will always be UTC. If you are using Kibana, it will handle the conversion to local time.

**Comment by techbobo** [comment]
Thank you very much.
