### ISSUE TITLE
Retire `bin/logstash web` when Kibana 4 is released

### ISSUE THREAD

**Issue by jordansissel** [elasticsearch/logstash#2494]
Related: https://github.com/elasticsearch/kibana/pull/2574

The kibana 4 backend is now in nodejs. Given that Kibana 4 now uses a backend supported by the nice folks on the Kibana team, I don't think we need to ship with `bin/logstash web` anymore.

**Comment by untergeek** [comment]
+1,000,000 this!!!

**Comment by purbon** [comment]
amen to that! +1 on retire.

**Comment by rashidkpc** [comment]
++

**Comment by suyograo** [comment]
@untergeek we can remove this for LS RC1

**Comment by suyograo** [comment]
Fixed via https://github.com/elasticsearch/logstash/pull/2661
