### ISSUE TITLE
The dns filter (dns.rb) produces a lot of SocketError messages  for reverse lookups

### ISSUE THREAD

**Issue by emmitux** [elasticsearch/logstash#2499]
We are using the dns filter in logstash quite heavily to do a reverse lookup for the IP of every incoming log message. We get a lot of "DNS: Encountered SocketError" errors. The SocketError object contains the message "bind: name or service not known".

The IPs the reverse lookups are done for are all properly registered in our DNS and most of the time the dns filter can successfully make the reverse lookup. Running tcpdump I could not find any problems on the network layer while the SocketError in the dns filter appeared. 

The volume of messages and hence of reverse lookups per 24h is roughly 7.3 millions, of which are  700 thousand socket errors.

Some more information about our environment:

Enterprise Linux 6.6 with nscd running. Turning nscd on/off doesn't change anything. We also changed the JVM dns caching from completely off to infinite. No effects either.

**Comment by emmitux** [comment]
Some more information to our environment:

Enterprise Linux 6.6 with nscd running. Turning nscd on/off doesn't change anything. We also changed the JVM dns caching from completely off to infinite. No effects either.

**Comment by untergeek** [comment]
Plugins reside in their own repositories now.  Can you please close this and re-open at https://github.com/logstash-plugins/logstash-filter-dns ?

Thanks.

**Comment by emmitux** [comment]
Re-opened at  https://github.com/logstash-plugins/logstash-filter-dns
