### ISSUE TITLE
Make sure mixin type of plugins cannot be installed

### ISSUE THREAD

**Issue by suyograo** [elasticsearch/logstash#2503]
We use a "mixin" plugin to share common code between multiple plugins (to DRY). For example, the AWS S3 input and output plugins use [logstash-mixin-aws](https://github.com/logstash-plugins/logstash-mixin-aws).  which is a gem but not a Logstash plugin. 

We need to enforce that `bin/plugin install` cannot actually install this as a plugin. This should only be installed as a dependency when installing `logstash-input-s3`.

**Comment by suyograo** [comment]
We could achieve this by hopefully just setting `logstash_plugin` to `false` in the `.gemspec` and enforcing it on the Logstash core side

**Comment by electrical** [comment]
Not setting `logstash_plugin` is more then enough..  no need to set it to false.
Its already handled in the plugin manager.

**Comment by suyograo** [comment]
@electrical perfect. I'll move this to the mixins repo and close this

**Comment by purbon** [comment]
As @electrical said, enough to remove the logstash plugin metadata from this gems. Another thing is then to handle this stuff with the Bundler improvements @colinsurprenant and @ph are working on.
