### ISSUE TITLE
Cannot start logstash 1.5.beta1 on windows

### ISSUE THREAD

**Issue by nabheet** [elasticsearch/logstash#2504]
OS = Windows Server 2012 R2 Standard 64-bit
 
C:\logstash>bin\logstash.bat agent -vv --config c:\logstash\conf.d
Please download the JRuby Complete .jar from http://jruby.org/download to C:\log
stash\vendor\jar\ and re-run this command.
Press any key to continue . . .

Then I copied the jruby from https://s3.amazonaws.com/jruby.org/downloads/1.7.19/jruby-complete-1.7.19.jar ... to C:\logstash\vendor\jar

C:\logstash>java -version
java version "1.7.0_75"
Java(TM) SE Runtime Environment (build 1.7.0_75-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.75-b04, mixed mode)

C:\logstash>bin\logstash.bat agent -vv --config c:\logstash\conf.d
io/console not supported; tty will not be manipulated
The error reported is:
  bad URI(is not URI?): c:\logstash\conf.d
/C:/logstash/vendor/jar/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/uri/common.rb:176:in `split'
/C:/logstash/vendor/jar/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/uri/common.rb:210:in `parse'
/C:/logstash/vendor/jar/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/uri/common.rb:747:in `parse'
C:/logstash/lib/logstash/agent.rb:291:in `load_config'
C:/logstash/lib/logstash/agent.rb:101:in `execute'
C:\logstash\lib\logstash\runner.rb:166:in `run'
org/jruby/RubyProc.java:271:in `call'
C:\logstash\lib\logstash\runner.rb:171:in `run'
org/jruby/RubyProc.java:271:in `call'
C:/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.18/lib/stud/task.rb:12:in `initialize'

**Comment by jordansissel** [comment]
This is being fixed for 1.5.0

**Comment by ph** [comment]
I have to make another PR for this the bug still exist in the master branch.
