### ISSUE TITLE
output file doesn't work correctly on logstash 1.5 beta1

### ISSUE THREAD

**Issue by jindov** [elasticsearch/logstash#2517]
This is my configuration in output.conf

output {
....
file { path => "/var/log/test-%{+YYYY-MM-dd}.log" }
...
}

but it hasn't created a valid file with the above time format (I need rotation log), it's created test-/_filepath_failures, this configuration was still used normally in logstash 1.4. 

format of "@timestamp"=>"2015-02-05T17:19:27.456Z"

**Comment by ph** [comment]
This should be fixed in the latest version of the plugin, related issue:
https://github.com/logstash-plugins/logstash-output-file/issues/3
