### ISSUE TITLE
Logstash is loosing lines/events when it terminates

### ISSUE THREAD

**Issue by driegel** [elasticsearch/logstash#2521]
I got a logdata.json file that contains log events. I believe this bug is generic and doesn't depend on the input file format.

I tested this behaviour (again) with logstash 1.5.0.beta1 and Oracle Java 1.8.0_31-b13 64-bit, however, I believe it does not depend on the Java version. Also, I noticed similar logstash behaviour in version 1.4.2 and I believe it's the same problem.

I count the events the of the input file with
wc logdata.json

Then I check the number of imported documents in ElasticSearch with /index/_search 

..........
1. cat logdata.json | logstash -f <config>
```
input {
        stdin {
                codec => json
        }
}

output {
        elasticsearch { 
               protocol => "http"
               host => "localhost"
               workers => 2
               index => "logdata-%{+YYYY.MM}"
       }
}
```
Counting events after the import, I notice that there are some 1000 events/documents missing! If I am using more than one worker, more documents get lost. (One worker is the best case.)

..........
2. logstash -f <config> &
cat logdata.json | ncat localhost 10000
```
input {
        tcp {
                codec => json
                port => 10000
        }
}

output {
        elasticsearch { 
               protocol => "http"
               host => "localhost"
               workers => 2
               index => "logdata-%{+YYYY.MM}"
       }
}
```
Counting events after the import, the number of lines in the JSON file is identical to the number of events in ElasticSearch. It is possible to use multiple workers.

Also, it is possible to use redis input plug-in, all events make it.

..........

Suspected reason/bug:
When we use stdin as input, logstash terminates immediately after the input file is fully read.

When we use tcp or redis as input, logstash reads all available events but does not terminate until it gets killed. 

http://www.elasticsearch.com/guide/en/logstash/current/plugins-outputs-elasticsearch.html describes the options flush_size and idle_flush_time. That means, by default each elasticsearch output worker maintains a queue of up to 5000 elements, however, it will be flushed or written to elasticsearch after 1 second of inactivity. That makes the difference between logstash terminating immediately or continuing to listen for input.

Questions:
1. Does the elasticsearch output flush it's queue when logstash terminates?
2. Does stdin input terminate logstash without the possibility to flush event queues?

I feel that question 1 describes the reason for this logstash behavior, however, it would be good to investigate other output plugins as well.

**Comment by jordansissel** [comment]
There specifically is a bug where you set `workers => N` where N > 1 in Elasticsearch output and a normal termination of Logstash mistakenly does not tell each worker to flush. This has been fixed in d6cb066e038d53fd2bdb47c0c05487b929aab801 (related: #2180)

**Comment by jordansissel** [comment]
Logstash 1.5.0 beta1 should have this patch, I think, but if not RC1 and GA will.

**Comment by jordansissel** [comment]
The workaround for now is to set `workers => 1` and this problem will not occur.

**Comment by driegel** [comment]
Thank you for looking into it. It certainly did happen w/ 1.5.0 beta1 and _one_ worker only. Using 2 workers increases the bulk import speed from 4000 events/sec to 7000 event/sec.

Unfortunately the workaround for setting workers => 1 does not work, However, I agree that the upcoming patch should solve the problem :-) For now I will continue to use the workaround of using the TCP input instead of STDIN.
