### ISSUE TITLE
[doc] Plugins installed from beta1 are not recognised by the new bundler solution

### ISSUE THREAD

**Issue by suyograo** [elasticsearch/logstash#2553]
I had plugins installed using `bin/plugin install` from beta1 release. I switched branches to test the https://github.com/elasticsearch/logstash/tree/wip/bundler-move and tried to uninstall an existing plugin. Plugins were not recognised because they are not listed in `Gemfile`

```
suyog@machine:~/ws/logstash (pr/2475)$ bin/plugin uninstall logstash-output-zeromq
This plugin has not been previously installed, aborting
suyog@machine:~/ws/logstash (pr/2475)$ bin/plugin list | grep zeromq
logstash-filter-zeromq (0.1.3)
logstash-input-zeromq (0.1.2)
logstash-output-zeromq (0.1.2)
```

Users upgrading from beta1 to RC1 will hit this issue too

**Comment by suyograo** [comment]
From our internal hipchat discussion with @jordansissel @ph and @colinsurprenant, this upgrade path should be documented in the release notes

```
bin/plugin list | sed -e 's/.*/gem "\1"/' > Gemfile
```

**Comment by colinsurprenant** [comment]
should we put this as blocker for RC1?

**Comment by colinsurprenant** [comment]
I reworked `bin/plugin list` in 2ed31233dfb88f55fa15d0b3ed05c4cd9f673090 to show all local plugin gems and only list bare names by default. this will allow us to either do 
```sh
bin/plugin list | sed -e 's/\(.*\)/gem "\1"/' > Gemfile
```

or even better:

```sh
bin/plugin install --no-verify `bin/plugin list | tr "\\n" " "`
```

since the plugin gems are already installed this operation is very fast and does not expose the Gemfile to the end-user.

**Comment by colinsurprenant** [comment]
I did not test since the `logstash-core` refactor but I think beta1 to rc1 migration is now doomed. /cc @purbon

**Comment by purbon** [comment]
@colinsurprenant actually they will not work, as there is no logstash.gemspec file (including dependencies on him). ..... the question here is, do we want to have this file (or something in the code base) to have backwards compatibility? I guess so.

- purbon

**Comment by purbon** [comment]
@colinsurprenant Analyzing what is necessary to have backwards compatibility, but not sure if this even makes sense, is some who played with 1.5-beta1 not able to use something named 1.5-rc1 ? or even newer?

**Comment by purbon** [comment]
If we aim to let people install old plugins in new ```1.5-rc1``` we should provide a ```logstash.gemspec``` that contains the necessary dependencies (now it's there, but without dependencies). Then this plugins are able to be installed as they require a reference to this as specified on their Gemfile.

Looking forward to your thoughts on this.

**Comment by colinsurprenant** [comment]
@purbon @suyograo I am not sure it is super important to have beta1 compatibility... since most plugins are packaged anyway. it would break for new plugin installs/upgrade from a beta1. we just have to tell our users to do a fresh install of RC1 ?

**Comment by suyograo** [comment]
@colinsurprenant @purbon yes, I am ok with that.

**Comment by colinsurprenant** [comment]
ok, so let's close this?
