### ISSUE TITLE
Install plugins message messing with bundler warning (messaging problem)

### ISSUE THREAD

**Issue by purbon** [elasticsearch/logstash#2565]
Hi,
  if you install a plugin it outputs the next message

```
➜  logstash git:(wip/bundler-move) ✗ ./bin/plugin install logstash-filter-clone
Validating logstash-filter-clone
Installing logstash-filter-clone
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

it would be great if we can hide somehow this bundler gemspec warnings, they don't really provide a relevant message to the issue of installing the plugin here. Might be misleading for some people.

**Comment by suyograo** [comment]
@purbon related to https://github.com/elasticsearch/logstash/issues/2556 which is an upstream issue

**Comment by suyograo** [comment]
Closing this.

**Comment by ph** [comment]
you are too fast @suyograo

**Comment by purbon** [comment]
ok! thanks!
