### ISSUE TITLE
Kibana 4 Beta 3 Version Conflict

### ISSUE THREAD

**Issue by jsirex** [elasticsearch/logstash#2570]
I've setup Kibana 4 beta 3, Elasticsearch 1.4.2.

Then I've setup logstash 1.4.2 and output 'elasticsearch'

I see that output is connected to elasticsearch and I can see one more node in elasticsearch cluster.

But kibana throws exception that version of elasticsearch is wrong (1.1.1)

**Comment by talevy** [comment]
Logstash 1.4.2 release is bundled with the Elasticsearch 1.1.1 client library.

You may want to try Logstash 1.5 Beta, which comes with a more up-to-date version of Elasticsearch

see version defined here: https://github.com/elasticsearch/logstash/blob/v1.4.2/Makefile#L6

does that answer your question?

**Comment by jsirex** [comment]
Didn't notice 1.5 Beta. Thank you. Will try it.

**Comment by jordansissel** [comment]
As an alternative, you can use http (meaning: `elasticsearch { protocol => http ... }`) in your elasticsearch output and it works around this issue.
