### ISSUE TITLE
mem leak in lumberjack input - logstash 1.5.0 beta1

### ISSUE THREAD

**Issue by seventy-7** [elasticsearch/logstash#2585]
Hi,

I am experiencing an increasing Mem usage and thread count.

Some info on setup:

15-20 logstash forwarders, connection directly to 1 logstash. The 1 logstash has 2 outputs, 1 elasticsearch and 1 to redis and all run on the same server.

There is a pic from jconsole
![1](https://cloud.githubusercontent.com/assets/10955247/6143899/2a57f198-b20b-11e4-9309-0e211fe92925.png)

The high majority of the threads are associated with lumberjack. I have the stacktrace from one of these threads, I also have a threaddump from the whole process. 

http://www.outtalimits.com.au/stack
http://www.outtalimits.com.au/heap.dmp [729M]

Let me know if you need any more info on this.

Cheers!

**Comment by seventy-7** [comment]
This looks to be purely a resource issue. I have the host server was a VM with a 2 CPU count. I increased that to 8 and the issue is gone. Marking this as closed.

![2](https://cloud.githubusercontent.com/assets/10955247/6180538/51f49830-b361-11e4-9c3e-aff93c572b77.png)

**Comment by suyograo** [comment]
thanks for the update @seventy-7

**Comment by seventy-7** [comment]
Looks like I spoke too soon :(

![3](https://cloud.githubusercontent.com/assets/10955247/6180620/8188c840-b362-11e4-8948-cf8b492a0bde.png)


It does feel like logstash can't handle the amount of incoming data though. Or maybe the bottleneck is on elasticsearch causing logstash to back up?

Any way i can check this?

**Comment by seventy-7** [comment]
I am also seeing an ever growing amount of CLOSE_WAIT connections.
This looks related https://logstash.jira.com/browse/LOGSTASH-1253

**Comment by seventy-7** [comment]
I have been able to overcome this issue by scaling out logstash into multiple daemons. From reading some comments on related issues it would seem the cause is slowness in the event pipeline which causes these reconnections. 

I'll keep this issue open for a couple more days to monitor before closing.
