### ISSUE TITLE
Cannot specify Elasticsearch cluster name in Logstash config 

### ISSUE THREAD

**Issue by vedaprasad** [elasticsearch/logstash#2589]
I have a single Node (ec2-instance) which runs ES , i have plans to add couple of more instance and make it a Cluster , However i am not finding a way to let my Logstash know that its a ES cluster and not a single node as i specify with (host => "IP Address") in output ES Plugin   . Below is my Conf file 

[ec2-user@ip-10-10-43-111 ~]$ grep -v ^# /etc/logstash/conf.d/logstash.conf
input {
  redis {
     data_type =>  "list"
     host => "elk-cluster.xxxxxxxxxx"
     key => "logstash"
  }
}

output {
  elasticsearch {
     action =>  "index"
     cluster => "ELK-Cluster1"
     host => "10.10.43.121"
     index =>  "logstash-%{+YYYY.MM.dd}"
  }
}

**Comment by suyograo** [comment]
@vedaprasad When you add more nodes to Elasticsearch cluster, it does not matter which node LS is talking to. All nodes in elasticsearch cluster share the same cluster name. You can scale your ES cluster without changing the configuration of LS.

**Comment by vedaprasad** [comment]
Thanks @suyograo
