### ISSUE TITLE
Logstash 1.5.0.beta1 RPM ignores patterns in /opt/logstash/patterns/

### ISSUE THREAD

**Issue by oernii** [elasticsearch/logstash#2592]
After symlinking /opt/logstash/patters to /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-patterns-core-0.1.2/patterns it began to work.

**Comment by jsvd** [comment]
fixed in https://github.com/logstash-plugins/logstash-filter-grok/pull/5, it will be solved in rc1

**Comment by jsvd** [comment]
but thanks for reporting :)

**Comment by oernii** [comment]
thx
