### ISSUE TITLE
Latest version of ruby-maven makes the `bundle install` fails

### ISSUE THREAD

**Issue by ph** [elasticsearch/logstash#2595]
Currently there is a blocking issue with the latest (3.1.1.0.9) version of `ruby-maven` and installing jars dependencies. If you are declaring a gem  in a gemfile  using the :github option it will make the bundle install crash, before upgrading this gem you need to test the version with any plugins that require jars.

Related issue and the stracktrace in https://github.com/logstash-plugins/logstash-input-kafka/issues/21

**Comment by colinsurprenant** [comment]
this is fixed now right?
