### ISSUE TITLE
Monkey patch for bugs isn't applied when testing a plugin from its repo

### ISSUE THREAD

**Issue by jsvd** [elasticsearch/logstash#2597]
Since https://github.com/elasticsearch/logstash/pull/2507 loads the "monkeypatches-for-bugs.rb" file in the runner.rb, when testing a plugin's spec file from its repo the runner is never loaded, hence the patch isn't applied.

Proposal: require the monkeypatch from pipeline.rb, event.rb or plugin.rb

**Comment by ph** [comment]
Event and plugin are probably the best candidate here, if we want minimal changes.
Maybe we should create a bootstrap.rb that require the miminal classes and use that for the system entry point? (bootstrap is probably a bad name)

**Comment by ph** [comment]
We dont really have a 'main' file for our requires maybe it is the time ?

**Comment by jsvd** [comment]
there's a lib/logstash/logstash.rb but we might not want to load it there, since some plugins won't need agent.rb for example

**Comment by ph** [comment]
fixed in https://github.com/elasticsearch/logstash/pull/2668

**Comment by ph** [comment]
`Environment.rb` is loaded in plugins test 
https://github.com/elasticsearch/logstash-devutils/blob/master/lib/logstash/devutils/rspec/spec_helper.rb#L16

**Comment by suyograo** [comment]
Fixed via https://github.com/elasticsearch/logstash/pull/2668
