### ISSUE TITLE
Map Disappearing 

### ISSUE THREAD

**Issue by Israaaaa** [elasticsearch/logstash#2599]
Im using Logstash 1.4.2, Elasticsearch 1.4.2 and Kibana4 
This is my conf logstash file

input { stdin {} }
filter { geoip {  source => "ip"    }}
output {  elasticsearch {  host => "localhost" } }

When I check the Elasticsearch head plugin, I can see that the logs I have indexed, which are 6 logs, are now stored in the index logstash-date and that index contains 6 documents

However, I cannot view these documents on Kibana. Furthermore, when I create a tile map, and then choose the coordinates to be geoip.location (I choose this field, which exists, which probably tells me that the logs are indexed properly because Logstash had managed to  create that field from the ip address), and after I hit 'Apply' the map disappears. No points are returned, not even a map. 

Is this an issue with Logstash, Kibana or Elasticsearch? What am I doing wrong?

Please note that I have indexed from MongoDB some logs into Elasticsearch and successfully viewed them in Kibana. So maybe the problem is with Logstash.

Thank you.

**Comment by untergeek** [comment]
I can't speak to the map behavior yet, but the `geoip` filter internally takes the `longitude` and `latitude` fields and creates a field called `location` (`geoip.location`) which is a GeoJSON object.  The configuration you have above will do this with Logstash 1.4.2

If you're using the Elasticsearch template bundled with Logstash—which is the default behavior—Elasticsearch will map the `geoip.location` field as type geopoint. I don't believe the `geoip` filter creates a `geoip.coordinates` field.  It won't be there unless you do some funky work with mutate filters, an example of which is here: https://redmine.openinfosecfoundation.org/projects/suricata/wiki/_logstash_kibana_and_suricata_json_output

Are you using the map panel type, or bettermap?  The bettermap panel is the one that uses a GeoJSON object type.

**Comment by Israaaaa** [comment]
@untergeek Im terribly sorry, I did mean to say that the field created was geoip.location and not geoip.coordinates. 

I'm using Kibana4, and it appears there is only one type of maps which is the bettermap (called tile map here) and it uses the GeoJSON object type.

**Comment by untergeek** [comment]
If you can't see the documents in Kibana, the map won't be able to see the field either.  Let's find out why Kibana doesn't see your 6 entries first.

**Comment by Israaaaa** [comment]
Is there any specific information you would like me to provide in order to try figure out why Kibana4 cannot see the 6 entries?

**Comment by untergeek** [comment]
If you only have 6, what index are they in?  Anyway, you should be able to do a query like:

```
curl -XGET 'localhost:9200/_search?q=*&pretty
```

And see all six documents.  Paste the result in here for a start.

**Comment by Israaaaa** [comment]
The Elasticsearch Head Plugin shows that I have indexed two indices, one that comes from MongoDB and Kibana is able to view it. This index is called mongoindex and contains 154,270 documents. The second index would be the one coming from Logstash, containing the 6 documents. 
The other two indices would be .kibana and _river

This is the results for the command:
curl -XGET "localhost:9200/_search?q=*&pretty"

{
  "took" : 24,
  "timed_out" : false,
  "_shards" : {
    "total" : 12,
    "successful" : 12,
    "failed" : 0
  },
  "hits" : {
    "total" : 154287,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : ".kibana",
      "_type" : "visualization",
      "_id" : "top-10-asn",
      "_score" : 1.0,
      "_source":{"title":"top 10 asn","visState":"{\"type\":\"area\",\"params\":{\"shareYAxis\":true,\"addTooltip\":true,\"addLegend\":true,\"mode\":\"stacked\"},\"aggs\":[{\"id\":1,\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":2,\"type\":\"terms\",\"schema\":\"segment\",\"params\":{\"field\":\"asn\",\"size\":10,\"order\":\"desc\",\"exclude\":{\"flags\":[]},\"include\":{\"flags\":[]}}}],\"listeners\":{}}","description":"","kibanaSavedObjectMeta":{"searchSourceJSON":"{\"index\":\"mongoindex\",\"query\":{\"query_string\":{\"query\":\"*\"}},\"filter\":[]}"}}
    }, {
      "_index" : ".kibana",
      "_type" : "index-pattern",
      "_id" : "logstash-*",
      "_score" : 1.0,
      "_source":{"title":"logstash-*","customFormats":"{}","fields":"[{\"type\":\"string\",\"indexed\":true,\"analyzed\":true,\"doc_values\":false,\"name\":\"host\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":false,\"analyzed\":false,\"name\":\"_source\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":false,\"doc_values\":false,\"name\":\"message.raw\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":false,\"analyzed\":false,\"name\":\"_index\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":false,\"doc_values\":false,\"name\":\"@version\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":true,\"doc_values\":false,\"name\":\"message\",\"count\":0,\"scripted\":false},{\"type\":\"date\",\"indexed\":true,\"analyzed\":false,\"doc_values\":false,\"name\":\"@timestamp\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":false,\"name\":\"_type\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":false,\"analyzed\":false,\"name\":\"_id\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":false,\"doc_values\":false,\"name\":\"host.raw\",\"count\":0,\"scripted\":false},{\"type\":\"geo_point\",\"indexed\":true,\"analyzed\":false,\"doc_values\":false,\"name\":\"geoip.location\",\"count\":0,\"scripted\":false}]"}
    }, {
      "_index" : ".kibana",
      "_type" : "config",
      "_id" : "4.0.0-beta3",
      "_score" : 1.0,
      "_source":{"defaultIndex":"logstash-*"}
    }, {
      "_index" : "_river",
      "_type" : "mongodb",
      "_id" : "_meta",
      "_score" : 1.0,
      "_source":{
    "type": "mongodb", 
    "mongodb": { 
"db": "collective_intel",
        "collection": "ips_test"
    }, 
    "index": { 
      "name": "mongoindex",
      "type": "mongodb"
    }
}
    }, {
      "_index" : "_river",
      "_type" : "mongodb",
      "_id" : "collective_intel.ips_test",
      "_score" : 1.0,
      "_source":{"mongodb":{"_last_ts":"{ \"$ts\" : 1423637351 , \"$inc\" : 1}"}}
    }, {
      "_index" : "_river",
      "_type" : "mongocc",
      "_id" : "_meta",
      "_score" : 1.0,
      "_source":{
    "type": "mongodb", 
    "mongodb": { 
     "db": "cc",
        "collection": "cc_data"
    }, 
    "index": { 
      "name": "mongoindexcc"
    }
}
    }, {
      "_index" : "_river",
      "_type" : "mongocc",
      "_id" : "cc.cc_data",
      "_score" : 1.0,
      "_source":{"mongodb":{"_last_ts":"{ \"$ts\" : 1423637351 , \"$inc\" : 1}"}}
    }, {
      "_index" : "_river",
      "_type" : "mongocc",
      "_id" : "_riverstatus",
      "_score" : 1.0,
      "_source":{"mongodb":{"status":"START_FAILED"}}
    }, {
      "_index" : "_river",
      "_type" : "mongodb",
      "_id" : "_riverstatus",
      "_score" : 1.0,
      "_source":{"mongodb":{"status":"START_FAILED"}}
    }, {
      "_index" : "_river",
      "_type" : "mongodb",
      "_id" : "_status",
      "_score" : 1.0,
      "_source":{"node":{"id":"S5Xs5aBQRyK7A76GTa57tQ","name":"Gideon","transport_address":"inet[/72.52.190.7:9300]"}}
    } ]
  }
}

**Comment by Israaaaa** [comment]
The Elasticsearch Head Plugin shows that I have indexed two indices, one that comes from MongoDB and Kibana is able to view it. This index is called mongoindex and contains 154,270 documents. The second index would be the one coming from Logstash, containing the 6 documents. 
The other two indices would be .kibana and _river


This is the results for the command:
curl -XGET "localhost:9200/_search?q=*&pretty"

{
"took" : 24,
"timed_out" : false,
"_shards" : {
"total" : 12,
"successful" : 12,
"failed" : 0
},
"hits" : {
"total" : 154287,
"max_score" : 1.0,
"hits" : [ {
"_index" : ".kibana",
"_type" : "visualization",
"_id" : "top-10-asn",
"_score" : 1.0,
"_source":{"title":"top 10 asn","visState":"{\"type\":\"area\",\"params\":{\"shareYAxis\":true,\"addTooltip\":true,\"addLegend\":true,\"mode\":\"stacked\"},\"aggs\":[{\"id\":1,\"type\":\"count\",\"schema\":\"metric\",\"params\":{}},{\"id\":2,\"type\":\"terms\",\"schema\":\"segment\",\"params\":{\"field\":\"asn\",\"size\":10,\"order\":\"desc\",\"exclude\":{\"flags\":[]},\"include\":{\"flags\":[]}}}],\"listeners\":{}}","description":"","kibanaSavedObjectMeta":{"searchSourceJSON":"{\"index\":\"mongoindex\",\"query\":{\"query_string\":{\"query\":\"\"}},\"filter\":[]}"}}
}, {
"_index" : ".kibana",
"_type" : "index-pattern",
"_id" : "logstash-",
"_score" : 1.0,
"_source":{"title":"logstash-","customFormats":"{}","fields":"[{\"type\":\"string\",\"indexed\":true,\"analyzed\":true,\"doc_values\":false,\"name\":\"host\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":false,\"analyzed\":false,\"name\":\"_source\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":false,\"doc_values\":false,\"name\":\"message.raw\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":false,\"analyzed\":false,\"name\":\"_index\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":false,\"doc_values\":false,\"name\":\"@version\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":true,\"doc_values\":false,\"name\":\"message\",\"count\":0,\"scripted\":false},{\"type\":\"date\",\"indexed\":true,\"analyzed\":false,\"doc_values\":false,\"name\":\"@timestamp\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":false,\"name\":\"_type\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":false,\"analyzed\":false,\"name\":\"_id\",\"count\":0,\"scripted\":false},{\"type\":\"string\",\"indexed\":true,\"analyzed\":false,\"doc_values\":false,\"name\":\"host.raw\",\"count\":0,\"scripted\":false},{\"type\":\"geo_point\",\"indexed\":true,\"analyzed\":false,\"doc_values\":false,\"name\":\"geoip.location\",\"count\":0,\"scripted\":false}]"}
}, {
"_index" : ".kibana",
"_type" : "config",
"_id" : "4.0.0-beta3",
"_score" : 1.0,
"_source":{"defaultIndex":"logstash-"}
}, {
"_index" : "_river",
"_type" : "mongodb",
"_id" : "_meta",
"_score" : 1.0,
"_source":{
"type": "mongodb", 
"mongodb": { 
"db": "collective_intel",
"collection": "ips_test"
}, 
"index": { 
"name": "mongoindex",
"type": "mongodb"
}
}
}, {
"_index" : "_river",
"_type" : "mongodb",
"_id" : "collective_intel.ips_test",
"_score" : 1.0,
"_source":{"mongodb":{"_last_ts":"{ \"$ts\" : 1423637351 , \"$inc\" : 1}"}}
}, {
"_index" : "_river",
"_type" : "mongocc",
"_id" : "_meta",
"_score" : 1.0,
"_source":{
"type": "mongodb", 
"mongodb": { 
"db": "cc",
"collection": "cc_data"
}, 
"index": { 
"name": "mongoindexcc"
}
}
}, {
"_index" : "_river",
"_type" : "mongocc",
"_id" : "cc.cc_data",
"_score" : 1.0,
"_source":{"mongodb":{"_last_ts":"{ \"$ts\" : 1423637351 , \"$inc\" : 1}"}}
}, {
"_index" : "_river",
"_type" : "mongodb",
"_id" : "_riverstatus",
"_score" : 1.0,
"_source":{"mongodb":{"status":"START_FAILED"}}
}, {
"_index" : "_river",
"_type" : "mongodb",
"_id" : "_status",
"_score" : 1.0,
"_source":{"node":{"id":"S5Xs5aBQRyK7A76GTa57tQ","name":"Gideon","transport_address":"inet[/72.52.190.7:9300]"}}
} ]
}
}

**Comment by untergeek** [comment]
What's the name of the Logstash index?

```
curl -XGET "localhost:9200/logstash-2015.02.12/_search?q=*&pretty"
```

Replace `logstash-2015.02.12` with your index name.

**Comment by Israaaaa** [comment]
My Logstash index name is logstash-2015.02.12

Here is the result of that command: 

{
  "took" : 172,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 6,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "logstash-2015.02.12",
      "_type" : "logs",
      "_id" : "AUuAFSZB4ZCRI5d_L0pB",
      "_score" : 1.0,
      "_source":{"message":"{ \"_id\" : ObjectId(\"5327ddf68e7e78c99a39df24\"), \"asn\" : \"47142\", \"cc\" : \"UA\", \"cidr\" : \"91.207.7.0/24\", \"evidence\" : { \"infiltrated\" : [ ISODate(\"2014-03-18T05:47:33Z\"), ISODate(\"2014-03-18T13:00:28Z\"), ISODate(\"2014-03-18T20:18:28Z\"), ISODate(\"2014-03-19T04:00:31Z\"), ISODate(\"2014-03-19T13:00:33Z\"), ISODate(\"2014-05-31T04:00:25Z\"), ISODate(\"2014-05-31T13:00:23Z\"), ISODate(\"2014-05-31T20:00:23Z\"), ISODate(\"2014-06-01T04:00:25Z\"), ISODate(\"2014-06-01T13:00:24Z\"), ISODate(\"2014-06-01T20:00:38Z\"), ISODate(\"2014-06-02T04:00:25Z\"), ISODate(\"2014-06-02T13:00:23Z\"), ISODate(\"2014-06-02T20:00:25Z\") ] }, \"ip\" : \"91.207.7.29\", \"rir\" : \"RI\" }","@version":"1","@timestamp":"2015-02-12T23:17:11.908Z","host":"eggdrop"}
    }, {
      "_index" : "logstash-2015.02.12",
      "_type" : "logs",
      "_id" : "AUuAFSZB4ZCRI5d_L0o_",
      "_score" : 1.0,
      "_source":{"message":"{ \"_id\" : ObjectId(\"5327ddf68e7e78c99a39df5e\"), \"asn\" : \"43765\", \"cc\" : \"UA\", \"cidr\" : \"91.200.12.0/22\", \"evidence\" : { \"infiltrated\" : [ ISODate(\"2014-03-18T05:47:33Z\"), ISODate(\"2014-03-18T13:00:28Z\"), ISODate(\"2014-03-18T20:18:28Z\"), ISODate(\"2014-03-19T04:00:31Z\"), ISODate(\"2014-03-19T13:00:33Z\"), ISODate(\"2014-09-26T20:00:24Z\"), ISODate(\"2014-09-27T04:00:23Z\"), ISODate(\"2014-09-27T13:00:23Z\"), ISODate(\"2014-09-27T20:00:23Z\") ] }, \"ip\" : \"91.200.13.7\", \"rir\" : \"RI\" }","@version":"1","@timestamp":"2015-02-12T23:17:11.901Z","host":"eggdrop"}
    }, {
      "_index" : "logstash-2015.02.12",
      "_type" : "logs",
      "_id" : "AUuAFSZB4ZCRI5d_L0pC",
      "_score" : 1.0,
      "_source":{"message":"{ \"_id\" : ObjectId(\"5327ddf68e7e78c99a39df25\"), \"asn\" : \"47142\", \"cc\" : \"UA\", \"cidr\" : \"91.207.7.0/24\", \"evidence\" : { \"infiltrated\" : [ ISODate(\"2014-03-18T05:47:33Z\"), ISODate(\"2014-03-18T13:00:28Z\"), ISODate(\"2014-03-18T20:18:28Z\"), ISODate(\"2014-03-19T04:00:31Z\"), ISODate(\"2014-03-19T13:00:33Z\"), ISODate(\"2014-05-31T04:00:25Z\"), ISODate(\"2014-05-31T13:00:23Z\"), ISODate(\"2014-05-31T20:00:23Z\"), ISODate(\"2014-06-01T04:00:25Z\"), ISODate(\"2014-06-01T13:00:24Z\"), ISODate(\"2014-06-01T20:00:38Z\"), ISODate(\"2014-06-02T04:00:25Z\"), ISODate(\"2014-06-02T13:00:23Z\"), ISODate(\"2014-06-02T20:00:25Z\") ] }, \"ip\" : \"91.207.7.254\", \"rir\" : \"RI\" }","@version":"1","@timestamp":"2015-02-12T23:17:11.908Z","host":"eggdrop"}
    }, {
      "_index" : "logstash-2015.02.12",
      "_type" : "logs",
      "_id" : "AUuAFSZB4ZCRI5d_L0pD",
      "_score" : 1.0,
      "_source":{"message":"{ \"_id\" : ObjectId(\"5327ddf68e7e78c99a39df26\"), \"asn\" : \"47142\", \"cc\" : \"UA\", \"cidr\" : \"91.207.7.0/24\", \"evidence\" : { \"infiltrated\" : [ ISODate(\"2014-03-18T05:47:33Z\"), ISODate(\"2014-03-18T13:00:28Z\"), ISODate(\"2014-03-18T20:18:28Z\"), ISODate(\"2014-03-19T04:00:31Z\"), ISODate(\"2014-03-19T13:00:33Z\"), ISODate(\"2014-05-31T04:00:25Z\"), ISODate(\"2014-05-31T13:00:23Z\"), ISODate(\"2014-05-31T20:00:23Z\"), ISODate(\"2014-06-01T04:00:25Z\"), ISODate(\"2014-06-01T13:00:24Z\"), ISODate(\"2014-06-01T20:00:38Z\"), ISODate(\"2014-06-02T04:00:25Z\"), ISODate(\"2014-06-02T13:00:23Z\"), ISODate(\"2014-06-02T20:00:25Z\") ] }, \"ip\" : \"91.207.7.253\", \"rir\" : \"RI\" }","@version":"1","@timestamp":"2015-02-12T23:17:11.909Z","host":"eggdrop"}
    }, {
      "_index" : "logstash-2015.02.12",
      "_type" : "logs",
      "_id" : "AUuAFSZB4ZCRI5d_L0pE",
      "_score" : 1.0,
      "_source":{"message":"{ \"_id\" : ObjectId(\"5327ddf68e7e78c99a39df27\"), \"asn\" : \"47142\", \"cc\" : \"UA\", \"cidr\" : \"91.207.7.0/24\", \"evidence\" : { \"infiltrated\" : [ ISODate(\"2014-03-18T05:47:33Z\"), ISODate(\"2014-03-18T13:00:28Z\"), ISODate(\"2014-03-18T20:18:28Z\"), ISODate(\"2014-03-19T04:00:31Z\"), ISODate(\"2014-03-19T13:00:33Z\"), ISODate(\"2014-06-01T20:00:38Z\"), ISODate(\"2014-06-02T04:00:25Z\"), ISODate(\"2014-06-02T13:00:23Z\"), ISODate(\"2014-06-02T20:00:25Z\") ] }, \"ip\" : \"91.207.7.238\", \"rir\" : \"RI\" }","@version":"1","@timestamp":"2015-02-12T23:17:12.572Z","host":"eggdrop"}
    }, {
      "_index" : "logstash-2015.02.12",
      "_type" : "logs",
      "_id" : "AUuAFSZB4ZCRI5d_L0pA",
      "_score" : 1.0,
      "_source":{"message":"{ \"_id\" : ObjectId(\"5327ddf68e7e78c99a39df23\"), \"asn\" : \"47142\", \"cc\" : \"UA\", \"cidr\" : \"91.207.7.0/24\", \"evidence\" : { \"infiltrated\" : [ ISODate(\"2014-03-18T05:47:33Z\"), ISODate(\"2014-03-18T13:00:28Z\"), ISODate(\"2014-03-18T20:18:28Z\"), ISODate(\"2014-03-19T04:00:31Z\"), ISODate(\"2014-03-19T13:00:33Z\"), ISODate(\"2014-06-01T20:00:38Z\"), ISODate(\"2014-06-02T04:00:25Z\"), ISODate(\"2014-06-02T13:00:23Z\"), ISODate(\"2014-06-02T20:00:25Z\") ] }, \"ip\" : \"91.207.7.30\", \"rir\" : \"RI\" }","@version":"1","@timestamp":"2015-02-12T23:17:11.907Z","host":"eggdrop"}
    } ]
  }
}

**Comment by Israaaaa** [comment]
For testing purposes, I have edited the Logstash file without using Elasticsearch this time, as follows:

input { stdin {} }
filter {  geoip { source => "ip"  } }
output {  stdout{}  }

Put the following as input:
"ip" : "91.207.7.253"

And the following was returned as the output
2015-02-13T07:02:39.274+0000 hostname "ip" : "91.207.7.253"

**Comment by Israaaaa** [comment]
So apparently the filter geoip is not working.. Because no points are being returned from the ip I sent out.

**Comment by untergeek** [comment]
For better output:

```
output { stdout { codec => rubydebug } }
```

I tested the geoip filter with the last ip in your above output.  `message` in this case is just the ip I'm putting in on stdin (rather than `ip`).  This is because whatever is captured on stdin is put into the `message` field:

```
bin/logstash -e 'input { stdin {} } filter { geoip { source => "message" } } output { stdout { codec => rubydebug } }'
91.207.7.30
{
       "message" => "91.207.7.30",
      "@version" => "1",
    "@timestamp" => "2015-02-13T16:44:14.953Z",
          "host" => "Aironaut.local",
         "geoip" => {
                    "ip" => "91.207.7.30",
         "country_code2" => "UA",
         "country_code3" => "UKR",
          "country_name" => "Ukraine",
        "continent_code" => "EU",
              "latitude" => 49.0,
             "longitude" => 32.0,
              "location" => [
            [0] 32.0,
            [1] 49.0
        ]
    }
}
```

**Comment by Israaaaa** [comment]
Okay, I see. So that worked for me as well.. But the problem is.. the logs I'm sending out have the field "ip", only.. 

Here is a sample from my logs:

{ "_id" : ObjectId("5327ddf68e7e78c99a39df5e"), "asn" : "43765", "cc" : "UA", "cidr" : "91.200.12.0/22", "evidence" : { "infiltrated" : [ ISODate("2014-03-18T05:47:33Z"), ISODate("2014-03-18T13:00:28Z"), ISODate("2014-03-18T20:18:28Z"), ISODate("2014-03-19T04:00:31Z"), ISODate("2014-03-19T13:00:33Z"), ISODate("2014-09-26T20:00:24Z"), ISODate("2014-09-27T04:00:23Z"), ISODate("2014-09-27T13:00:23Z"), ISODate("2014-09-27T20:00:23Z") ] }, "ip" : "91.200.13.7", "rir" : "RI" }

Btw, thank you for your time!!

**Comment by untergeek** [comment]
I see it now.  Your message is JSON-like, but is not valid JSON.  This means you'll have to parse it out.  I tried piping it through the `json_lines` codec, but it says there's a JSON parse error (likely because instead of true key/value pairs, you have "ObjectID()" and "ISODate()" objects.

So, I took the liberty of parsing out those invalid JSON bits, and fixing up your config:

```
input {
  stdin { }
}

filter {
  mutate {
    # Filter out object naming block bits
    gsub => [
      "message", "ObjectId\(", "",
      "message", "ISODate\(", "",
      "message", "\)", ""
    ]
  }
  # Run the cleaned up "message" field through the json filter
  json { source => "message" }
  # Finally, run the geoip filter on the now-existing "ip" field.
  geoip { source => "ip" }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

And now the output is:

```
{
       "message" => "{ \"_id\" : \"5327ddf68e7e78c99a39df5e\", \"asn\" : \"43765\", \"cc\" : \"UA\", \"cidr\" : \"91.200.12.0/22\", \"evidence\" : { \"infiltrated\" : [ \"2014-03-18T05:47:33Z\", \"2014-03-18T13:00:28Z\", \"2014-03-18T20:18:28Z\", \"2014-03-19T04:00:31Z\", \"2014-03-19T13:00:33Z\", \"2014-09-26T20:00:24Z\", \"2014-09-27T04:00:23Z\", \"2014-09-27T13:00:23Z\", \"2014-09-27T20:00:23Z\" ] }, \"ip\" : \"91.200.13.7\", \"rir\" : \"RI\" }",
      "@version" => "1",
    "@timestamp" => "2015-02-13T17:48:00.175Z",
          "host" => "Aironaut.local",
           "_id" => "5327ddf68e7e78c99a39df5e",
           "asn" => "43765",
            "cc" => "UA",
          "cidr" => "91.200.12.0/22",
      "evidence" => {
        "infiltrated" => [
            [0] "2014-03-18T05:47:33Z",
            [1] "2014-03-18T13:00:28Z",
            [2] "2014-03-18T20:18:28Z",
            [3] "2014-03-19T04:00:31Z",
            [4] "2014-03-19T13:00:33Z",
            [5] "2014-09-26T20:00:24Z",
            [6] "2014-09-27T04:00:23Z",
            [7] "2014-09-27T13:00:23Z",
            [8] "2014-09-27T20:00:23Z"
        ]
    },
            "ip" => "91.200.13.7",
           "rir" => "RI",
         "geoip" => {
                    "ip" => "91.200.13.7",
         "country_code2" => "UA",
         "country_code3" => "UKR",
          "country_name" => "Ukraine",
        "continent_code" => "EU",
              "latitude" => 49.0,
             "longitude" => 32.0,
              "location" => [
            [0] 32.0,
            [1] 49.0
        ]
    }
}
```

**Comment by Israaaaa** [comment]
This is so beautiful.. Thank you! Everything is working now!

**Comment by untergeek** [comment]
If `_id` is not unique, I recommend not using it as it conflicts with how Elasticsearch does document ids.  On the other hand, if `_id` matches something in another database, you may want to keep it.  It just needs to be unique per index+type within Elasticsearch.

You could perhaps rename the field to something else, like objectid:

```
mutate {
  rename => { "_id" => "objectid" }
}
```

Also, keeping the `message` field might be redundant once the information is in the other fields.  You can remove it by changing:

```
# Run the cleaned up "message" field through the json filter
  json { 
    source => "message" 
    remove_field => "message"
  }
```

As scary as that looks, it will _only_ remove the `message` field if the json conversion is successful.

See for yourself:

```
input {
  stdin { }
}

filter {
  mutate {
    gsub => [
      "message", "ObjectId\(", "",
      "message", "ISODate\(", "",
      "message", "\)", ""
    ]
  }
  json {
    source => "message"
    remove_field => "message"
  }
  mutate { rename => { "_id" => "objectid" } }
  geoip { source => "ip" }
}

output {
  stdout {
    codec => rubydebug
  }
}
```

And the new output:

```
{
      "@version" => "1",
    "@timestamp" => "2015-02-13T18:49:54.277Z",
          "host" => "Aironaut.local",
           "asn" => "43765",
            "cc" => "UA",
          "cidr" => "91.200.12.0/22",
      "evidence" => {
        "infiltrated" => [
            [0] "2014-03-18T05:47:33Z",
            [1] "2014-03-18T13:00:28Z",
            [2] "2014-03-18T20:18:28Z",
            [3] "2014-03-19T04:00:31Z",
            [4] "2014-03-19T13:00:33Z",
            [5] "2014-09-26T20:00:24Z",
            [6] "2014-09-27T04:00:23Z",
            [7] "2014-09-27T13:00:23Z",
            [8] "2014-09-27T20:00:23Z"
        ]
    },
            "ip" => "91.200.13.7",
           "rir" => "RI",
      "objectid" => "5327ddf68e7e78c99a39df5e",
         "geoip" => {
                    "ip" => "91.200.13.7",
         "country_code2" => "UA",
         "country_code3" => "UKR",
          "country_name" => "Ukraine",
        "continent_code" => "EU",
              "latitude" => 49.0,
             "longitude" => 32.0,
              "location" => [
            [0] 32.0,
            [1] 49.0
        ]
    }
}
```

As this successfully addresses your concern, I am closing this.

Please ask the [logstash-users google group](https://groups.google.com/forum/#!forum/logstash-users) for usage questions in the future.  If something turns out to be a bug, then an issue can be raised.
