### ISSUE TITLE
move all patches in lib/logstash/patches/

### ISSUE THREAD

**Issue by colinsurprenant** [elasticsearch/logstash#2613]
Isolate any monkey patches into a special directory structure so we can more easily understand what patches we have enabled.

This is a post #2475 issue.

**Comment by ph** [comment]
:monkey_face:'s jail

**Comment by colinsurprenant** [comment]
including this patch 76bb77fd117a21b9eb82d40718571e171e2da44a

**Comment by suyograo** [comment]
Fixed https://github.com/elasticsearch/logstash/pull/2668
