### ISSUE TITLE
[doc] /docs/1.4.2/flags - sample config string is outdated

### ISSUE THREAD

**Issue by cernautan** [elasticsearch/logstash#2620]
in: http://logstash.net/docs/1.4.2/flags
For the '-e' flag, the example ( 'stdout { debug => true }}' ) is outdated.

According to http://logstash.net/docs/1.4.2/outputs/stdout the sample config string should be:
'stdout { codec  => rubydebug }'

**Comment by untergeek** [comment]
Thanks for reporting this (you are not the first to point it out--it just takes an act of congress to publish new docs for the old branch).  Fortunately, the docs for 1.5 do not have this oversight.  You can see the work in progress for the 1.5 docs at http://www.elasticsearch.org/guide/en/logstash/current/index.html
