### ISSUE TITLE
refactor LogStash::Bundler.bundler_arguments

### ISSUE THREAD

**Issue by colinsurprenant** [elasticsearch/logstash#2623]
this method could benefit refactoring. see #2475 discussion.

**Comment by ph** [comment]
I have to rebase my branch with the latest changes with the `Bundler.settings`

**Comment by ph** [comment]
@colinsurprenant the `bundler_arguments` method doesn't do much now, so I dont feel the need of refactoring it. I have decided instead to add some tests for this class to guard the fuzzy behavior..

**Comment by colinsurprenant** [comment]
+1
