### ISSUE TITLE
contrib plugin fail.

### ISSUE THREAD

**Issue by rakesh91** [elasticsearch/logstash#2628]
Hi,
In logstash setup i am sending output to both mongodb and to elasticsearch, works perfectly fine until mongodb goes down. If mongodb goes down, the other output elasticsearch also ceases. Shouldn't both the output be independent of each other? or Am i missing something?

Using 
1.4.2 logstash.
milestone 2 output plugin 'mongodb'
Thanks,
Rakesh

**Comment by untergeek** [comment]
This is the expected behavior.  Were it not so, one of your outputs stands to lose data while the other receives normally.

**Comment by rakesh91** [comment]
@untergeek In that case when elasticsearch is down, mongo shouldn't get any data. But in my setup when ES is down, i see the data in mongo.

**Comment by untergeek** [comment]
Yes, but Elasticsearch in 1.4.2 is set to buffer 500 messages (the default) before sending.  Logstash's queue is only 20 lines deep, so Mongo could receive messages before the Logstash pipeline turned up full and unable to send to Elasticsearch.

**Comment by rakesh91** [comment]
@untergeek So to stop logstash from pilling up, contrib plugin is reading data, is it?

**Comment by untergeek** [comment]
All outputs will try to output in parallel, always.  There's nothing single-plugin specific, or otherwise,  which can change this behavior.

**Comment by rakesh91** [comment]
@untergeek Thanks, Got it.

**Comment by rakesh91** [comment]
Sorry, got one more question. I did the some experiment with file - mongodb, file - elasticsearch. Whenever mongo is stopped, file is not getting output which is perfectly fine. But, when file's output fails mongo is still getting the data. Same with elasticsearch, it works smoothly though file is not there. File fails when elasticsearch is down. 
why this behavior with file output?

**Comment by untergeek** [comment]
I am guessing it does happen because writes to the OS are buffered and not necessarily returned as failures in the correct way.

This behavior should be tested against 1.5.  There may be changes merged since 1.4.2 which affect this.

If it persists in 1.5, an issue should be raised in https://github.com/logstash-plugins/logstash-output-file as a bug.  This behavior should not happen.

**Comment by rakesh91** [comment]
ok Thanks.
