### ISSUE TITLE
Update jenkins to latest rake tasks after the bundler refactor

### ISSUE THREAD

**Issue by suyograo** [elasticsearch/logstash#2634]
In #2475, as part of the major bundler refactoring effort we added new rake tasks. The current Jenkins jobs use the old way of testing so they need to be updated after the merge

Rake tasks to install default plugins and their dev dependencies:

```
rake test:install-core
rake test:install-default
rake test:install-all
```
To test them:

```
rake test:plugins
rake test:core 
rake test:core-fail-fast
```

**Comment by purbon** [comment]
working in a way to fix that.

**Comment by purbon** [comment]
I proposed an improvement that would make our life easier in #2639 and 2638, if this gets merged I can later update our internal jenkins and have an smooth transition.

It would be also nice to have a similar setup for plugins, but this is a matter of another story.

**Comment by purbon** [comment]
can we close this? @suyograo
