### ISSUE TITLE
One shard constantly fails to allocate

### ISSUE THREAD

**Issue by darkpixel** [elasticsearch/logstash#2635]
I get one shard that continually fails to allocate.  There is nothing in the logs that would seem to indicate a problem.

![screenshot from 2015-02-17 14 51 10](https://cloud.githubusercontent.com/assets/158380/6239036/c8960ffe-b6b4-11e4-88d1-700080e74634.png)

The pattern of one of the copies of shard '2' not being allocated runs throughout all my logstash indexes.

Running 1.4.3 on all nodes.

Any pointers?

**Comment by markwalkom** [comment]
These sorts of issues are best for the mailing list :)

**Comment by darkpixel** [comment]
Thanks!
