### ISSUE TITLE
[Bundler-move branch] Having two gemspec declarations

### ISSUE THREAD

**Issue by purbon** [elasticsearch/logstash#2637]
While trying to apply the #2629 PR in the #2475 bundler refactor branch, I noticed something that raised a question on me.

I created two gemspec files there, one for logstash and another for logstash-core. The first one has dependencies for the main project while the second one has core and testing dependencies. In the #2475 codebase there is an explicit check for having only one gemspec declaration (https://github.com/elasticsearch/logstash/blob/wip/bundler-move/lib/logstash/gemfile.rb#L156), do we've any especific reason for that? why we can not have more than one? 

Thanks

**Comment by ph** [comment]
The gemspec directive checck is only done when we are validating the Gemfile, since we can only use one `gemspec` per Gemfile.

**Comment by purbon** [comment]
Why can we only use one per Gemfile ? is this a limitation that we somehow impose ? as far as I know with bundler there is no problem to use multiple gemspecs, right? (correct me if I'm wrong)

What is your best advice to handle this properly? I would like to have dependencies only defined once.

- purbon

**Comment by colinsurprenant** [comment]
it does not really make sense to reference 2 gemspecs from a Gemfile and I don't think it is valid...

**Comment by purbon** [comment]
I see is a design decision of yours, there is actually no point on the gemspec documentation or any other place in rubygems where I've seen that this is not an option.  I see it as a very valid option when you've more than one gem in the same project and want to integrate them all, but this is just my point of view.

Ok, now I understand the point of this, so I close this issue. If we find this to be a limitation we can always remove this check.

Thanks for the clarification.
