### ISSUE TITLE
Logstash version for ElasticSearch 1.4.4

### ISSUE THREAD

**Issue by stephenstroud** [elasticsearch/logstash#2657]
Which version of Logstash should I use with ElasticSearch 1.4.4 - running on Windows Server 2012 R2

**Comment by suyograo** [comment]
Hey, Logstash 1.4.2 is the current stable version and it works with any ES above v1.x. So 1.4.4 will work with it

**Comment by brizzbane** [comment]
rss plugin I tried is not working, was with 1.4.2,
