### ISSUE TITLE
rspec test does not work in all plugins

### ISSUE THREAD

**Issue by purbon** [elasticsearch/logstash#2663]
If you run the recommended commands to execute the tests in a plugin they don't work, having an error that looks like:

```
Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
Gem::LoadError: rspec-core is not part of the bundle. Add it to Gemfile.
     gem at /mnt/jenkins/rbenv/versions/jruby-1.7.16/lib/ruby/gems/shared/gems/bundler-1.7.6/lib/bundler/rubygems_integration.rb:256
  (root) at /home/jenkins/.rbenv/versions/jruby-1.7.16/bin/rspec:22
Build step 'Conditional step (single)' marked build as failure
Sending e
````

or 

```
➜  logstash-input-kafka git:(master) ✗ bundle exec rspec
bundler: command not found: rspec
```

This error gets solved if you add  ```gem "rspec", :group => :development``` to your Gemfile or ``` spec.add_development_dependency 'rspec' ``` to your plugin.gemspec file.

All plugins are affected.

**Comment by electrical** [comment]
Shouldn't it be part of devutils ?

**Comment by purbon** [comment]
The development dependencies of development dependencies are not installed (by default), so answer is no.

**Comment by purbon** [comment]
I retract my last comment, I see rspec as a runtime development for devutils, not a development one as it's right now. Then the fix is easy ;-)

**Comment by purbon** [comment]
Fixed by https://github.com/elasticsearch/logstash-devutils/pull/22
