### ISSUE TITLE
Logstash-web debian init script fails

### ISSUE THREAD

**Issue by Thinkscape** [elasticsearch/logstash#2678]
1. Install logstash on Ubuntu 12 from Debian packages.
2. Try to start with `/etc/init.d/logstash-web start`

### Expected
Service starts

### Actual
````bash
# /etc/init.d/logstash-web status
logstash-web is running

# netstat -apn | grep 9292

# tail /var/log/logstash/logstash-web.err
nice: 19: No such file or directory
````

**Comment by jordansissel** [comment]
logstash-web is removed in Logstash 1.5, so this problem will not occur in the next release.
