### ISSUE TITLE
Bundler::GemfileNotFound thrown when bin/logstash isn't run from logstash root directory.

### ISSUE THREAD

**Issue by joekiller** [elasticsearch/logstash#2681]
If you invoke logstash outside the root directory which it resides (either from source or when installed) you get the following result:

```
$ /tmp/logstash/bin/logstash -f /etc/logstash/conf.d --debug
Bundler::GemfileNotFound: Could not locate Gemfile or .bundle/ directory
                         root at /tmp/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.2/lib/bundler.rb:198
                  bundle_path at /tmp/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.2/lib/bundler.rb:101
  configure_gem_home_and_path at /tmp/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.2/lib/bundler.rb:420
                    configure at /tmp/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.2/lib/bundler.rb:92
                   definition at /tmp/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.2/lib/bundler.rb:153
                        setup at /tmp/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.8.2/lib/bundler.rb:118
               bundler_setup! at /tmp/logstash/lib/logstash/environment.rb:106
                       (root) at /tmp/logstash/lib/logstash/runner.rb:8
```

If I `cd` into `/tmp/logstash` (where I have master checked out) and then run the command it works fine.

The problem is that https://github.com/elasticsearch/logstash/blob/9561ade0353c4f12b3ba39edfd43a1d75e1a7748/lib/logstash/environment.rb#L91 detects that `[logstash_root]/.bundle/config` exists, however there isn't ever an entry for `BUNDLE_GEMFILE` so unless you are in `logstash_root` Bundler cannot find `Gemfile`.  This can be fixed by moving `ENV["BUNDLE_GEMFILE"] = LogStash::Environment::GEMFILE_PATH` outside the `unless`.

It's hard for me to tell, being unfamiliar with Bundler as much, where BUNDLE_GEMFILE would be written to the config file.

**Comment by joekiller** [comment]
ps, as mentioned in #2674 if I delete  .bundle/config everything works fine.  I think the explanation above details why deleting it works.

**Comment by joekiller** [comment]
Finally I think the .bundle/config file shows up when you `bin/plugin install --no-verify`

**Comment by jordansissel** [comment]
![BUNDLERRRR!!!!](http://i.imgur.com/8pNwzC8.jpg)

**Comment by colinsurprenant** [comment]
@joekiller good catch! in fact Bundler does not store BUNDLE_GEMFILE in its `.bundle/setup` so whenever `bin/plugin install` is invoked the and `.bundle/setup` created, `ENV["BUNDLE_GEMFILE"]` will not be set. 

moving it outside the condition will in fact solve this. stay tune for a PR.

**Comment by colinsurprenant** [comment]
fix in #2685

**Comment by colinsurprenant** [comment]
fix is in master. 

@joekiller let us know how that work for you. Also, are the `.rpm` init scripts working for you?

**Comment by joekiller** [comment]
I will test and let you know.  .rpm stuff seemed good beyond this.

**Comment by colinsurprenant** [comment]
great! thanks!

**Comment by joekiller** [comment]
rpm builds feel good.  Now if only that plugin uninstall bug was fixed, I'd almost greenlight :)

**Comment by colinsurprenant** [comment]
@joekiller great stuff! thanks for the feedback. looking at #2689
