### ISSUE TITLE
Netflow codec and no matching template

### ISSUE THREAD

**Issue by lolostates** [elasticsearch/logstash#2694]
Hi, 

I try to store Netflow on ElasticSearch using Logstash codec.
I use netflow V9 but logstash input debug return this: 

{:timestamp=>"2015-02-26T12:34:40.521000+0100", :message=>"No matching template for flow id 260", :level=>:warn}

I don't understand this error. Does it mean: my netflow version isnt supported ?
I have created a new yaml file trying to match with my netflow template.

![capture d ecran de 2015-02-26 12 39 44](https://cloud.githubusercontent.com/assets/2452640/6391253/9406cca4-bdb4-11e4-88a8-b44b76748dc8.png)

and my yaml file:

```yaml
---
1:
- 4
- :pkts
2:
- 4
- :bytes
3:
- :ip4_addr
- :ip_src_addr
4:
- :ip4_addr
- :ip_dst_addr
5:
- 4
- :input_snmp
6:
- 4
- :output_snmp
7:
- 4
- :last_switched
8:
- 4
- :first_switched
9:
- :uint16
- :l4_src_port
10:
- :uint16
- :l4_dst_port
11:
- :uint32
- :src_as
12:
- :uint32
- :dst_as
13:
- :ip4_addr
- :bgp_next_hop
14:
- :uint8
- :src_mask
15:
- :uint8
- :dst_mask
16:
- :uint8
- :protocol
17:
- :uint8
- :tcp_flags
18:
- :uint8
- :ip_tos
19:
- :uint8
- :direction
20:
- :uint8
- :forwarding_status
21:
- :uint16
- :flow_sampler_id
22:
- :uint32
- :ingress_vrfid
23:
- :uint32
- :egress_vrfid
```

Does it mean that netflow plugin can "learn" each field ?

Thanks in advance,
Regards.

**Comment by untergeek** [comment]
I apologize for the inconvenience, but plugin-related issues need to be registered in their respective repositories.

Please open this issue at https://github.com/logstash-plugins/logstash-codec-netflow
