### ISSUE TITLE
read rabbitmq headers

### ISSUE THREAD

**Issue by fsarwari** [elasticsearch/logstash#2720]
Is it possible to read headers from the rabbitmq input plugin?

There's an old  jira ticket it mentions such a feature.  And from the ticket it looks like it should work.  But I can't find anything in the docs to show how to extract headers from rabbitmq.  
https://logstash.jira.com/browse/LOGSTASH-926

In the docs for an older version of logstash it has a headers_field as a config option.  This option is no longer available in the newer versions.

Thanks

**Comment by jordansissel** [comment]
@fsarwari this sounds like a similar thing to this: https://github.com/logstash-plugins/logstash-input-rabbitmq/issues/7 - can we move the discussion there if so? Otherwise, if not related, can you move this to https://github.com/logstash-plugins/logstash-input-rabbitmq/issues?

**Comment by fsarwari** [comment]
created new issue in logstash-input-rabbitmq.
Thanks.
