### ISSUE TITLE
Mass update all plugins with RC1 version of logstash-core

### ISSUE THREAD

**Issue by suyograo** [elasticsearch/logstash#2729]
Dependent on https://github.com/elasticsearch/logstash/issues/2709

**Comment by suyograo** [comment]
logstash-core rc1 has been published

**Comment by purbon** [comment]
Not sure this is need at all,
 the way the plugin gemspecs are right now is like this:

```
  # Gem dependencies
  s.add_runtime_dependency "logstash-core", '>= 1.4.0', '< 2.0.0'
````

what means they are by now automatically getting the last logstash-core gem released in rubygems.

**Comment by jsvd** [comment]
Agreed, we don't have a dependency on a fixed version of logstash-core. It might make sense, tough, to mass update all plugins once we release the final 1.5.0 to:

` s.add_runtime_dependency "logstash-core", '>= 1.5.0', '< 2.0.0'`
