### ISSUE TITLE
prune whitelist gives 'tv_sec' error

### ISSUE THREAD

**Issue by mikedewar** [elasticsearch/logstash#2730]
In logstash 1.4.2, the following filter:
```
filter {
  prune {
    whitelist_names => [ "agent" ]
  }
}
```
produces the error:
```
NoMethodError: undefined method `tv_sec' for nil:NilClass
        sprintf at /home/ubuntu/logstash-1.4.2/lib/logstash/event.rb:230
           gsub at org/jruby/RubyString.java:3041
        sprintf at /home/ubuntu/logstash-1.4.2/lib/logstash/event.rb:216
        receive at /home/ubuntu/logstash-1.4.2/lib/logstash/outputs/elasticsearch.rb:308
         handle at /home/ubuntu/logstash-1.4.2/lib/logstash/outputs/base.rb:86
     initialize at (eval):38
           call at org/jruby/RubyProc.java:271
         output at /home/ubuntu/logstash-1.4.2/lib/logstash/pipeline.rb:266
   outputworker at /home/ubuntu/logstash-1.4.2/lib/logstash/pipeline.rb:225
  start_outputs at /home/ubuntu/logstash-1.4.2/lib/logstash/pipeline.rb:152
2015/03/02 17:54:35 ERROR: failed to write to os.Stdout - write /dev/stdout: broken pipe
```
Here is my full config:
```
input {
  pipe {
    command => "***"
    codec => "json"
  }
}
filter {
  prune {
    whitelist_names => [ "agent" ]
  }
}
output {
  elasticsearch { host => localhost }
  pipe {command => "***"}
}
```
Without the filter, or with other filters (I have also tried mutate), it works fine - elastic search is populated and my pipe command does its thing well.

This is a fresh install of logstash/elasticsearch on an otherwise shiny new ubuntu 12.04 machine. I'm new to logstash; happy to provide any more information as needed.

**Comment by talevy** [comment]
Hi @mikedewar, thanks for sharing this and I am sorry you ran into this issue. I have published a PR for Logstash 1.5 (sorry, not 1.4.2!) with a possible fix for this expection, here: https://github.com/elasticsearch/logstash/pull/2736

Basically, the `prune` filter is removing a somewhat important field within each Logstash event called `@timestamp`. This field is used to properly index each event into elasticsearch by day. This is the default behavior of Logstash. 

This default ES-index value can be found here:
https://github.com/elasticsearch/logstash/blob/v1.4.2/lib/logstash/outputs/elasticsearch.rb#L47

Assuming your piped inputs do not have any fields named `@timestamp`, the current timestamp will 
be set for this field de-facto. If that is still alright with you, then you can go ahead and add `@timestamp` to your list of `whitelist_names` and the `elasticsearch` output will index them accordingly.

let me know if that helps!

**Comment by mikedewar** [comment]
that does help! Why, I wonder, would prune do this?

Also, can I instead somehow use a timestamp that's already in my message? That would be great.

**Comment by talevy** [comment]
plugins sometimes have their own view of the worlds :smile: 

to update the Logstash Event timestamp you can check out the `date` filter here: http://logstash.net/docs/1.4.2/filters/date

and it can be used in your config with something like this:

```
filter {
    date {
        match => [ "YOUR_TIMESTAMP_FIELD_HERE", "STR_FORMAT_OF_TIMESTAMP_STRING" ]
        locale => en
        remove_field => "YOUR_TIMESTAMP_FIELD_HERE"
    }
    prune {
        whitelist_names => [ "@timestamp", "agent" ]
    }
}
```
This will match the `@timestamp` field with your own field, and then go ahead and remove the original field (assuming you do not need it after you treat `@timestamp` as the source of truth time field)

**Comment by mikedewar** [comment]
brilliant! Thanks so much for the help!

**Comment by talevy** [comment]
no problem, enjoy!
