### ISSUE TITLE
Gemfile & Gemfile.jruby-1.9.lock for 1.5-rc1 should contain default plugins

### ISSUE THREAD

**Issue by colinsurprenant** [elasticsearch/logstash#2733]
make sure 1.5-rc1 branch/tag contains Gemfile & Gemfile.jruby-1.9.lock with all packaged plugins. This is really important to be able to recreate the package with the correct plugins versions originally included in the released package.

**Comment by suyograo** [comment]
Fixed https://github.com/elasticsearch/logstash/commit/909778a75fac92248466347e8d0269daa7c7c1ec
