### ISSUE TITLE
Logstash 1.4.2 unit tests fail in 1.5.0 beta1 version

### ISSUE THREAD

**Issue by 91pavan** [elasticsearch/logstash#2743]
I get this error when I run the unit tests by issuing the following command

```
bin/logstash rpsec test/test-log-1.rb
```
```
LoadError: no such file to load -- test_utils
          require at org/jruby/RubyKernel.java:1065
          require at /home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55
          require at /home/vagrant/logstash-1.5.0.beta1/vendor/jruby/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53
           (root) at /home/vagrant/logstash-1.5.0.beta1/test/test-log-1.rb:3
             load at org/jruby/RubyKernel.java:1081
           (root) at /home/vagrant/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:1
             each at org/jruby/RubyArray.java:1613
  load_spec_files at /home/vagrant/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896
  load_spec_files at /home/vagrant/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/rspec-core-2.14.8/lib/rspec/core/configuration.rb:896
              run at /home/vagrant/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/rspec-core-2.14.8/lib/rspec/core/command_line.rb:22
              run at /home/vagrant/logstash-1.5.0.beta1/lib/logstash/runner.rb:58
              run at /home/vagrant/logstash-1.5.0.beta1/lib/logstash/runner.rb:113
             call at org/jruby/RubyProc.java:271
              run at /home/vagrant/logstash-1.5.0.beta1/lib/logstash/runner.rb:171
             call at org/jruby/RubyProc.java:271
              run at /home/vagrant/logstash-1.5.0.beta1/vendor/bundle/jruby/1.9/gems/rspec-core-2.14.8/lib/rspec/core/runner.rb:80
```

Here is my unit test : http://pastebin.com/69CaRPtZ

Am I missing something obvious here?

**Comment by purbon** [comment]
I'm not sure what this test utils are, but in 1.5.0 I don't see it any where, this might be the reason of your test failing.

I check your test and is not hard to adapt them to something similar to https://github.com/elasticsearch/logstash/blob/master/spec/core/conditionals_spec.rb#L132

Let me know if this helps.

- purbon

**Comment by 91pavan** [comment]
@purbon Even if I comment out that line, it gives me an error 
```
NameError: uninitialized constant LogStash::RSpec
    const_missing at org/jruby/RubyModule.java:2723
```

Is this documented anywhere? I searched everywhere and couldn't find anything about backporting of unit tests

**Comment by purbon** [comment]
There is no ```LogStash::RSpec```, you should take a look at the current test under the spec directory in logstash to get inspiration how to port yours. This is the best way to know how to make yours work. Might I ask you what do you want to test? It looks like you want to test a grok pattern, isn't?

**Comment by wiibaa** [comment]
@purbon fyi this "old" test style is the 1.4.x test style used with `bin/logstash rspec` command.It comes from before https://github.com/elasticsearch/logstash/pull/1758, I could not found a clear statement in the changelog or somewhere else about this change

**Comment by purbon** [comment]
Jajaj, ok! ;-) you notice I'm new here! The easiest point to port this is to take a look at current test, I found them not much different.

thanks for the history class ;-)

**Comment by wiibaa** [comment]
@91pavan I suppose you figured out by yourself but just to be sure, you need to 

1. replace `require 'test_utils'` with `require 'spec_helper'`
2. remove ` extend LogStash::RSpec`

Also you might be interested to know that Logstash is moving away from reject/insist in favor of rspec3 *expect* syntax

**Comment by purbon** [comment]
@91pavan do you know how to move on? can we close this issue?

**Comment by 91pavan** [comment]
Yep, thanks.

**Comment by purbon** [comment]
Thanks! if you need more help, dont worry to open another issue ;-) closing this one.
