### ISSUE TITLE
grok 'match' documentation differs from examples

### ISSUE THREAD

**Issue by wpaulson** [elasticsearch/logstash#2750]
The `match` key of the `grok` plugin says in the docs that it takes a value type of Hash, yet every example shows it taking an array value type. In the code, the `config` validates it as a `:hash` which apparently generates the `Value type is hash` line. The comment that precedes the `config` line also says it's a hash, yet the example in the same comment shows it as an array.

**Comment by suyograo** [comment]
@wpaulson The next release 1.5.0, will refer to this documentation http://www.elasticsearch.org/guide/en/logstash/current/plugins-filters-grok.html#plugins-filters-grok-match which has the `match` fixed

Let me know if this works

**Comment by wpaulson** [comment]
Works for me

**Comment by jordansissel** [comment]
The "array" syntax for hashes is from before logstash 1.2.0 and is still
valid.
