### ISSUE TITLE
Logstash show _grokparsefailure, despite Grokdebugger can parse log

### ISSUE THREAD

**Issue by Kashlikov** [elasticsearch/logstash#2758]
Hi, can somebody please advice on my issue.  

I have such simple example from log file

[3/2/15 23:03:01:687 EST] 00000086 Logging       I here is some text
[3/2/15 23:03:01:688 EST] 00000086 Logging       I here is some text

Below is my test config and I have defined custom pattern in grok pattern file. 

If I use http://grokdebug.herokuapp.com, it can parse such records, but log stash itself says _grokparsefailure.    I have used tons of different settings, but unfortunately still no luck

![screen shot 2015-03-04 at 12 58 27 am](https://cloud.githubusercontent.com/assets/11250064/6478872/9dc231b2-c209-11e4-9f15-5add7886b42e.png)

input {
  file {
        
   type => "websphere"
    path => "/home/user/Downloads/websphere.log"
    start_position => beginning
  }
}
 
filter {
  if [type] == "websphere" {
    grok {      
      match => { 
        message => "\\[%{WEBSPHERE_TIMESTAMP:logdate}\\]%{SPACE}%{DATA:thread}\s%{DATA:log}\s\w\s%{GREEDYDATA:messagetext}"
               }
      add_tag => ["env_prod"] 
         }
                            }
     }
 
output {
  stdout {
    codec => rubydebug
  }
}

**Comment by 91pavan** [comment]
First, this should have been posted on the logstash-users mailing list, not here.

Here's what you need to do:
1. you need to escape the brackets in your grok filter and add the custom pattern in some file inside patterns directory.

**Comment by Kashlikov** [comment]
Apologies for posting in not correct place.   But as I mentioned, custom pattern is added inside grok-patterns files.  Also in fact brackets are escaped, not sure why web show them in my config without escape.  When I click edit post, I see them.   Now I have updated post and added one more escape to reflect this correctly.

**Comment by suyograo** [comment]
hi @Kashlikov and @91pavan thanks for your responses. We encourage folks to ask config type questions in the logstash-users mailing list (because someone might have already hit this issue and have a ready answer, and also, we have active users on the mailing list).  We do welcome any questions here if you are not sure of what to ask in the ML.

**Comment by Kashlikov** [comment]
Thanks. I have opened thread there https://groups.google.com/forum/#!topic/logstash-users/eO5I5mgqVns  and closing this one,

**Comment by suyograo** [comment]
thanks much @Kashlikov !
