### ISSUE TITLE
No such file or directory - Gemfile.defaults

### ISSUE THREAD

**Issue by patrickbcullen** [elasticsearch/logstash#2781]
I checked out the source and attempted to build:

rake artifact:tar

Invoking bundler install...
Resolving dependencies...
Using addressable 2.3.7
Using thread_safe 0.3.4
Using descendants_tracker 0.0.4
Using ice_nine 0.11.1
Using axiom-types 0.1.1
Using backports 3.6.4
Using cabin 0.7.1
Using clamp 0.6.4
Using coderay 1.1.0
Using coercible 1.0.0
Using equalizer 0.0.9
Using ffi 1.9.6
Using minitar 0.5.4
Using file-dependencies 0.1.6
Using filesize 0.0.4
Using http_parser.rb 0.6.0
Using ftw 0.0.42
Using i18n 0.6.9
Using jar-dependencies 0.1.7
Using jrjackson 0.2.8
Using jruby-httpclient 1.1.1
Using virtus 1.0.4
Using maven-tools 1.0.7
Using mime-types 2.4.3
Using method_source 0.8.2
Using slop 3.6.0
Using spoon 0.0.4
Using pry 0.10.1
Using rack 1.6.0
Using ruby-maven-libs 3.1.1
Using ruby-maven 3.1.1.0.8
Using rack-protection 1.5.3
Using tilt 1.4.1
Using sinatra 1.4.5
Using stud 0.0.19
Using polyglot 0.3.5
Using treetop 1.4.15
Using logstash-core 2.0.0.dev from source at .
Using bundler 1.8.4
Bundle complete! 6 Gemfile dependencies, 39 gems now installed.
Gems in the group development were not installed.
Bundled gems are installed into ./vendor/bundle.
rake aborted!
No such file or directory - Gemfile.defaults
org/jruby/RubyFile.java:848:in `stat'
/home/ec2-user/Projects/logstash/rakelib/artifacts.rake:47:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1087:in `load'
Tasks: TOP => artifact:tar => artifact:prepare => artifact:use-defaults-gemfile

ruby version = 2.2.0p0
rake version = 10.4.2

**Comment by suyograo** [comment]
@patrickbcullen is this master? if so, you need to do an additional step to build the artifacts. Sorry we are behind on the README

```
rake artifact:freeze-defaults-gemfile
rake artifact:tar
```
