### ISSUE TITLE
Logstash does not push data

### ISSUE THREAD

**Issue by OElesin** [elasticsearch/logstash#2794]
Hello, I have an issue with LogStash and ElasticSeacrch. Each time I try to push data via LogStash, it hangs and I get no response. Although, earlier today, it worked and later it stopped working. No data is being transferred.

Using milestone 2 input plugin 'file'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.5.0.beta1/plugin-milestones {:level=>:warn}
Mar 06, 2015 1:25:17 PM org.elasticsearch.plugins.PluginsService 
INFO: [logstash-terragon-HP-Pro-3120-Microtower-PC-24973-3846] loaded [], sites []

This is the point where it hangs. Kindly help

**Comment by jsvd** [comment]
hi! can you post your configuration file?

**Comment by OElesin** [comment]
Thanks jsvd. Solved it. The issue was with the grok filter command

**Comment by jsvd** [comment]
yay :) closing then
