### ISSUE TITLE
v1.5.0.rc2 keeps stopping

### ISSUE THREAD

**Issue by MarkGavalda** [elasticsearch/logstash#2798]
On Ubuntu 14.04 Logstash v1.5.0.rc2 keeps stopping. I assume this is a memory related issue because when I manually edit /etc/init.d/logstash and change LS_HEAP_SIZE="500m" to something else, like LS_HEAP_SIZE="5g" it stays up, *however* still stops answering and accepting connections after a while!

All log files are clean, I cannot find the reason anywhere :( I've been running 1.4.2 and previous versions on these machines for more than a year now, no issues. Please let me know what debug options should I switch on to resolve this? Thanks.

**Comment by MarkGavalda** [comment]
Additional info:

**input** {
  lumberjack {
    port => 5000
    type => "logs"
    ssl_certificate => "/etc/pki/tls/certs/XY.crt"
    ssl_key => "/etc/pki/tls/private/XY.key"
  }
}

**filters**: grok, date, geoip

**output** {
  elasticsearch {
    host => "localhost"
    protocol => transport }}

**Comment by MarkGavalda** [comment]
What's interesting is that even though logstash stops processing incoming files and doesn't reply to logstash-forwarders at all (they time-out) it keeps eating up RAM until restarted:
![logstash memory and cpu usage](http://i.imgur.com/8lEYWJc.png)

**Comment by untergeek** [comment]
Increasing the heap size is really only masking the problem.

It sounds to me more like an output is blocked, but instead of giving a message that it's blocked, it just continues to buffer until it runs out of space.

Why transport protocol?  The http and node protocols are much more common.  Do you have an objection to using the http protocol, especially since it's localhost you're talking to?

**Comment by MarkGavalda** [comment]
Thanks for the reply @untergeek I was only testing *transport* as I had previously gone through both http (which I was using for the past half a year) and node. It seems like it makes no difference.

**Comment by untergeek** [comment]
Hmmm.   This can also happen when Elasticsearch is overloaded.  How big is your cluster?  How much heap in your nodes?

**Comment by MarkGavalda** [comment]
We have two nodes in this cluster each has 32GB heap (out of 64GB RAM in each machine). Didn't have any issues before upgrading to the new logstash forwarder and 1.5 of logstash. :(

**Comment by MarkGavalda** [comment]
So it turns out there really was a bottleneck somewhere. I modified the setup to include a Redis based buffer / broker and two instances of logstash 1.5 on each machine and now it's chopping along nicely. Thanks @untergeek for your help, much appreciated.

**Comment by stachdude** [comment]
Well, I'm having similar issue: logstash 1.5 rc4, we are already using buffer / broker, however we chose rabbitmq, in any case my setup consists of 12 node es cluster, 6 node rabbitmq (all ram) cluster, and 8 logstash-es 1.5 rc4 setup as consumers with 16 threads and 2048 prefetch. Traffic is balanced through LB (10GB links).

From time to time we are receiving this warning in logs, which was not present in 1.4.2 version of logstash.

LS-es and ES-es have 16 g ram 8g heap, 8 core each, and we only send around 6k eps (~1kb each) (but with ack).

The difference is that we are using rsyslog as a producer, not lumberjack, and the the warning doesn't cause the process to stop.

**Comment by scukonick** [comment]
I have the same issue with logstash 1.5.0 GA. In our case logstash is reading the logs and sending them to ES directly.

**Comment by ph** [comment]
@scukonick can you create a new issue with your configuration, and can you take a heap dump with the `jstack <PID>` command when logstash is frozen? 

Thank you!

**Comment by mrlesmithjr** [comment]
Also experiencing the following running 1.5.0 GA.
{:timestamp=>"2015-06-12T14:48:11.354000-0400", :message=>"retrying failed action with response code: 429", :level=>:warn}

**Comment by talevy** [comment]
@mrlesmithjr that is occurring because your ES cluster is not able to handle the indexing rate your are pushing with Logstash. For such messages received from ES, Logstash will try and retry to submit them. 429 is a response code returned from ES representing "TOO MANY REQUESTS"

**Comment by mrlesmithjr** [comment]
@talevy good info as that is where I was headed in looking as well. Thanks for the info!

**Comment by talevy** [comment]
@mrlesmithjr we actually just updated our docs to explain this more here: https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/master/lib/logstash/outputs/elasticsearch.rb#L37-L63. 

next time we generate our docs for the website, it should show up there with nice formatting!
