### ISSUE TITLE
lumberjack "host" directive does not work

### ISSUE THREAD

**Issue by lifeofguenter** [elasticsearch/logstash#2799]
According to the doc I should be able to setup a host on which lumberjack will listen: http://www.logstash.net/docs/1.4.2/inputs/lumberjack#host

Unfortunately setting it does not do anything and it will still listen on 0.0.0.0.

**Comment by jsvd** [comment]
```
input {
  lumberjack {
    port => 6782
host => "10.128.187.XXX"
    ssl_certificate => ".."
    ssl_key => "..."
    type => "lumberjack"
    codec => "json"
  }
}
output {
   stdout { }
}
```

and the, while doing "bin/logstash -f server.conf":

% netstat -an | grep 6782
tcp4       0      0  10.128.187.XXX.6782    *.*                    LISTEN
